### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by mrbrdo** [jeremyevans/sequel#1022]
sequel 4.23.0
jdbc-postgres 9.2.1002.1
jRuby 1.7.19
postgres 9.3.3.0

example: https://github.com/mrbrdo/sequel_2connect_bug

as discussed on IRC. fails on the second `connect`. DB has hstore extension and column with a default value. there is no data in the DB except in a schema_migrations table (from ActiveRecord not Sequel). the error occurs when executing the query from `postgres.rb:709`. it fails the same no matter how it's executed (doesn't need to be select_map). it fails the same no matter the results of the query (e.g. empty or 1 row), which works fine when executed in `psql` cli. does not fail if `db.extension :pg_hstore` is removed.
no errors with sequel 4.1.1. tested locally on OS X and on CI (linux).

```
NoMethodError: undefined method `[]' for nil:NilClass
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:751:in `type_convertor'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:777:in `process_result_set'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:775:in `times'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:775:in `process_result_set'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:714:in `fetch_rows'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:251:in `execute'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:651:in `statement'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:246:in `execute'
/path/gems/sequel-4.23.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/path/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:255:in `synchronize'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:245:in `execute'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:921:in `execute'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:714:in `fetch_rows'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:139:in `each'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:390:in `map'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:390:in `map'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:848:in `_select_map_multiple'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:881:in `_select_map'
/path/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:617:in `select_map'
/path/gems/sequel-4.23.0/lib/sequel/adapters/shared/postgres.rb:709:in `convert_named_procs_to_procs'
/path/gems/sequel-4.23.0/lib/sequel/adapters/shared/postgres.rb:570:in `add_named_conversion_procs'
/path/gems/sequel-4.23.0/lib/sequel/adapters/shared/postgres.rb:943:in `get_conversion_procs'
/path/gems/sequel-4.23.0/lib/sequel/adapters/shared/postgres.rb:424:in `reset_conversion_procs'
/path/gems/sequel-4.23.0/lib/sequel/adapters/shared/postgres.rb:985:in `initialize_postgres_adapter'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc/postgresql.rb:49:in `extended'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc/postgresql.rb:10:in `extend'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc/postgresql.rb:10:in `JDBC'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:359:in `call'
/path/gems/sequel-4.23.0/lib/sequel/adapters/jdbc.rb:359:in `adapter_initialize'
/path/gems/sequel-4.23.0/lib/sequel/database/misc.rb:142:in `initialize'
/path/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:66:in `connect'
/path/gems/sequel-4.23.0/lib/sequel/core.rb:95:in `connect'
```

**Comment by jeremyevans** [comment]
Can you test the following patch and let me know if it works?

```
diff --git a/lib/sequel/adapters/jdbc.rb b/lib/sequel/adapters/jdbc.rb
index ae93a48..eee26dd 100644
--- a/lib/sequel/adapters/jdbc.rb
+++ b/lib/sequel/adapters/jdbc.rb
@@ -354,14 +354,13 @@ module Sequel
         raise(Error, "No connection string specified") unless uri

         resolved_uri = jndi? ? get_uri_from_jndi : uri
+        setup_type_convertor_map

         @driver = if (match = /\Ajdbc:([^:]+)/.match(resolved_uri)) && (prok = Sequel::Database.load_adapter(match[1].to_sym, :map=>DATABASE_SETUP, :subdir=>'jdbc'))
           prok.call(self)
         else
           @opts[:driver]
         end
-
-        setup_type_convertor_map
       end

       # Yield the native prepared statements hash for the given connection

```

**Comment by mrbrdo** [comment]
no error after applying this patch.

**Comment by jeremyevans** [comment]
Great!  I'll run more tests locally and push that afterward assuming no errors.

**Comment by jeremyevans** [comment]
Looks like this patch causes failures when using sqlite with jdbc.  I'll have to figure that out before I can commit this.

**Comment by mrbrdo** [comment]
thanks!
