### ISSUE TITLE
ArgumentError is displayed when trying to print Sequel Dataset

### ISSUE THREAD

**Issue by Adam89** [jeremyevans/sequel#1023]
Hi Jeremy

I've come across an issue when using sequel and the awesome print gem together.

The following code snippet raises an error
```
db =  Sequel.connect(file)
ap db[:products].where(name: 'clioco')
```

```
.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:687:in `to_hash': wrong number of arguments (0 for 1..2) (ArgumentError)
	from .rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:67:in `awesome_self'
	from .rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib/awesome_print/formatter.rb:28:in `format'
	from .rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:137:in `unnested'
	.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib/awesome_print/inspector.rb:104:in `awesome'
	.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib/awesome_print/core_ext/kernel.rb:10:in `ai'
	.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/awesome_print-1.6.1/lib/awesome_print/core_ext/kernel.rb:20:in `ap'
	from connnect_with_yaml.rb:13:in `<main>'
```

For more information please refer to https://github.com/michaeldv/awesome_print/issues/196

**Comment by jeremyevans** [comment]
This is a bug in awesome_print.  It shouldn't assume that `to_hash` on an arbitrary object takes no arguments.

**Comment by Adam89** [comment]
Thanks for the swift response
