### ISSUE TITLE
PG::ReadOnlySqlTransaction: ERROR:  cannot execute SELECT FOR UPDATE in a read-only transaction 

### ISSUE THREAD

**Issue by kg1990** [jeremyevans/sequel#1041]
Hi,

when I use lock! to lock a column for_update I got this error
```
/usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `async_exec': PG::ReadOnlySqlTransaction: ERROR:  cannot execute SELECT FOR UPDATE in a read-only transaction (Sequel::DatabaseError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `block in execute_query'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/logging.rb:33:in `log_yield'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:180:in `execute_query'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:143:in `check_disconnect_errors'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:167:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:512:in `_execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block (2 levels) in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:533:in `check_database_errors'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `block in execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/sharded_threaded.rb:126:in `hold'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:336:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:921:in `execute'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/adapters/postgres.rb:656:in `fetch_rows'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:139:in `each'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:644:in `single_record'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/dataset/actions.rb:192:in `first'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1852:in `_refresh_get'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1846:in `_refresh'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/model/base.rb:1391:in `lock!'
	from sequel_lock_test.rb:16:in `block in <main>'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:134:in `_transaction'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:108:in `block in transaction'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `block in synchronize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/connection_pool/sharded_threaded.rb:126:in `hold'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/connecting.rb:250:in `synchronize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/sequel-4.23.0/lib/sequel/database/transactions.rb:97:in `transaction'
	from sequel_lock_test.rb:14:in `<main>'
```

this is how I connet my database
```
require 'sequel'
Sequel::Model.db = DB = Sequel.postgres(:host => 'pg host ip',
                                         :port => port,
                                         :user => 'pg user',
                                         :password => 'pg password',
                                         :database => 'database',
                                         :max_connections => 20,
                                         :pool_timeout => 5,
                                         :servers=>{:read_only=>{:host=>'pg readonly server'}})

#include my model gem
DB.transaction do
  account = Account.first
  account.lock!
end
```

I think when use lock! the db server can change to :default, than can exec the "for_update" sql.

**Comment by jeremyevans** [comment]
One of the problems with this is the `Account.first` call is not inside the transaction.  The transaction will use the :default server, but since `Account.first` just issues a select, it will use the :read_only server.

For what you are doing, it's best to use the server_block extension:

```ruby
DB.extension :server_block
DB.with_server(:default) do
  DB.transaction do
    account = Account.first
    account.lock!
  end
end
```

Or call `for_update` directly with a server specified:

```ruby
DB.transaction do
  account = Account.for_update.server(:default).first
end
```

The main issue with changing Sequel to automatically send queries that use `FOR UPDATE` to the :default server instead of a :read_only server is the code path you would have to add it to is one of the hot paths and I don't want to negatively affect performance for the vast majority of users.  Also, such a change would only handle cases when using the DSL, it wouldn't work if you did:

```ruby
DB['SELECT * FROM accounts FOR UPDATE LIMIT 1']
```

I suppose I could consider such a change in an extension that would ship with Sequel.  Please let me know if one of the above options would work for you, or if you think Sequel should ship and extension that tries to handle some cases automatically.

**Comment by kg1990** [comment]
Thank you for your reply. 

I'm a little confused when someone going to use lock! or for_update, it must be execute in the :default server, and then sequel can choose which server to execute, so programmer unnecessary to care which server to use.  This is just personal thoughts.

**Comment by jeremyevans** [comment]
I agree it would be nice if Sequel just picked the correct server in this case.  Looking at the code, it's already setup so that Sequel users who are not using sharding don't have to pay a penalty to support this, so it is something that can be included by default. Can you please test this diff and let me know if it works for you?  

```diff
diff --git a/lib/sequel/dataset/actions.rb b/lib/sequel/dataset/actions.rb
index a574a37..2d49b4d 100644
--- a/lib/sequel/dataset/actions.rb
+++ b/lib/sequel/dataset/actions.rb
@@ -915,7 +915,7 @@ module Sequel
       db = @db
       if db.sharded?
         opts = Hash[opts]
-        opts[:server] = @opts[:server] || :read_only
+        opts[:server] = @opts[:server] || (@opts[:lock] ? :default : :read_only)
         opts
       end
       db.execute(sql, opts, &block)
```

**Comment by kg1990** [comment]
I'm test in my code, it works well.

**Comment by kg1990** [comment]
It works well.
