### ISSUE TITLE
Support for non-integer primary keys

### ISSUE THREAD

**Issue by tymat** [jeremyevans/sequel#1098]
Sqlite Schema
```
DB.create_table :orders do
  String :order_id, primary_key: true
  String :sku
  String :owner
  Bool :processed, default: false
end
```
Model
```
module Storage
  class Gold < Sequel::Model(DB[:golds])
  end

  class Order < Sequel::Model(DB[:orders])
  end

end
```

Error
```
Storage::Gold.create({address: "#1231123"})
Sequel::DatabaseError: SQLite3::SQLException: no such column: id
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:266:in `query'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/adapters/sqlite.rb:185:in `block (2 levels) in _execute'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/logging.rb:33:in `log_yield'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/adapters/sqlite.rb:185:in `block in _execute'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `synchronize'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/adapters/sqlite.rb:178:in `_execute'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/adapters/sqlite.rb:128:in `execute'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:950:in `execute'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/adapters/sqlite.rb:319:in `fetch_rows'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:833:in `with_sql_each'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:841:in `with_sql_first'
... 6 levels...
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:1933:in `_save'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:1547:in `block (2 levels) in save'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:2046:in `block in checked_transaction'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/transactions.rb:134:in `_transaction'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/transactions.rb:108:in `block in transaction'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `synchronize'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/database/transactions.rb:97:in `transaction'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:2046:in `checked_transaction'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:1547:in `block in save'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:2034:in `checked_save_failure'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:1547:in `save'
	from /Users/aeufemio/.rvm/gems/ruby-2.2.3@digixcore/gems/sequel-4.28.0/lib/sequel/model/base.rb:148:in `create'
	from (irb):42
	from /Users/aeufemio/.rvm/rubies/ruby-2.2.3/bin/irb:15:in `<main>'2.2.3 :043 >
```

**Comment by odigity** [comment]
Some suggestions...

1. You should include the schema for the Gold model.

2. As per the the CONTRIBUTING guidelines, issues should only be opened when you're certain you've discovered a bug in Sequel, and should include a fully executable test case:

https://github.com/jeremyevans/sequel/blob/master/CONTRIBUTING

For questions, try IRC channel #sequel or Google Group sequel-talk:

https://groups.google.com/forum/#!forum/sequel-talk

**Comment by jeremyevans** [comment]
I can't recreate this error.  Here's a test case I used:

```ruby
DB.create_table :golds do
  String :order_id, primary_key: true
  String :address
end

class Gold < Sequel::Model
end

# Raises ConstraintException, expected because order_id is NULL
Gold.create(:address => "#1231123")

# Works correctly
Gold.create(:address => "#1231123"){|g| g.order_id = 'a'}
```

Please include a small self contained example showing the failure if you would like this to be reopened.

**Comment by tymat** [comment]
Thanks.  That seems to work.
