### ISSUE TITLE
Can't execute prepared insert with JSONB data

### ISSUE THREAD

**Issue by zedalaye** [jeremyevans/sequel#1099]
Hello,

I'm new to Sequel. I know Postgres and ActiveRecord. I'm coding a non rails project to mass insert loads of JSONB values into PG.

```ruby
require 'sequel'
require 'pg'

Sequel.extension :pg_array, :pg_json

module LoadJSONBProject
  class Storage
    def initialize(environment = 'development', options = {})
      @logger = options.delete(:logger)
      raw_config = YAML::load_file("../config/database.yml")
      config = raw_config[environment]['url']

      @client = Sequel.connect(config)

      @client.create_table(:files) do
        primary_key :id
        String  :user_code
        Date    :date
        String  :name
      end

      @client.create_table(:lines) do
        foreign_key :file_id, :files
        Integer :number
        String  :code
        jsonb   :data
        primary_key [:file_id, :number], name: :lines_pk
      end

      @client.run('CREATE INDEX lines_data_gin ON lines USING GIN (data jsonb_path_ops);')

      @file_insert = @client[:files].prepare(:insert, :insert_file, nim: :$nim, date: :$date, name: :$name)
      @line_insert = @client[:lines].prepare(:insert, :insert_line, file_id: :$file_id, number: :$number, code: :$code, data: :$data)
    end

    def store(data)
      data.each do |nim, data|
        @client.transaction do
          @client.after_commit { @logger.info "SUCCESS" }
          @client.after_rollback { @logger.info "FAILURE" }

          @logger.info "Storing raw_data for #{user_code}"
          data.map do |file|
            file_id = @file_insert.call( # @client[:files].insert(
              user_code: file[:user_code],
              date: file[:date],
              name: file[:file]
            )

            file[:contents].map.with_index do |line, index|
              @line_insert.call( # @client[:lines].insert
                file_id: file_id,
                number: index + 1,
                code: line[:code],
                data: Sequel.pg_jsonb(line)
              )
            end
          end
        end
      end
    end

  end
end
```
I works well with direct ```@client[:table].insert(...)``` but not with ```call()``` on prepared statements.

Here is the exception: 

```
/home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:530:in `exec_prepared': PG::InvalidTextRepresentation: ERREUR:  syntaxe en entrée invalide pour le type json (Sequel::DatabaseError)
DETAIL:  Chaîne ou « } » attendu, mais « : » trouvé
CONTEXT:  données JSON, ligne 1 : {:...
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:530:in `_execute_prepared_statement'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:597:in `block (2 levels) in execute_prepared_statement'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/logging.rb:33:in `log_yield'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:597:in `block in execute_prepared_statement'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:147:in `check_disconnect_errors'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:597:in `execute_prepared_statement'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:522:in `_execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:340:in `block (2 levels) in execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:545:in `check_database_errors'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:340:in `block in execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/database/connecting.rb:249:in `synchronize'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:340:in `execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/actions.rb:950:in `execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/prepared_statements.rb:31:in `execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/prepared_statements.rb:31:in `execute'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:668:in `fetch_rows'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/shared/postgres.rb:1221:in `run'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/dataset/prepared_statements.rb:53:in `call'
	from /home/pierre/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/sequel-4.28.0/lib/sequel/adapters/postgres.rb:756:in `call'
... { my code }
```

**Comment by jeremyevans** [comment]
Thanks for the detailed report.  You need to switch from `Sequel.extension :pg_array, :pg_json` to `DB.extension :pg_array, :pg_json`, where `DB` is your `Sequel::Database` instance.
