### ISSUE TITLE
Database#create_table? breaks inside transactions

### ISSUE THREAD

**Issue by Overbryd** [jeremyevans/sequel#1100]
*EDIT: I might as well be wrong, and this issue needs a second pair of eyes. I tried writing a reproducible case for this issue, and it seemed to work fine without the patch.*

I am running a simple setup that uses database_cleaner to create a transaction for tests.
Unfortunately this does not play well with `create_table?`, and thus any `table_exists?` functionality provided in Sequel. I am assuming this is the root cause of the error.

The failing tests raise this error: `Sequel::DatabaseError: PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block`

The backtrace looks something like this:

```
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:184:in `async_exec'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:184:in `block in execute_query'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/logging.rb:33:in `log_yield'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:184:in `execute_query'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:171:in `block in execute'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:147:in `check_disconnect_errors'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:171:in `execute'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:524:in `_execute'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:340:in `block (2 levels) in execute'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:545:in `check_database_errors'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:340:in `block in execute'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `block in synchronize'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/connection_pool/threaded.rb:99:in `hold'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/connecting.rb:249:in `synchronize'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/adapters/postgres.rb:340:in `execute'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/query.rb:50:in `execute_dui'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/query.rb:43:in `execute_ddl'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/schema_methods.rb:661:in `create_table_from_generator'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/schema_methods.rb:195:in `create_table'
    /Users/lukas/.rbenv/versions/2.2.3/gemsets/bitcoinppi/gems/sequel-4.27.0/lib/sequel/database/schema_methods.rb:223:in `create_table?'
```

Here is an excerpt of the postgres server logs:

```
ERROR:  relation "bitcoinppi_7_days" does not exist at character 27
STATEMENT:  SELECT NULL AS "nil" FROM "bitcoinppi_7_days" LIMIT 1
ERROR:  current transaction is aborted, commands ignored until end of transaction block
STATEMENT:  CREATE TABLE "bitcoinppi_7_days" ("time" timestamptz NOT NULL, "tick" timestamptz NOT NULL, "country" varchar(255) NOT NULL, "c
urrency" char(3) NOT NULL, "source" varchar(255), "bitcoin_price" numeric(10, 2) NOT NULL, "bigmac_price" numeric(10, 2) NOT NULL, "weight"
 numeric(7, 6), "local_ppi" numeric(14, 6) NOT NULL, "global_ppi" numeric(14, 6) NOT NULL, PRIMARY KEY ("country", "tick"))
```

The problem might be that Sequel relies on [a database error to be thrown](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/query.rb#L196).
There are other ways to check wether a table does not exist (e.g. http://stackoverflow.com/a/24089729/128351).

My workaround (**only works for PostgreSQL 9.4+**) is to patch `Sequel::Database#table_exists?` with the following code:

```ruby
module Sequel
  class Database

    def table_exists?(name)
      schema_and_table_name = schema_and_table(name).compact.join(".")
      regclass = select{ to_regclass(schema_and_table_name) }.single_value
      !regclass.nil?
    end

  end
end
```

Unfortunately, my knowledge of the various databases Sequel supports is very weak. So I tried to heal my own wound focusing on my own environment.
Maybe a more generic non-error-throwing table existence check would be beneficial to other users too.

Best regards, Lukas

**Comment by jeremyevans** [comment]
Sequel previously had code that would try to parse metadata to determine table existence, instead of just issuing a query and checking for an exception.  It had corner cases and required database-specific code, so I decided to go back to the simple approach.

I think one way we could work around this would be to run the table exists check in it's own savepoint if the database supports savepoints.  That way it won't rollback the surrounding transaction.  I'll try that and see if it works.
