### ISSUE TITLE
Date/Time functions and operations

### ISSUE THREAD

**Issue by dalizard** [jeremyevans/sequel#1110]
I'm having a trouble with a simple functionality. I am looking for a way to convert this Ruby (`ActiveSupport`) code:
```
24.hours.from_now
```
to a PostgreSQL function, which calculates the same time, basically:
```
select now() + interval '24 hours';
```
I know `Sequel::SQL::Function` exists, but I couldn't find a way to pass in the arguments or fetch the result. Any suggestions? :heart:

**Comment by rohitn** [comment]
@dalizard Have you tried the date_arithmetic extension?

http://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/date_arithmetic_rb.html

**Comment by dalizard** [comment]
@rohitn I am not sure how the first parameter to the method is used. It seems like it has to be a database column. What I am trying to achieve is build a query similar to:
```
User.where(status: 'active').and { expired_at <= 24.hours.from_now }
```

**Comment by rohitn** [comment]
@dalizard This should work, no?

```ruby
$ sequel mock://postgres
Your database is stored in DB...
2.2.2 :001 > require 'active_support/all'
 => true
2.2.2 :002 > one_day_ahead = 24.hours.from_now
 => 2015-12-01 08:42:31 -0600
2.2.2 :003 > DB[:users].where(status: 'active').and{expired_at <= one_day_ahead}
 => #<Sequel::Mock::Dataset: "SELECT * FROM \"users\" WHERE ((\"status\" = 'active') AND (\"expired_at\" <= '2015-12-01 08:42:31.771596-0600'))">
```

**Comment by janko-m** [comment]
Hmm, I've tried `DB.select(Sequel.date_add(Sequel::CURRENT_TIMESTAMP, hours: 24))` with Postgres, but I get the error:

```
NoMethodError: undefined method `date_add_sql_append' for #<Sequel::Postgres::Dataset:0x007f8f442a5b90>
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/sql.rb:107:in `to_s_append'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:1207:in `literal_expression_append'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:85:in `literal_append'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:1007:in `block in expression_list_append'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:1005:in `each'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:1005:in `expression_list_append'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:916:in `column_list_append'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:1331:in `select_columns_sql'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:232:in `select_sql'
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/lib/sequel/dataset/sql.rb:146:in `sql'
        from (irb):3
        from /Users/janko/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/sequel-4.27.0/bin/sequel:251:in `<top (required)>'
        from /Users/janko/.rbenv/versions/2.2.2/bin/sequel:23:in `load'
        from /Users/janko/.rbenv/versions/2.2.2/bin/sequel:23:in `<main>'
```

I get this error wherever I try to use the `Sequel.date_add` expression, even when executing the example from the extension documentatation.

**Comment by dalizard** [comment]
@rohitn It does work :smile_cat: However, I was trying to use the database time and skip ActiveSupport calls. I managed to get it work with the following:
```
User.where(status: 'active').and("expired_at <= now() + interval '24 hours'")
```

@janko-m You'd have to load the extension first:
```
DB.extension :date_arithmetic
```

**Comment by janko-m** [comment]
Aha, for some reason `DB.extension :date_arithmetic` didn't work, so I did `Sequel.extension :date_arithmetic`, but that was obviously wrong. Ok, so when you load the database extension, you can do

```rb
User.where(status: 'active').and{expired_at <= Sequel.date_add(Sequel::CURRENT_TIMESTAMP, days: 1)}
```
