### ISSUE TITLE
Inconsistent updates to jsonb column from model attribute set as [] or {}

### ISSUE THREAD

**Issue by gregburek** [jeremyevans/sequel#1142]
Given a schema of:

```
                             Table "public.tests"
   Column    |           Type           |              Modifiers
-------------+--------------------------+-------------------------------------
 uuid        | uuid                     | not null default uuid_generate_v4()
 message_set | jsonb                    |
 updated_at  | timestamp with time zone |
 created_at  | timestamp with time zone | default now()
Indexes:
    "tests_pkey" PRIMARY KEY, btree (uuid)
```

And class definition of

```
Sequel.extension :pg_array, :pg_array_ops, :pg_json
class Test < Sequel::Model
  plugin :dirty
  plugin :timestamps
end
```

The handling of message_set, set to `[]` and `{}`, which are stored as NULL in postgres, is subtly different.

```
[7] gregburek(main)> Test.all
I, [2016-02-10T03:17:53.837639 #60271]  INFO -- : (0.085448s) SELECT * FROM "tests"
[]
[8] gregburek(main)> t = Test.create
I, [2016-02-10T03:18:12.683542 #60271]  INFO -- : (0.085724s) BEGIN
I, [2016-02-10T03:18:12.774104 #60271]  INFO -- : (0.089962s) INSERT INTO "tests" ("created_at") VALUES ('2016-02-10 03:18:12.597680+0000') RETURNING *
I, [2016-02-10T03:18:12.859396 #60271]  INFO -- : (0.084974s) COMMIT
#<Test:0x007fad31cea3e8> {
     :created_at => 2016-02-10 03:18:12 +0000,
    :message_set => nil,
     :updated_at => nil,
           :uuid => "3d1a998a-c396-4566-9064-2b6da95a59ff"
}
[9] gregburek(main)> t.message_set = []
[]
[10] gregburek(main)> t.changed_columns
[
    [0] :message_set
]
[11] gregburek(main)> t.column_changes
{
    :message_set => [
        [0] nil,
        [1] []
    ]
}
[12] gregburek(main)> t.save_changes
I, [2016-02-10T03:19:18.802886 #60271]  INFO -- : (0.084546s) BEGIN
I, [2016-02-10T03:19:18.911158 #60271]  INFO -- : (0.099389s) UPDATE "tests" SET "message_set" = (NULL), "updated_at" = '2016-02-10 03:19:18.804331+0000' WHERE ("uuid" = '3d1a998a-c396-4566-9064-2b6da95a59ff')
I, [2016-02-10T03:19:19.000512 #60271]  INFO -- : (0.088693s) COMMIT
#<Test:0x007fad31cea3e8> {
     :created_at => 2016-02-10 03:18:12 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 03:19:18 +0000,
           :uuid => "3d1a998a-c396-4566-9064-2b6da95a59ff"
}
[13] gregburek(main)> t.reload
I, [2016-02-10T03:19:24.387399 #60271]  INFO -- : (0.104554s) SELECT * FROM "tests" WHERE ("uuid" = '3d1a998a-c396-4566-9064-2b6da95a59ff') LIMIT 1
#<Test:0x007fad31cea3e8> {
     :created_at => 2016-02-10 03:18:12 +0000,
    :message_set => nil,
     :updated_at => 2016-02-10 03:19:18 +0000,
           :uuid => "3d1a998a-c396-4566-9064-2b6da95a59ff"
}
[14] gregburek(main)> t.message_set = {}
{}
[15] gregburek(main)> t.column_changes
{
    :message_set => [
        [0] nil,
        [1] {}
    ]
}
[16] gregburek(main)> t.save_changes
I, [2016-02-10T03:20:55.071098 #60271]  INFO -- : (0.094018s) BEGIN
I, [2016-02-10T03:20:55.160230 #60271]  INFO -- : (0.088167s) ROLLBACK
Sequel::Error: The AND operator requires at least 1 argument
from ./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/sql.rb:218:in `initialize'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/sql.rb:1006:in `new'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/sql.rb:1006:in `from_value_pairs'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:1207:in `literal_hash_append'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:83:in `literal_append'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:1543:in `block in update_set_sql'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:1535:in `each'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:1535:in `update_set_sql'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:228:in `_update_sql'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/sql.rb:174:in `update_sql'
./vendor/bundle/ruby/2.3.0/gems/sequel-4.17.0/lib/sequel/dataset/actions.rb:769:in `update'
[17] gregburek(main)> t.update(message_set: {})
nil
[18] gregburek(main)> t.update(message_set: [])
I, [2016-02-10T03:55:46.456516 #60271]  INFO -- : (0.086243s) BEGIN
I, [2016-02-10T03:55:46.547876 #60271]  INFO -- : (0.085668s) UPDATE "tests" SET "message_set" = (NULL), "updated_at" = '2016-02-10 03:55:46.457602+0000' WHERE ("uuid" = '3d1a998a-c396-4566-9064-2b6da95a59ff')
I, [2016-02-10T03:55:46.638191 #60271]  INFO -- : (0.089596s) COMMIT
#<Test:0x007fad31cea3e8> {
     :created_at => 2016-02-10 03:18:12 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 03:55:46 +0000,
           :uuid => "3d1a998a-c396-4566-9064-2b6da95a59ff"
}
[19] gregburek(main)> t.reload
I, [2016-02-10T03:55:54.209404 #60271]  INFO -- : (0.085857s) SELECT * FROM "tests" WHERE ("uuid" = '3d1a998a-c396-4566-9064-2b6da95a59ff') LIMIT 1
#<Test:0x007fad31cea3e8> {
     :created_at => 2016-02-10 03:18:12 +0000,
    :message_set => nil,
     :updated_at => 2016-02-10 03:55:46 +0000,
           :uuid => "3d1a998a-c396-4566-9064-2b6da95a59ff"
}
```

The timestamp plugin exacerbates this issue, as the updated_at column continually increases with each otherwise empty update, leading to bloat. 

The four test cases are 

1. `t.message_set = []; t.save_changes`
1. `t.message_set = {}; t.save_changes`
1. `t.update(message_set: {})`
1. `t.update(message_set: [])`

I believe the exception trace of test case 2 is a bug and the spurious dirtying of the model of no. 1 and update of no. 4 are undesirable. Test case 3 behaves as expected. 

Gemfile.lock:

```
    sequel (4.17.0)
    sequel-paranoid (0.4.3)
      sequel
    sequel_pg (1.6.11)
      pg (>= 0.8.0)
      sequel (>= 3.39.0)
```

The database used here is postgres 9.5.0

**Comment by janko-m** [comment]
Loading the `pg_json` and `pg_array` extension via `Sequel.extension` will not automatically make your models recognize arrays and hashes as JSON values, you have to convert them to Sequel's types, with `Sequel.pg_json({})` or `Sequel.pg_array([])`.

To make models automatically recognize these values, you need to load through the database object, so `DB.extension :pg_array, :pg_json` if you store the database object in a `DB` constant. Note that you need to load this extension before any models are loaded, so that it is loaded before the schema is parsed. In our app we didn't have a global `DB` object, so we used `Sequel::Database.extension :pg_array, :pg_json`, which loads extensions as soon as the database object is instantiated.

**Comment by gregburek** [comment]
That seems to fix all of the problems:

```
[2] gregburek(main)> t = Test.create
I, [2016-02-10T08:07:19.563494 #63899]  INFO -- : (0.084776s) BEGIN
I, [2016-02-10T08:07:19.654223 #63899]  INFO -- : (0.090112s) INSERT INTO "tests" ("created_at") VALUES ('2016-02-10 08:07:19.478541+0000') RETURNING *
I, [2016-02-10T08:07:19.745011 #63899]  INFO -- : (0.090495s) COMMIT
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => nil,
     :updated_at => nil,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[3] gregburek(main)> t.message_set = []
[]
[5] gregburek(main)> t.column_changes
{
    :message_set => [
        [0] nil,
        [1] []
    ]
}
[6] gregburek(main)> t.save_changes
I, [2016-02-10T08:07:54.364949 #63899]  INFO -- : (0.084759s) BEGIN
I, [2016-02-10T08:07:54.497422 #63899]  INFO -- : (0.085260s) UPDATE "tests" SET "message_set" = '[]'::jsonb, "updated_at" = '2016-02-10 08:07:54.365170+0000' WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6')
I, [2016-02-10T08:07:54.581367 #63899]  INFO -- : (0.083749s) COMMIT
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 08:07:54 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[7] gregburek(main)> t.reload
I, [2016-02-10T08:07:57.820247 #63899]  INFO -- : (0.197101s) SELECT * FROM "tests" WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6') LIMIT 1
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 08:07:54 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[8] gregburek(main)> t.message_set = {}
{}
[9] gregburek(main)> t.save_changes
I, [2016-02-10T08:08:18.268920 #63899]  INFO -- : (0.084958s) BEGIN
I, [2016-02-10T08:08:18.359289 #63899]  INFO -- : (0.089717s) UPDATE "tests" SET "message_set" = '{}'::jsonb, "updated_at" = '2016-02-10 08:08:18.269056+0000' WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6')
I, [2016-02-10T08:08:18.448531 #63899]  INFO -- : (0.089059s) COMMIT
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => {},
     :updated_at => 2016-02-10 08:08:18 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[10] gregburek(main)> t.reload
I, [2016-02-10T08:08:22.493048 #63899]  INFO -- : (0.085137s) SELECT * FROM "tests" WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6') LIMIT 1
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => {},
     :updated_at => 2016-02-10 08:08:18 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[11] gregburek(main)> t.update(message_set: {})
nil
[12] gregburek(main)> t.update(message_set: [])
I, [2016-02-10T08:08:38.386240 #63899]  INFO -- : (0.084307s) BEGIN
I, [2016-02-10T08:08:38.475261 #63899]  INFO -- : (0.088380s) UPDATE "tests" SET "message_set" = '[]'::jsonb, "updated_at" = '2016-02-10 08:08:38.386374+0000' WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6')
I, [2016-02-10T08:08:38.564596 #63899]  INFO -- : (0.089148s) COMMIT
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 08:08:38 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[13] gregburek(main)> t.reload
I, [2016-02-10T08:08:44.789620 #63899]  INFO -- : (0.085669s) SELECT * FROM "tests" WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6') LIMIT 1
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 08:08:38 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[14] gregburek(main)> t.update(message_set: {})
I, [2016-02-10T08:11:18.221371 #63899]  INFO -- : (0.093767s) BEGIN
I, [2016-02-10T08:11:18.311047 #63899]  INFO -- : (0.083894s) UPDATE "tests" SET "message_set" = '{}'::jsonb, "updated_at" = '2016-02-10 08:11:18.222327+0000' WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6')
I, [2016-02-10T08:11:18.414870 #63899]  INFO -- : (0.103225s) COMMIT
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => {},
     :updated_at => 2016-02-10 08:11:18 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[15] gregburek(main)> t.update(message_set: [])
I, [2016-02-10T08:11:23.727305 #63899]  INFO -- : (0.084426s) BEGIN
I, [2016-02-10T08:11:23.816628 #63899]  INFO -- : (0.087350s) UPDATE "tests" SET "message_set" = '[]'::jsonb, "updated_at" = '2016-02-10 08:11:23.727464+0000' WHERE ("uuid" = '4d26c322-bcc5-47fe-9dc0-c5d89e1998c6')
I, [2016-02-10T08:11:23.901798 #63899]  INFO -- : (0.084897s) COMMIT
#<Test:0x007fb76aef8a70> {
     :created_at => 2016-02-10 08:07:19 +0000,
    :message_set => [],
     :updated_at => 2016-02-10 08:11:23 +0000,
           :uuid => "4d26c322-bcc5-47fe-9dc0-c5d89e1998c6"
}
[16] gregburek(main)> t.update(message_set: [])
nil
```

Thanks!
