### ISSUE TITLE
Default value for pg_enum extension

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/sequel#1144]
Hi!
I can't use `default` flag when create enum-column with `pg_enum` extension:
```ruby
create_enum :enum_action, [:follow, :unfollow, :like]
# ...
create_table :table_name do
  # ...
  enum_action :action, null: false, default: :follow
  # ...
end
```

```bash
Sequel::DatabaseError: PG::UndefinedColumn: ERROR:  column "follow" does not exist
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:186:in `async_exec'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:186:in `block in execute_query'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/logging.rb:35:in `log_yield'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:186:in `execute_query'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:173:in `block in execute'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:173:in `execute'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:526:in `_execute'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:342:in `block (2 levels) in execute'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:547:in `check_database_errors'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:342:in `block in execute'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/connection_pool/threaded.rb:101:in `hold'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/connecting.rb:251:in `synchronize'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/adapters/postgres.rb:342:in `execute'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/query.rb:52:in `execute_dui'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/query.rb:45:in `execute_ddl'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/schema_methods.rb:666:in `create_table_from_generator'
/home/alex/.gem/ruby/2.3.0/gems/sequel-4.31.0/lib/sequel/database/schema_methods.rb:197:in `create_table'
```
(It's all in migration, yes)

**Comment by jeremyevans** [comment]
You need to specify the enum `:default` value as a string.  A symbol is interpreted as a column reference.

```
enum_action :action, null: false, default: 'follow'
```

**Comment by AlexWayfer** [comment]
Thanks!
I read [this comment](https://github.com/jeremyevans/sequel/blob/master/lib/sequel/extensions/pg_enum.rb#L52) and I thought that `default` flag supports symbols too. But now I see `model code` words.
Excuse for troubling.
