### ISSUE TITLE
PGArray creates wrong SQL Translation for WHERE statements

### ISSUE THREAD

**Issue by QuAcK3RjAcK** [jeremyevans/sequel#1153]
### Complete Description of Issue
PGArray raises Sequel::DatabaseError: PG::UndefinedFunction error if you want to use it in a select statements where clause. 

Background: I used Array column to save different values which i converted before in a PGArray to use this feature and saved it to the DB. Later i picked it out and wanted to use that Array for a different table in a where statement.

### Simplest Possible Self-Contained Example Showing the Bug
```
require 'sequel'
require 'sequel/extensions/core_extensions'

db = Sequel.connect(adapter: 'postgres', 
                     host: "localhost", 
                     port: 5432, 
                     database: "test", 
                     user: "postgres", 
                     password: "*******", 
                     max_connection: 1)

db.extension :pg_array

# example records which we want to select later in Backtrace block
[1,2,3,4].each do |x|
  db[:public__pg_array].insert(id: x, description: "test #{x}")
end

db[:public__pg_array].select(:id).where(id: [1,2,3,4]).sql
=> "SELECT \"id\" FROM \"public\".\"pg_array\" WHERE (\"id\" IN (1, 2, 3, 4))"

# this is crashing
db[:public__pg_array].select(:id).where(id: Sequel.pg_array([1,2,3,4])).sql
=> "SELECT \"id\" FROM \"public\".\"pg_array\" WHERE (\"id\" = ARRAY[1,2,3,4])"

```

### Full Backtrace of Exception (if any)
```
irb(main):026:0> db[:public__pg_array].select(:id).where(id: Sequel.pg_array([1,2,3,4])).all
Sequel::DatabaseError: PG::UndefinedFunction: ERROR:  Operator does not exist: integer = integer[]
LINE 1: SELECT "id" FROM "public"."pg_array" WHERE ("id" = ARRAY[1,2...
                                                         ^
HINT:  Kein Operator stimmt mit dem angegebenen Namen und den Argumenttypen Überein. Sie müssen möglicherweise ausdrückliche Typumwandlungen hinzufügen.

        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `async_exec'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `block in execute_query'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/database/logging.rb:35:in `log_yield'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:186:in `execute_query'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:173:in `block in execute'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:173:in `execute'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'

        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:341:in `execute'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:952:in `execute'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:141:in `each'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:47:in `block in all'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:892:in `_all'
        from C:/ruby-222/lib/ruby/gems/2.2.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:47:in `all'
        from (irb):26
```

### Fix

I fixed it by just reconvert the PGArray in a Ruby Array with .to_a
But i thought that PGArray is like a Subclass of Ruby Array so it should be possible to use it in where statements without to take care which class i have.

Thx in advance! Great gem btw ;)

**Comment by janko-m** [comment]
This is exactly what is supposed to happen. The whole goal of having a `PGArray` is that converting it into SQL results into `ARRAY[...]`, not `(...)` what happens with a normal array. If "id" was an array column, this is exactly what you would write to compare if it's equal to another array. If `PGArray` would act as a normal array in SQL queries, then to produce `ARRAY[...]` you would have to write raw SQL. This is exactly why `PGArray` exists, so that you don't have to use raw SQL.

**Comment by QuAcK3RjAcK** [comment]
Ok thanks!
So in all cases where i want the normal WHERE IN () behavior on attributes and want to compare with PGArray data from other tables i have to reconvert.
