### ISSUE TITLE
fetching columns doesn't work w/ -infinity as default

### ISSUE THREAD

**Issue by joevandyk** [jeremyevans/sequel#1186]
```
require 'sequel'
db = Sequel.connect('postgres://localhost/tanga_dev')
db[:promotions].columns
```

```
/usr/local/tanga/ruby-2.2.4/lib/ruby/2.2.0/time.rb:252:in `make_time': ArgumentError: no time information in "-infinity" (Sequel::InvalidValue)
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/2.2.0/time.rb:364:in `parse'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/core.rb:279:in `string_to_datetime'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/timezones.rb:136:in `convert_input_timestamp'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/timezones.rb:77:in `convert_timestamp'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/database/misc.rb:305:in `to_application_timestamp'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:514:in `to_application_timestamp'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:859:in `call'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:859:in `block (2 levels) in yield_hash_rows'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:857:in `each'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:857:in `block in yield_hash_rows'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:855:in `times'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:855:in `yield_hash_rows'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:669:in `block in fetch_rows'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:175:in `execute'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:525:in `_execute'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/database/connecting.rb:251:in `synchronize'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:341:in `execute'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:965:in `execute'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:141:in `each'
	from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.34.0/lib/sequel/dataset/actions.rb:73:in `columns'
	from rom.rb:3:in `<main>'
```
	
```
tanga_dev=# \d promotions
                                               Table "public.promotions"
            Column            |            Type             |                         Modifiers
------------------------------+-----------------------------+-----------------------------------------------------------
 id                           | integer                     | not null default nextval('promotions_id_seq'::regclass)
 start_at                     | timestamp without time zone | not null default '-infinity'::timestamp without time zone
 end_at                       | timestamp without time zone | not null default 'infinity'::timestamp without time zone
```

**Comment by jeremyevans** [comment]
This is expected behavior, set `DB.convert_infinite_timestamps = :nil # or :string or :float` to choose how you want to handle them instead of raising an error.
