### ISSUE TITLE
add_ association methods not working when passed hashes

### ISSUE THREAD

**Issue by TiagoCardoso1983** [jeremyevans/sequel#1187]
### Complete Description of Issue

The [documentation](http://sequel.jeremyevans.net/rdoc/files/doc/association_basics_rdoc.html#label-add_association-28object_to_associate-29+-28e.g.+add_album-29+-5Bone_to_many+and+many_to_many-5D) says this is possible, but it is not happening. here's a small example:

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'                             
require 'logger'                             
                                             
DB = Sequel.sqlite                           
DB.loggers = [Logger.new(STDOUT)]            
Sequel::Model.plugin :delay_add_association  
                                             
DB.create_table? :cars do                    
  primary_key :id                            
end                                          
DB.create_table? :wheels do                  
  foreign_key :car_id, :cars                 
  column :number, Integer                    
end                                          

class Car < Sequel::Model         
  one_to_many :wheels             
end                               
class Wheel < Sequel::Model       
  many_to_one :car                
end                               
                                  
puts "database is set..."                    
                                             
                                             
car = Car.new                                
# this doesn't work => car.add_wheel number: 1                      
# this works => car.add_wheel Wheel.new(number: 1)         
                                             
begin                                        
  car.save                                   
rescue                                       
  puts "BOOM!!"                              
end                                          
                                             
car.save                                     
                                             
puts "car has #{car.wheels.size} wheels..."  
puts "wheel car is #{car}..."                
                                             
DB.drop_table :wheels, :cars                 
```

Tested with sequel 4.34.0 (latest). 

### Full Backtrace of Exception (if any)

```
BOOM!!                                                                                                                
app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/validate_associated.rb:38:in `[]': no implicit conversion of Symbol into Integer (TypeError)                                                             
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/validate_associated.rb:38:in `validate_associated_object'                                                                                   
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/validate_associated.rb:30:in `block in delay_validate_associated_object'                                                                    
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/instance_hooks.rb:87:in `call'                                                                                                              
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/instance_hooks.rb:87:in `each'                                                                                                              
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/instance_hooks.rb:87:in `run_after_instance_hooks'                                                                                          
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/plugins/instance_hooks.rb:57:in `after_validation'                                                                                                  
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:2043:in `block in _valid?'                                                                                                            
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:1146:in `around_validation'                                                                                                           
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:2032:in `_valid?'                                                                                                                     
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:1568:in `block in save'                                                                                                               
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:2063:in `checked_save_failure'                                                                                                        
        from app/.bundle/ruby/2.2.0/gems/sequel-4.34.0/lib/sequel/model/base.rb:1568:in `save'          from sequel_tests.rb:36:in `<main>'                                                                           
```

**Comment by jeremyevans** [comment]
Thanks for the bug report. This happens because delay_add_association tries to validate the object before converting it from a hash to a model instance.  The behavior of the delay_add_association is currently unspecified when you pass a hash, but I agree with you that it should handle the hash case correctly.  I'll try to fix this later today.

**Comment by TiagoCardoso1983** [comment]
Thx. Btw, if you remove the plugin, you'll see that the script doesn't work in both cases. It seems that it only lets me add records to the association only if the parent is already persisted (tested also with many_to_one, also doesn't work). 

Now, I have an issue with that, as I would like to validate on the model whether the many_to_one record is present (validation_helpers plugin). Something like:

```ruby
car = Car.new

# this line doesn't work currently. If I remove the car attribute, it fails below.
car.add_wheel Wheel.new(number: 1, car: car)
# => Sequel::Error: associated object #<Car @values={}> does not have a primary key                                                                    

# my expectation: by saving the car, I'm saving the dirty associated records
car.save
```

this expectation is obviously from ActiveRecord, and I would like to find an equivalent workaround for sequel. This becomes even worse when speccing, as I'm using factory girl, and by setting the association in the factories I'm automatically invalidating the record. This would be a typical factory:

```ruby
factory :car do
  after(:build) do |car|
    car.add_wheel # and here we are again...
  end
end

factory :wheel do
  number { 42 }
  car
end
```

my expectation: ```build(:wheel)``` initializes an unpersisted instance of ```Wheel``` with an unpersisted instance of car, for example. 

How do you solve these? Do you declare factories or you have another workaround?

**Comment by jeremyevans** [comment]
`Wheel.new(number: 1, car: Car.new)` raising an error is expected, the many_to_one setter expects the argument to already be persisted first.

If you want to create both Car and Wheel at the same time, then you can use the nested_attributes or delay_add_association plugins. You could also modify the association cache directly:

```ruby
car = Car.new
wheel = Wheel.new
wheel.associations[:car] = car
car.associations[:wheels] = [wheel]
```

**Comment by TiagoCardoso1983** [comment]
just confirmed, the script works against master. Your workaround for setting the association directly is decent enough, I guess, as I only need this for defining factories, and will prefer add_* methods for my BL instead. 

Thx a lot!
