### ISSUE TITLE
ArgumentError: unexpected datetime format

### ISSUE THREAD

**Issue by kenaniah** [jeremyevans/sequel#1217]
### Complete Description of Issue

Running against Postgres 9.5 where `expires_at`, `created_at`, and `updated_at` are `TIMESTAMPTZ` fields. All other fields are `INTEGER`.

Both `created_at` and `updated_at` are managed using triggers defined by the `sequel_postgresql_triggers` gem. 

### Relevant Parts of pg.conf

```
# - Locale and Formatting -

datestyle = 'iso, mdy'
#intervalstyle = 'postgres'
timezone = 'US/Pacific'
#timezone_abbreviations = 'Default'     # Select the set of available time zone
                                        # abbreviations.  Currently, there are
                                        #   Default
                                        #   Australia (historical usage)
                                        #   India
                                        # You can create your own file in
                                        # share/timezonesets/.
#extra_float_digits = 0                 # min -15, max 3
#client_encoding = sql_ascii            # actually, defaults to database
                                        # encoding

# These settings are initialized by initdb, but they can be changed.
lc_messages = 'en_US.UTF-8'                     # locale for system error message
                                        # strings
lc_monetary = 'en_US.UTF-8'                     # locale for monetary formatting
lc_numeric = 'en_US.UTF-8'                      # locale for number formatting
lc_time = 'en_US.UTF-8'                         # locale for time formatting

# default configuration for text search
default_text_search_config = 'pg_catalog.english'
```

### SQL Log

```
(0.000119s) BEGIN
(0.000221s) PREPARE smpsp_8 AS INSERT INTO "alerts" ("organization_id", "be_on_the_lookout_id", "community_ticket_id", "location_of_interest_id", "person_of_interest_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id", "organization_id", "be_on_the_lookout_id", "community_ticket_id", "location_of_interest_id", "person_of_interest_id", "expires_at", "created_at", "updated_at"
(0.000918s) EXECUTE smpsp_8 (INSERT INTO "alerts" ("organization_id", "be_on_the_lookout_id", "community_ticket_id", "location_of_interest_id", "person_of_interest_id") VALUES ($1, $2, $3, $4, $5) RETURNING "id", "organization_id", "be_on_the_lookout_id", "community_ticket_id", "location_of_interest_id", "person_of_interest_id", "expires_at", "created_at", "updated_at"); [395, 347, nil, nil, nil]
(0.000169s) ROLLBACK
```

### Exception Backtrace

```
ArgumentError: unexpected datetime format
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:669:in `yield_hash_rows'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:669:in `block in fetch_rows'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:600:in `execute_prepared_statement'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:523:in `_execute'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:341:in `block (2 levels) in execute'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:546:in `check_database_errors'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:341:in `block in execute'
	from /.../sequel-4.36.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
	from /.../sequel-4.36.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
	from /.../sequel-4.36.0/lib/sequel/database/connecting.rb:251:in `synchronize'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:341:in `execute'
	from /.../sequel-4.36.0/lib/sequel/dataset/actions.rb:970:in `execute'
	from /.../sequel-4.36.0/lib/sequel/dataset/prepared_statements.rb:33:in `execute'
	from /.../sequel-4.36.0/lib/sequel/dataset/prepared_statements.rb:33:in `execute'
	from /.../sequel-4.36.0/lib/sequel/adapters/postgres.rb:669:in `fetch_rows'
	from /.../sequel-4.36.0/lib/sequel/dataset/actions.rb:853:in `with_sql_each'
... 67 levels...
```

**Comment by jeremyevans** [comment]
Very odd.  I originally thought this might be related to infinite timestamps, but you mentioned the use of sequel_postgresql_triggers, so that doesn't appear to be an issue, unless expires_at is defaulting to infinity.  Can you try setting `DB.convert_infinite_timestamps = :nil # or :string or :float` and see if you get the same results?

If you still get the same results, can you post a small self contained example showing the problem so I can test?

**Comment by kenaniah** [comment]
It was indeed defaulted to infinity. Would be nice if sequel caught that exception and threw a new one with a better description. I didn't really know where to look ;-)
