### ISSUE TITLE
On Postgres, tables(qualify: true) can't be passed into truncate if a table contains a '__'

### ISSUE THREAD

**Issue by pnomolos** [jeremyevans/sequel#1241]
### Complete Description of Issue

I've been trying to add multi-schema support to the database_cleaner gem, and ran into a bug when doing the following: `db.from(*db.tables(qualify: true)).truncate`.  The problem arises if a table name has a double-underscore.  Even though it's returned as a `Sequel::SQL::QualifiedIdentifier` it's still run through the '__' => '.' conversion process.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB << "CREATE TABLE i__have__underscores (id int);"
DB.from(*DB.tables(qualify: true)).truncate
```

### Full Backtrace of Exception (if any)
```
Sequel::DatabaseError:
       PG::FeatureNotSupported: ERROR:  cross-database references are not implemented: "public.i.have__underscores"
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:187:in `async_exec'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:187:in `block in execute_query'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/database/logging.rb:44:in `log_connection_yield'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:187:in `execute_query'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:174:in `block in execute'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:150:in `check_disconnect_errors'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:174:in `execute'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:527:in `_execute'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:343:in `block (2 levels) in execute'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:548:in `check_database_errors'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:343:in `block in execute'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/database/connecting.rb:279:in `block in synchronize'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/database/connecting.rb:279:in `synchronize'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/postgres.rb:343:in `execute'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/database/query.rb:52:in `execute_dui'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/database/query.rb:45:in `execute_ddl'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/dataset/actions.rb:975:in `execute_ddl'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/dataset/actions.rb:809:in `truncate'
     # /Users/pnomolos/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/sequel-4.39.0/lib/sequel/adapters/shared/postgres.rb:1579:in `truncate'
```

**Comment by pnomolos** [comment]
I was going to add a failing spec for this case, but wasn't quite sure where in `postgresql_spec.rb` it should end up :)

**Comment by jeremyevans** [comment]
Thanks for the report.  That looks like a bug.   I'll fix it shortly.

**Comment by pnomolos** [comment]
@jeremyevans Awesome, thanks.

Changing line 1035 of postgres.rb to:

```ruby
ds.select_append(:pg_namespace__nspname).map{|r| Sequel.qualify(SQL::Identifier.new(m.call(r[:nspname])), SQL::Identifier.new(m.call(r[:relname])))}
```

appears to fix the problem (so that the schema and table names are identifiers, not symbols/strings) :)

**Comment by jeremyevans** [comment]
I think you can actually just use a string and not a symbol to avoid the issue, that's probably faster.

**Comment by pnomolos** [comment]
@jeremyevans Good point.  I wasn't sure how they were returned and that was the first thing I tried :)
