### ISSUE TITLE
Class Table Inheritance and Prepared Statements do not play well together

### ISSUE THREAD

**Issue by kenaniah** [jeremyevans/sequel#1244]
### Complete Description of Issue
Child classes of a model using Class Table Inheritance when the prepared statements plugin is also loaded causes `Model.[]` and `Model#refresh` to build failing queries. Appears to be caused by an issue in [`#prepared_lookup`](https://github.com/jeremyevans/sequel/blob/3a61daac311985bfea5566e2ad2c4a5a7a936580/lib/sequel/plugins/prepared_statements.rb#L99). Works perfectly when the prepared statements plugin is not loaded.

```ruby
Sequel::Model.plugin :prepared_statements

module Test 
end

class Test::Entity < Sequel::Model :test__entities
	plugin(
		:class_table_inheritance,
		key: :kind,
		model_map: {
			'vehicle' => 'Test::Vehicle'.to_sym,
			'person' => 'Test::Person'.to_sym
		},
		table_map: {
			'Test::Vehicle'.to_sym => :test__vehicles,
			'Test::Person'.to_sym => :test__people
		}
	)
end

class Test::Vehicle < Test::Entity
end

class Test::Person < Test::Entity
end
```

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
Test::Person[1] 
# yields Sequel::DatabaseError: PG::AmbiguousColumn: ERROR:  column reference "id" is ambiguous
```

### Full Backtrace of Exception (if any)
```
from .../sequel/lib/sequel/adapters/postgres.rb:594:in `prepare'
from .../sequel/lib/sequel/adapters/postgres.rb:594:in `block (2 levels) in execute_prepared_statement'
from .../sequel/lib/sequel/extensions/error_sql.rb:63:in `log_connection_yield'
from .../sequel/lib/sequel/adapters/postgres.rb:594:in `block in execute_prepared_statement'
from .../sequel/lib/sequel/adapters/postgres.rb:149:in `check_disconnect_errors'
from .../sequel/lib/sequel/adapters/postgres.rb:594:in `execute_prepared_statement'
from .../sequel/lib/sequel/adapters/postgres.rb:524:in `_execute'
from .../sequel/lib/sequel/adapters/postgres.rb:342:in `block (2 levels) in execute'
from .../sequel/lib/sequel/adapters/postgres.rb:547:in `check_database_errors'
from .../sequel/lib/sequel/adapters/postgres.rb:342:in `block in execute'
from .../sequel/lib/sequel/database/connecting.rb:279:in `block in synchronize'
from .../sequel/lib/sequel/connection_pool/threaded.rb:107:in `hold'
from .../sequel/lib/sequel/database/connecting.rb:279:in `synchronize'
from .../sequel/lib/sequel/adapters/postgres.rb:342:in `execute'
from .../sequel/lib/sequel/dataset/actions.rb:970:in `execute'
from .../sequel/lib/sequel/dataset/prepared_statements.rb:33:in `execute'
... 5 levels...
from .../sequel/lib/sequel/dataset/actions.rb:652:in `single_record'
from .../sequel/lib/sequel/dataset/actions.rb:194:in `first'
from .../sequel/lib/sequel/dataset/prepared_statements.rb:175:in `run'
from .../sequel/lib/sequel/adapters/shared/postgres.rb:1257:in `run'
from .../sequel/lib/sequel/dataset/prepared_statements.rb:55:in `call'
from .../sequel/lib/sequel/adapters/postgres.rb:764:in `call'
from .../sequel/lib/sequel/plugins/prepared_statements.rb:137:in `primary_key_lookup'
from .../sequel/lib/sequel/model/base.rb:222:in `[]'
from (irb):2
```

### SQL Log (if any)
```sql
PREPARE smpsp_1 AS 
SELECT "test"."entities"."id", "test"."entities"."kind", "test"."people"."first_name", "test"."people"."last_name" 
FROM "test"."entities" 
INNER JOIN "test"."people" ON ("test"."people"."id" = "test"."entities"."id") 
WHERE ("id" = $1) 
LIMIT 1
```

**Comment by kenaniah** [comment]
More info...

The prepared SQL statements appears to be generated via `filter(prepared_statement_key_array(primary_key))` inside of `#prepared_lookup`.

`primary_key` returns `:id`
`prepared_statement_key_array(primary_key)` returns `[[:id, :$id]]`
`filter(prepared_statement_key_array(primary_key))` returns:

> ```sql
> SELECT "test"."entities"."id", "test"."entities"."kind", "test"."people"."first_name", "test"."people"."last_name" 
> FROM "test"."entities" 
> INNER JOIN "test"."people" ON ("test"."people"."id" = "test"."entities"."id") 
> WHERE ("id" = "$id")
> ```

**Comment by jeremyevans** [comment]
I don't think prepared statements and CTI could work together, so the CTI plugin should disable the use of prepared statements.  I'll work on that shortly.
