### ISSUE TITLE
Model#update_fields fails with updatable custom primary_key

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/sequel#1273]
### Complete Description of Issue

Sequel::Model#update_fields fails when trying to update a custom primary key, for example a post slug for a blog-like application. UPDATE: Sequel::Model#update also fails under certain conditions.

### Simplest Possible Self-Contained Example Showing the Bug

Environment:

- ruby-2.3.3
- sequel-4.41.0
- sqlite3-1.3.12 (in-memory)

Migration:

```ruby
DB.create_table?(:posts) do
  String :slug, primary_key: true
  foreign_key :author_id, :authors, on_delete: :cascade
  String :title, null: false
  String :body, text: true, null: false
  DateTime :created_at
  DateTime :updated_at
end
```

Model:

```ruby
class Post < Sequel::Model
  plugin :timestamps

  unrestrict_primary_key # allow client-generated slugs

  many_to_one :author
  one_to_many :comments
  many_to_many :tags, left_key: :post_slug

  def validate
    super
    validates_not_null :author
  end
end
```

Post#create works as expected:

```
irb(main):007:0> Post.create(:author=>Author.first, :slug=>'foo-bar', :body=>'foo', :title=>'bar')
I, [2016-12-08T11:51:23.889318 #8071]  INFO -- : (0.000332s) SELECT * FROM `authors` LIMIT 1
I, [2016-12-08T11:51:23.890464 #8071]  INFO -- : (0.000065s) BEGIN
I, [2016-12-08T11:51:23.891106 #8071]  INFO -- : (0.000173s) INSERT INTO `posts` (`author_id`, `slug`, `body`, `title`, `created_at`) VALUES (1, 'foo-bar', 'foo', 'bar', '2016-12-08 11:51:23.890212')
I, [2016-12-08T11:51:23.891585 #8071]  INFO -- : (0.000248s) SELECT * FROM `posts` WHERE (`slug` = 'foo-bar') LIMIT 1
I, [2016-12-08T11:51:23.891683 #8071]  INFO -- : (0.000034s) COMMIT
=> #<Post @values={:slug=>"foo-bar", :author_id=>1, :title=>"bar", :body=>"foo", :created_at=>2016-12-08 11:51:23 -0600, :updated_at=>nil}>
```

And I can update the the just-created record using Post#update:

```
irb(main):008:0> _.update(:slug=>'bar-qux')
I, [2016-12-08T11:51:36.740596 #8071]  INFO -- : (0.000056s) BEGIN
I, [2016-12-08T11:51:36.741188 #8071]  INFO -- : (0.000241s) UPDATE `posts` SET `slug` = 'bar-qux', `updated_at` = '2016-12-08 11:51:36.740678' WHERE (`slug` = 'foo-bar')
I, [2016-12-08T11:51:36.741309 #8071]  INFO -- : (0.000040s) COMMIT
=> #<Post @values={:slug=>"bar-qux", :author_id=>1, :title=>"bar", :body=>"foo", :created_at=>2016-12-08 11:51:23 -0600, :updated_at=>2016-12-08 11:51:36 -0600}>
```

UPDATE: But not if I query it first:

```
irb(main):019:0> Post.first.update(:slug=>'qux-foo')
I, [2016-12-08T12:21:56.417046 #11286]  INFO -- : (0.000302s) SELECT * FROM `posts` LIMIT 1
I, [2016-12-08T12:21:56.417493 #11286]  INFO -- : (0.000239s) SELECT * FROM `authors` WHERE `id` = 1
I, [2016-12-08T12:21:56.417677 #11286]  INFO -- : (0.000039s) BEGIN
I, [2016-12-08T12:21:56.418211 #11286]  INFO -- : (0.000170s) UPDATE `posts` SET `slug` = 'qux-foo', `updated_at` = '2016-12-08 12:21:56.417736' WHERE (`slug` = 'qux-foo')
I, [2016-12-08T12:21:56.418501 #11286]  INFO -- : (0.000044s) ROLLBACK
Sequel::NoExistingObject: Attempt to update object did not result in a single row modification
```

And not using Post#update_fields (whether I query it first or not):

```
irb(main):015:0> Post.first.update_fields({ :slug=>'qux-foo' }, [:slug])
I, [2016-12-08T11:53:21.039116 #8071]  INFO -- : (0.000374s) SELECT * FROM `posts` LIMIT 1
I, [2016-12-08T11:53:21.039744 #8071]  INFO -- : (0.000297s) SELECT * FROM `authors` WHERE `id` = 1
I, [2016-12-08T11:53:21.040055 #8071]  INFO -- : (0.000045s) BEGIN
I, [2016-12-08T11:53:21.040656 #8071]  INFO -- : (0.000180s) UPDATE `posts` SET `slug` = 'qux-foo', `updated_at` = '2016-12-08 11:53:21.040125' WHERE (`slug` = 'qux-foo')
I, [2016-12-08T11:53:21.040946 #8071]  INFO -- : (0.000045s) ROLLBACK
Sequel::NoExistingObject: Attempt to update object did not result in a single row modification
```

Here is the workaround:

```
irb(main):023:0> Post.first.this.update(:slug=>'qux-foo')
I, [2016-12-08T12:24:11.412369 #11286]  INFO -- : (0.000385s) SELECT * FROM `posts` LIMIT 1
I, [2016-12-08T12:24:11.412932 #11286]  INFO -- : (0.000222s) UPDATE `posts` SET `slug` = 'qux-foo' WHERE (`slug` = 'foo-bar')
=> 1
```

### Full Backtrace of Exception (if any)

```
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2117:in `_update'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2110:in `_update_columns'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2064:in `block (2 levels) in _save'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1243:in `around_update'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2048:in `block in _save'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1243:in `around_save'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2034:in `_save'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1684:in `block (2 levels) in save'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `block in checked_transaction'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:215:in `_transaction'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `checked_transaction'
... 3 levels...
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1697:in `save_changes'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/model/base.rb:1847:in `update_fields'
	from (irb):17
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli/console.rb:18:in `run'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:362:in `console'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
	from /Users/mwp/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
	from /Users/mwp/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
	from /Users/mwp/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
```

### SQL Log (if any)

Embedded above.

**Comment by jeremyevans** [comment]
Thank you for posting a detailed description of the problem and a self contained example.  However, this is expected behavior.  If you have to update the primary key, use the update_primary_key plugin: http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/UpdatePrimaryKey.html

**Comment by mwpastore** [comment]
Ah, shoot. Thanks Jeremy. There is one case where you *can* update the primary key without using the plugin, noted above; would that be considered a bug, then?

**Comment by jeremyevans** [comment]
It's not a bug, just an implementation side effect.  Really, updating the primary key without the plugin is considered undefined behavior.  As long as you can update it with the plugin, then there isn't a bug.
