### ISSUE TITLE
Models using a one_to_one relationship will have deadlocks on MySQL

### ISSUE THREAD

**Issue by zrob** [jeremyevans/sequel#1274]
When assigning to a one_to_one relationship -- `model.i_have_one = one_thing.new` -- the following queries are performed in a transaction:

```sql
UPDATE "bobs" SET "alice_id" = NULL WHERE ("alice_id" = 1)
INSERT INTO "bobs" ("alice_id") VALUES (1) RETURNING *
```

This is inherently unsafe on mysql when concurrent requests performing the same operation occur due to gap locking.

```ruby
require 'sequel'

DB = Sequel.connect('mysql2://root@localhost/test')
DB.run 'create table if not exists bobs (id int AUTO_INCREMENT, alice_id int, PRIMARY KEY (id))'
DB.run 'create table if not exists alices (id int AUTO_INCREMENT, PRIMARY KEY (id))'
DB[:bobs].delete
DB[:alices].delete

class Bob < Sequel::Model
  many_to_one :alices
end

class Alice < Sequel::Model
  one_to_one :bob
end

t1 = Thread.new do
  100.times do
    a     = Alice.create
    a.bob = Bob.new  # deadlocks here
  end
end

t2 = Thread.new do
  100.times do
    a     = Alice.create
    a.bob = Bob.new  # deadlocks here
  end
end

t1.join
t2.join
```

```
/Users/pivotal/.gem/ruby/2.3.3/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query': Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction (Sequel::SerializationFailure)
	from /Users/pivotal/.gem/ruby/2.3.3/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:136:in `block in _execute'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/logging.rb:44:in `log_connection_yield'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:131:in `_execute'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `block in execute'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `execute'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/mysql2.rb:76:in `execute_insert'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:986:in `execute_insert'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:338:in `insert'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1997:in `_insert_raw'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1979:in `_insert'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2041:in `block (2 levels) in _save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1243:in `around_create'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2038:in `block in _save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1243:in `around_save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2034:in `_save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1684:in `block (2 levels) in save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `block in checked_transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:186:in `block in transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `checked_transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1684:in `block in save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2176:in `checked_save_failure'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1684:in `save'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/associations.rb:2048:in `block (2 levels) in def_one_to_many'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `block in checked_transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:215:in `_transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `checked_transaction'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/associations.rb:2046:in `block in def_one_to_many'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/associations.rb:2424:in `_set_associated_object'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/associations.rb:2454:in `set_one_to_one_associated_object'
	from /Users/pivotal/.gem/ruby/2.3.3/gems/sequel-4.41.0/lib/sequel/model/associations.rb:2051:in `block in def_one_to_many'
	from mysql_deadlock.rb:20:in `block (2 levels) in <main>'
	from mysql_deadlock.rb:18:in `times'
	from mysql_deadlock.rb:18:in `block in <main>'
```

I'm not sure if there is an alternative set of queries that actually accomplishes setting a one_to_one relationship atomically, but wanted to at least report the issue.

**Comment by jeremyevans** [comment]
Thank you for the analysis and sample code.  I don't think this is a bug, as concurrent updates to the database can result in serialization failures in many cases when you are using multiple queries, and there isn't a way that I know of to use a single query to perform this update.  I'll certainly consider alternative approaches, as long as they work on all databases that Sequel supports.

If you want, you can wrap the code in a transaction and use `:retry_on=>Sequel::SerializationFailure`, so Sequel will automatically retry the transaction in such cases.
