### ISSUE TITLE
'clone': wrong number of arguments?

### ISSUE THREAD

**Issue by maxiedaniels** [jeremyevans/sequel#1291]
After doing gem update (sequel got updated in the process), I'm getting this error:
`'clone': wrong number of arguments (given 1, expected 0) (ArgumentError)`

I'm not sure what's causing this.. here's the full backtrace:

```
.../gems/ruby-head/gems/sequel-4.42.1/lib/sequel/dataset/query.rb:89:in `clone': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /Users/me/.rvm/gems/ruby-head/gems/sequel-4.42.1/lib/sequel/dataset/query.rb:89:in `clone'
	from /Users/me/.rvm/gems/ruby-head/gems/sequel-4.42.1/lib/sequel/dataset/query.rb:265:in `from'
	from /Users/me/.rvm/gems/ruby-head/gems/sequel-4.42.1/lib/sequel/database/dataset.rb:58:in `from'
	from /Users/me/.rvm/gems/ruby-head/gems/sequel-4.42.1/lib/sequel/model/base.rb:951:in `convert_input_dataset'
	from /Users/me/.rvm/gems/ruby-head/gems/sequel-4.42.1/lib/sequel/model/base.rb:816:in `set_dataset'
	from /Users/me/.rvm/gems/ruby-head/gems/sequel-4.42.1/lib/sequel/model/base.rb:647:in `inherited'
	from myscript.rb:31:in `<main>'
```

Line 31 in my script is simply this, which has been in my code for over a month and has never been an issue:

```
class Playlist < Sequel::Model
	many_to_one :atrrib1
	many_to_many :attrib2
	one_to_many :attrib3
end
```

Any ideas?

**Comment by jeremyevans** [comment]
When is the last time you updated ruby-head?  My guess is you are using a pre release version of 2.4.0 which lacks support for `clone(:freeze=>false)`.  You should either update to the latest ruby-head or ruby-2.4.0.
