### ISSUE TITLE
Symbol#to_proc for associations

### ISSUE THREAD

**Issue by AlexWayfer** [jeremyevans/sequel#1301]
### Complete Description of Issue

I want to use `Symbol#to_proc` for associations, but receive the error.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'sequel'

DB = Sequel.connect(
  adapter: 'postgres',
  database: 'sequel_test'
)

class Album < Sequel::Model
  many_to_one :artist

  # subset(:most_sells)

  dataset_module do
    def most_sells
      order(:sells).reverse
    end
  end
end

class Artist < Sequel::Model
  one_to_many :albums
  one_to_one :the_best_album, class: Album, &:most_sells
end

p Artist.where(name: 'Elton').first.the_best_album
```

With standard block it works:

```ruby
one_to_one :the_best_album, class: Album do |ds|
  ds.most_sells
end
```

But it's dumb.

### Full Backtrace of Exception

```
/home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2135:in `instance_exec': undefined method `most_sells' for #<Artist @values={:id=>1, :name=>"Elton"}> (NoMethodError)
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2135:in `_apply_association_options'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2163:in `_dataset'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:1796:in `block in def_association_instance_methods'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2141:in `_associated_dataset'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2189:in `_load_associated_object_array'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2175:in `_load_associated_object'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2202:in `_load_associated_objects'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:2307:in `load_associated_objects'
	from /home/alex/.gem/ruby/2.4.0/gems/sequel-4.42.1/lib/sequel/model/associations.rb:1791:in `block in def_association_method'
	from test.rb:25:in `<main>'
```

### SQL Dump of Database

[sequel_test.txt](https://github.com/jeremyevans/sequel/files/748270/sequel_test.txt)

**Comment by jeremyevans** [comment]
This appears to be a bug in ruby 2.4.0, not in Sequel.  The code passes in ruby 1.8-2.3.  Please narrow down a test case and file a bug for ruby itself (bugs.ruby-lang.org).

**Comment by AlexWayfer** [comment]
I was afraid it was so. Thank you. And I'm sorry.

**Comment by jeremyevans** [comment]
Looks like this was already fixed in trunk, so no reason to file a bug upstream.  You'll probably have to wait until 2.4.1.  Here's a simple reproducer:

```ruby
H={}
def defm(&foo)
  H[:foo] = foo
end
defm &:bar
a = Object.new
def a.bar; 1; end
instance_exec(a, &H[:foo])
```

Looks like the closed bug is https://bugs.ruby-lang.org/issues/13087

**Comment by AlexWayfer** [comment]
Thank you again.
