### ISSUE TITLE
Oracle without tnsnames

### ISSUE THREAD

**Issue by Daniel-ltw** [jeremyevans/sequel#1311]
Could anyone offer a solution in this regards? 

### Complete Description of Issue
Attempting to connect to an Oracle database without a tnsnames file

### Simplest Possible Self-Contained Example Showing the Bug
Self explanatory from the above description. 
The ActiveRecord Oracle Enhanced gem does allow users to do that. 

### Full Backtrace of Exception (if any)
```
OCIError: ORA-12545: Connect failed because target host or object does not exist
oci8.c:656:in oci8lib_230.so
/usr/local/lib/ruby/gems/2.3.0/gems/ruby-oci8-2.1.8/lib/oci8/oci8.rb:148:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/adapters/oracle.rb:32:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/adapters/oracle.rb:32:in `connect'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool.rb:94:in `make_new'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:158:in `make_new'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:137:in `available'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:127:in `block in acquire'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:194:in `block in sync'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:194:in `synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:194:in `sync'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:126:in `acquire'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/connection_pool/threaded.rb:94:in `hold'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/database/connecting.rb:235:in `synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/adapters/oracle.rb:79:in `_execute'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/adapters/oracle.rb:65:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:860:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/adapters/oracle.rb:407:in `fetch_rows'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:156:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:437:in `map'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:437:in `map'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:826:in `_select_map_single'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:848:in `_select_map'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/dataset/actions.rb:602:in `select_map'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/adapters/oracle.rb:275:in `schema_parse_table'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/database/query.rb:197:in `schema'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model/base.rb:795:in `block in get_db_schema'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model/base.rb:719:in `check_non_connection_error'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model/base.rb:795:in `get_db_schema'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model/base.rb:572:in `block in set_dataset'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model/base.rb:719:in `check_non_connection_error'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model/base.rb:572:in `set_dataset'
/usr/local/lib/ruby/gems/2.3.0/gems/sequel-3.48.0/lib/sequel/model.rb:46:in `Model'
```

**Comment by Daniel-ltw** [comment]
database string should be: 

```
(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ENV['HOSTNAME'])(PORT=ENV['PORT']))(CONNECT_DATA=(SERVICE_NAME=ENV['SID'])))
```
