### ISSUE TITLE
Can not change(update) record of the '#each' dataset for mssql

### ISSUE THREAD

**Issue by gossion** [jeremyevans/sequel#1314]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
Hi,

The issue happens with `tiny_tds` adapter when I try to update(or delete) `each` record of the query result, it raises an issue saying that **TinyTds::Error: Attempt to initiate a new Adaptive Server operation with results pending (Sequel::DatabaseDisconnectError)**.

Not sure if it is a limitation, as I know `postgres` and `mysql` adapters do not have the same issue.

### Simplest Possible Self-Contained Example Showing the Bug
1. create a table on sql server:
```sql
CREATE TABLE [NAMES] (
    [ID] integer NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [GUID] varchar(255) NOT NULL
)
```
2. source code to reproduce the issue:
```ruby
require 'sequel'
require 'logger'

DB = Sequel.connect("tinytds://user:pass@localhost:1433/dbtest", :logger => Logger.new('/tmp/db.log'))

class NameModel < Sequel::Model(:names)
end

10.times { |i|  NameModel.create(guid: 'guid') }

results = NameModel.where(guid: 'guid')

results.each do |i|
  newguid = 'new-guid' #generate_new_guid(i)
  i.update(guid: newguid) ######ERROR on this line.
end
```

### Full Backtrace of Exception (if any)
```
/home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:142:in `execute': TinyTds::Error: Attempt to initiate a new Adaptive Server operation with results pending (Sequel::DatabaseDisconnectError)
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:142:in `block in log_connection_execute'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/logging.rb:48:in `log_connection_yield'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:142:in `log_connection_execute'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:300:in `begin_new_transaction'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:310:in `begin_transaction'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:205:in `_transaction'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:190:in `block in transaction'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/transactions.rb:156:in `transaction'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2188:in `checked_transaction'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1684:in `block in save'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2176:in `checked_save_failure'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1684:in `save'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1697:in `save_changes'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:2352:in `update_restricted'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/model/base.rb:1825:in `update'
        from t.rb:14:in `block in <main>'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:139:in `block in each'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:239:in `block (2 levels) in fetch_rows'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:239:in `each'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:239:in `block in fetch_rows'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:65:in `block in execute'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/database/connecting.rb:280:in `synchronize'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:970:in `execute'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/adapters/tinytds.rb:217:in `fetch_rows'
        from /home/guwe/.rvm/gems/ruby-2.3.3/gems/sequel-4.41.0/lib/sequel/dataset/actions.rb:139:in `each'
        from t.rb:13:in `<main>'
```

### SQL Log (if any)
```
# Logfile created on 2017-03-03 02:46:12 +0000 by logger.rb/56438
I, [2017-03-03T02:46:13.031941 #63229]  INFO -- : (0.000067s) SELECT CAST(SERVERPROPERTY('ProductVersion') AS varchar)
I, [2017-03-03T02:46:13.033232 #63229]  INFO -- : (0.000044s) SELECT TOP (1) object_id(N'NAMES') AS [V]
I, [2017-03-03T02:46:13.034329 #63229]  INFO -- : (0.000044s) SELECT [NAME] FROM [sys].[columns] WHERE (([OBJECT_ID] = 651149365) AND ([IS_IDENTITY] = 1))
I, [2017-03-03T02:46:13.035348 #63229]  INFO -- : (0.000047s) SELECT TOP (1) [INDID] FROM sysindexes WHERE (([ID] = 651149365) AND ([INDID] >= 1) AND ([INDID] <= 254) AND (([STATUS] & 2048) = 2048))
I, [2017-03-03T02:46:13.036626 #63229]  INFO -- : (0.000045s) SELECT [SC].[NAME] FROM sysindexkeys AS [SIK] INNER JOIN syscolumns AS [SC] ON (([SC].[ID] = [SIK].[ID]) AND ([SC].[COLID] = [SIK].[COLID])) WHERE (([SIK].[ID] = 651149365) AND ([SIK].[INDID] = 1)) ORDER BY [SC].[NAME]
I, [2017-03-03T02:46:13.037693 #63229]  INFO -- : (0.000051s) SELECT [COLUMN_NAME] AS [COLUMN], [DATA_TYPE] AS [DB_TYPE], [CHARACTER_MAXIMUM_LENGTH] AS [MAX_CHARS], [COLUMN_DEFAULT] AS [DEFAULT], [IS_NULLABLE] AS [ALLOW_NULL], [NUMERIC_PRECISION] AS [COLUMN_SIZE], [NUMERIC_SCALE] AS [SCALE] FROM [INFORMATION_SCHEMA].[TABLES] AS [T] INNER JOIN [INFORMATION_SCHEMA].[COLUMNS] AS [C] ON (([C].[TABLE_CATALOG] = [T].[TABLE_CATALOG]) AND ([C].[TABLE_SCHEMA] = [T].[TABLE_SCHEMA]) AND ([C].[TABLE_NAME] = [T].[TABLE_NAME])) WHERE ([C].[TABLE_NAME] = N'NAMES')
I, [2017-03-03T02:46:13.039923 #63229]  INFO -- : (0.000485s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.040213 #63229]  INFO -- : (0.000046s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.042397 #63229]  INFO -- : (0.000779s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.042969 #63229]  INFO -- : (0.000433s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.043168 #63229]  INFO -- : (0.000044s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.045069 #63229]  INFO -- : (0.000853s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.045614 #63229]  INFO -- : (0.000408s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.045828 #63229]  INFO -- : (0.000061s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.047887 #63229]  INFO -- : (0.001191s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.048790 #63229]  INFO -- : (0.000578s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.049182 #63229]  INFO -- : (0.000081s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.051550 #63229]  INFO -- : (0.001156s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.054080 #63229]  INFO -- : (0.002063s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.054881 #63229]  INFO -- : (0.000199s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.057167 #63229]  INFO -- : (0.001005s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.057978 #63229]  INFO -- : (0.000561s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.058333 #63229]  INFO -- : (0.000080s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.060085 #63229]  INFO -- : (0.000704s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.060831 #63229]  INFO -- : (0.000511s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.061200 #63229]  INFO -- : (0.000079s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.062969 #63229]  INFO -- : (0.000707s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.063827 #63229]  INFO -- : (0.000514s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.064286 #63229]  INFO -- : (0.000173s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.068197 #63229]  INFO -- : (0.000739s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.069154 #63229]  INFO -- : (0.000806s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.069510 #63229]  INFO -- : (0.000181s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.071772 #63229]  INFO -- : (0.001463s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.072706 #63229]  INFO -- : (0.000765s) BEGIN TRANSACTION
I, [2017-03-03T02:46:13.073098 #63229]  INFO -- : (0.000159s) INSERT INTO [NAMES] ([GUID]) OUTPUT [INSERTED].* VALUES (N'guid')
I, [2017-03-03T02:46:13.074197 #63229]  INFO -- : (0.000542s) COMMIT TRANSACTION
I, [2017-03-03T02:46:13.074529 #63229]  INFO -- : (0.000112s) SELECT * FROM [NAMES] WHERE ([GUID] = N'guid')
E, [2017-03-03T02:46:13.076503 #63229] ERROR -- : TinyTds::Error: Attempt to initiate a new Adaptive Server operation with results pending: BEGIN TRANSACTION
E, [2017-03-03T02:46:13.076628 #63229] ERROR -- : TinyTds::Error: Attempt to initiate a new Adaptive Server operation with results pending: IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
```

**Comment by gossion** [comment]
BTW, I can use "#all" instead of "#each" to avoid this issue.

**Comment by jeremyevans** [comment]
This is expected behavior, see the documentation: http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-each

The fact that it works on some adapters is just a side effect of how the underlying driver is programmed, and will only work in certain cases.  For example, it doesn't work if you are streaming queries.  In any case, relying on the behavior is unwise, which is why the documentation warns against it.
