### ISSUE TITLE
`Database#indexes` method fails for qualified tables

### ISSUE THREAD

**Issue by pabloh** [jeremyevans/sequel#1316]
When calling `Database#indexes` it does not work with qualified table names:

```ruby
DB.schema(:admin__users) # Works fine!
DB.indexes(:admin__users) # Raises an error
```

The error is: 
```
ERROR Mysql2::Error: Table 'mydb.admin__users' doesn't exist: SHOW INDEX FROM `admin__users`
Sequel::DatabaseError: Mysql2::Error: Table 'mydb.admin__users' doesn't exist
from /home/user/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
```

and backtrace:
```
Exception: Sequel::DatabaseError: Mysql2::Error: Table 'mydb.admin__users' doesn't exist
--
0: /home/user/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
1: /home/user/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
2: /home/user/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
3: /home/user/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
4: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/mysql2.rb:141:in `block in _execute'
5: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/database/logging.rb:48:in `log_connection_yield'
6: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/mysql2.rb:136:in `_execute'
7: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `block in execute'
8: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:280:in `block in synchronize'
9: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
10: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/database/connecting.rb:280:in `synchronize'
11: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/utils/mysql_mysql2.rb:36:in `execute'
12: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:1064:in `execute'
13: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/mysql2.rb:285:in `execute'
14: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/mysql2.rb:248:in `fetch_rows'
15: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/dataset/actions.rb:149:in `each'
16: /home/user/.rvm/gems/ruby-2.4.0/gems/sequel-4.44.0/lib/sequel/adapters/shared/mysql.rb:113:in `indexes'
```

**Comment by jeremyevans** [comment]
Looks like Database#indexes doesn't handle qualified tables on mysql.  This should be fairly easy to fix, I'll work on a patch tomorrow.

**Comment by pabloh** [comment]
That was fast... :open_mouth: 
Thank you!

**Comment by jeremyevans** [comment]
@pabloh Sequel releases around the first of every month.  The only exceptions are tiny releases, but those are only released to fix regressions from the previous version.  As this issue is not a regression from the previous version (the behavior hasn't changed between 4.43.0 and 4.44.0), I won't be doing a tiny release for it.  You can either have your project depend on the git master branch or a specific commit, or you can just monkey patch in the new code into your application until Sequel 4.45.0 is released.
