### ISSUE TITLE
ORA-00907: missing right parenthesis with select on Oracle

### ISSUE THREAD

**Issue by chuhn** [jeremyevans/sequel#1321]
### Complete Description of Issue

`select([:col1, :col2])` produces `SELECT ("COL1", "COL2") FROM …` which triggers ORA-00907 while 
`SELECT ("COL1") FROM …` surprisingly works.

`SELECT "COL1", "COL2" FROM …` works so the paretheses should not be generated here.

### Simplest Possible Self-Contained Example Showing the Bug

`db[:DUAL].select([:dummy, :dummy])`

### Full Backtrace of Exception (if any)
```
E, [2017-03-09T16:48:19.338645 #22953] ERROR -- : OCIError: ORA-00907: missing right parenthesis: SELECT ("DUMMY", "DUMMY") FROM "DUAL"
stmt.c:243:in oci8lib_230.so: OCIError: ORA-00907: missing right parenthesis (Sequel::DatabaseError)
        from /usr/lib/ruby/vendor_ruby/oci8/cursor.rb:126:in `exec'
        from /usr/lib/ruby/vendor_ruby/oci8/oci8.rb:276:in `exec_internal'
        from /usr/lib/ruby/vendor_ruby/oci8/oci8.rb:267:in `exec'
        from /usr/lib/ruby/vendor_ruby/sequel/adapters/oracle.rb:86:in `block (2 levels) in _execute'
        from /usr/lib/ruby/vendor_ruby/sequel/database/logging.rb:48:in `log_connection_yield'
        from /usr/lib/ruby/vendor_ruby/sequel/adapters/oracle.rb:86:in `block in _execute'
        from /usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `block in synchronize'
        from /usr/lib/ruby/vendor_ruby/sequel/connection_pool/threaded.rb:107:in `hold'
        from /usr/lib/ruby/vendor_ruby/sequel/database/connecting.rb:251:in `synchronize'
        from /usr/lib/ruby/vendor_ruby/sequel/adapters/oracle.rb:77:in `_execute'
        from /usr/lib/ruby/vendor_ruby/sequel/adapters/oracle.rb:67:in `execute'
        from /usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:970:in `execute'
        from /usr/lib/ruby/vendor_ruby/sequel/adapters/oracle.rb:362:in `fetch_rows'
        from /usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:141:in `each'
        from /usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:47:in `block in all'
        from /usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:910:in `_all'
        from /usr/lib/ruby/vendor_ruby/sequel/dataset/actions.rb:47:in `all'
        from select_test.rb:13:in `<main>'
```

BTW: I'm using ruby-sequel package from Debian Stretch (4.37.0-1), ruby-oci8 (2.2.3-1) and Oracle native client 12.1.0.2.0.

Kinf regads
	Christopher

**Comment by jeremyevans** [comment]
You should pass `select` separate arguments, not an array:

```ruby
db[:DUAL].select(:dummy, :dummy)
# or 
db[:DUAL].select(*[:dummy, :dummy])
```

This is true of most other dataset methods such as `group` and `order`.

The code you provided would probably fail on most databases Sequel supports.

**Comment by chuhn** [comment]
I see. What I want to do is to pass a dynamic list of columns to select:
```
columns = [:col_1, :col_2, …]
columns << :col_n if some_condition
db[:FOO].select(columns)
```
Is that achievable?
Of course I can `SELECT * FROM …` and filter afterward or `Sequel.lit(columns.join(', '))` etc. I but was hoping for a more elegant solution.

Cheers
	Christopher

**Comment by chuhn** [comment]
Sorry, didn't read your comment properly.
`db[:FOO].select(*columns)` is what I need.

Regards and many thanks
Christopher
