### ISSUE TITLE
undefined method `finish' for nil:NilClass during disconnect

### ISSUE THREAD

**Issue by baelter** [jeremyevans/sequel#1339]
When using Sequel.connect with a block to an endpoint that is not running Sequel throws this:

```
09:03:10 worker.1 | [ERROR] #<NoMethodError: undefined method `finish' for nil:NilClass>
09:03:10 worker.1 | undefined method `finish' for nil:NilClass
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/adapters/postgres.rb:315:in `disconnect_connection'
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/connection_pool.rb:104:in `disconnect_connection'
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/connection_pool/single.rb:20:in `disconnect'
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:226:in `disconnect'
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:80:in `ensure in connect'
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:81:in `connect'
09:03:10 worker.1 |   /Users/anders/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/sequel-4.45.0/lib/sequel/core.rb:116:in `connect'
```

**Comment by jeremyevans** [comment]
Thanks for the report.  I can confirm this is a bug. It is caused by the refactoring of the single connection pool a few versions ago.  I should have a fix pushed up shortly.
