### ISSUE TITLE
class_table_inheritance: exception and deprecation when subclass table doesnt exist

### ISSUE THREAD

**Issue by ayghor** [jeremyevans/sequel#1370]
i have something liek this

```
class Op < Sequel::Model
  plugin :class_table_inheritance, key: :type
end

class TaskOp < Op
end

class CreateTaskOp < TaskOp
end
```

i undersand from teh docs that if `create_task_ops` doesnt exist, it should try `task_ops`. that is teh case and it seems to be working correctly:

```
irb(main):002:0> TaskOp.dataset
=> #<Sequel::Postgres::Dataset: "SELECT \"ops\".\"id\", \"ops\".\"type\", \"ops\".\"mommy_id\", \"ops\".\"creator_id\", \"ops\".\"created_at\", \"task_ops\".\"task_id\" FROM \"ops\" INNER JOIN \"task_ops\" ON (\"task_ops\".\"id\" = \"ops\".\"id\")">
irb(main):003:0> CreateTaskOp.dataset
=> #<Sequel::Postgres::Dataset: "SELECT \"ops\".\"id\", \"ops\".\"type\", \"ops\".\"mommy_id\", \"ops\".\"creator_id\", \"ops\".\"created_at\", \"task_ops\".\"task_id\" FROM \"ops\" INNER JOIN \"task_ops\" ON (\"task_ops\".\"id\" = \"ops\".\"id\") WHERE (\"ops\".\"type\"
IN ('CreateTaskOp'))">
```

however i still get this:

```
SEQUEL DEPRECATION WARNING: Using a joined dataset as a Sequel::Model dataset is deprecated and will be removed in Sequel 5.  Use the class_table_inheritance plugin :alias option in Op.
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/base.rb:1010:in `convert_input_dataset'
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/base.rb:870:in `set_dataset'
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/plugins.rb:48:in `block in after_set_dataset'
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/plugins.rb:48:in `block in after_set_dataset'
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/model/plugins.rb:48:in `block in after_set_dataset'
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/plugins/single_table_inheritance.rb:174:in `inherited'
/home/rogi/.gem/ruby/2.4.0/gems/sequel-4.47.0/lib/sequel/plugins/class_table_inheritance.rb:274:in `inherited'
/home/rogi/sauce/wololo-tech/pikeman/models/op/create_task_op.rb:4:in `<top (required)>'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
I, [2017-06-02T17:19:22.281009 #26123]  INFO -- : (0.001144s) SELECT "indc"."relname" AS "name", "ind"."indisunique" AS "unique", "att"."attname" AS "column", "con"."condeferrable" AS "deferrable" FROM "pg_class" AS "tab" INNER JOIN "pg_index" AS "ind" ON ("ind"."indrelid" = "tab"."oid") INNER JOIN "pg_class" AS "indc" ON ("indc"."oid" = "ind"."indexrelid") INNER JOIN "pg_attribute" AS "att" ON (("att"."attrelid" = "tab"."oid") AND ("att"."attnum" = ANY("ind"."indkey"))) LEFT JOIN "pg_constraint" AS "con" ON ("con"."conname" = "indc"."relname") WHERE (("indc"."relkind" = 'i') AND ("ind"."indisprimary" IS FALSE) AND ("indexprs" IS NULL) AND ("indpred" IS NULL) AND ("indisvalid" IS TRUE) AND ("tab"."oid" = CAST(CAST('"ops"' AS regclass) AS oid)) AND ("indisready" IS TRUE) AND ("indcheckxmin" IS FALSE)) ORDER BY "indc"."relname", (CASE "att"."attnum" WHEN "ind"."indkey"[0] THEN 0 WHEN "ind"."indkey"[1] THEN 1 WHEN "ind"."indkey"[2] THEN 2 WHEN "ind"."indkey"[3] THEN 3 WHEN "ind"."indkey"[4] THEN 4 WHEN "ind"."indkey"[5] THEN 5 WHEN "ind"."indkey"[6] THEN 6 WHEN "ind"."indkey"[7] THEN 7 WHEN "ind"."indkey"[8] THEN 8 WHEN "ind"."indkey"[9] THEN 9 WHEN "ind"."indkey"[10] THEN 10 WHEN "ind"."indkey"[11] THEN 11
WHEN "ind"."indkey"[12] THEN 12 WHEN "ind"."indkey"[13] THEN 13 WHEN "ind"."indkey"[14] THEN 14 WHEN "ind"."indkey"[15] THEN 15 WHEN "ind"."indkey"[16] THEN 16 WHEN "ind"."indkey"[17] THEN 17 WHEN "ind"."indkey"[18] THEN 18 WHEN "ind"."indkey"[19] THEN 19 WHEN "ind"."indkey"[20] THEN 20 WHEN "ind"."indkey"[21] THEN 21 WHEN "ind"."indkey"[22] THEN 22 WHEN "ind"."indkey"[23] THEN 23 WHEN "ind"."indkey"[24]
THEN 24 WHEN "ind"."indkey"[25] THEN 25 WHEN "ind"."indkey"[26] THEN 26 WHEN "ind"."indkey"[27] THEN 27 WHEN "ind"."indkey"[28] THEN 28
WHEN "ind"."indkey"[29] THEN 29 WHEN "ind"."indkey"[30] THEN 30 WHEN "ind"."indkey"[31] THEN 31 ELSE 32 END)
E, [2017-06-02T17:19:22.281951 #26123] ERROR -- : PG::UndefinedTable: ERROR:  relation "create_task_ops" does not exist
LINE 1: SELECT * FROM "create_task_ops" LIMIT 1
                      ^: SELECT * FROM "create_task_ops" LIMIT 1
```

<3

**Comment by jeremyevans** [comment]
The deprecation warning is expected, as you need to use the :alias option to change class table inheritance to use a subquery, as it says in the deprecation warning. Sequel 5 will do this automatically, but using a subquery can result in behavior changes, hence the deprecation warning.

**Comment by ayghor** [comment]
is this expected too?

```
E, [2017-06-02T17:19:22.281951 #26123] ERROR -- : PG::UndefinedTable: ERROR:  relation "create_task_ops" does not exist
LINE 1: SELECT * FROM "create_task_ops" LIMIT 1
                      ^: SELECT * FROM "create_task_ops" LIMIT 1
```

**Comment by ayghor** [comment]
actually i thought that teh exception was from this and not teh deprecation

**Comment by jeremyevans** [comment]
That's a query to determine if the table exists, which it doesn't.  The exception is handled, but still logged if you are using a database logger.  The exception shouldn't be raised.  Assuming that's the behavior you are seeing, it is expected.
