### ISSUE TITLE
Dataset#[] doesn't seem work

### ISSUE THREAD

**Issue by gittmaekawa** [jeremyevans/sequel#1374]
I know I should ask at google group or IRC, but I can't use them in my working enviroment because of the company's security policy, so please excuse for asking this question.

### Complete Description of Issue
Dataset#[] doesn't seem work.
(http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html#method-i-5B-5D)

OS: ubuntu14.04
ruby: 2.3.4p301
sequel: 4.46.0
mysql2: 0.4.6

```
$ dpkg --list mysql*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
un  mysql                                                 <none>                          <none>                          (no description available)
ii  mysql-apt-config                                      0.8.6-1                         all                             Auto configuration for MySQL APT Repo.
un  mysql-client                                          <none>                          <none>                          (no description available)
un  mysql-client-5.0                                      <none>                          <none>                          (no description available)
un  mysql-client-5.1                                      <none>                          <none>                          (no description available)
un  mysql-client-5.5                                      <none>                          <none>                          (no description available)
un  mysql-client-5.6                                      <none>                          <none>                          (no description available)
un  mysql-client-core-5.0                                 <none>                          <none>                          (no description available)
un  mysql-client-core-5.1                                 <none>                          <none>                          (no description available)
un  mysql-client-core-5.5                                 <none>                          <none>                          (no description available)
un  mysql-client-core-5.6                                 <none>                          <none>                          (no description available)
un  mysql-commercial-client                               <none>                          <none>                          (no description available)
un  mysql-commercial-server                               <none>                          <none>                          (no description available)
ii  mysql-common                                          5.6.35-1ubuntu14.04             amd64                           MySQL Common
ii  mysql-community-client                                5.6.35-1ubuntu14.04             amd64                           MySQL Client
ii  mysql-community-server                                5.6.35-1ubuntu14.04             amd64                           MySQL Server
ii  mysql-server                                          5.6.35-1ubuntu14.04             amd64                           MySQL Server meta package depending on latest version
un  mysql-server-5.0                                      <none>                          <none>                          (no description available)
un  mysql-server-5.1                                      <none>                          <none>                          (no description available)
un  mysql-server-5.5                                      <none>                          <none>                          (no description available)
un  mysql-server-5.6                                      <none>                          <none>                          (no description available)
un  mysql-server-core-5.0                                 <none>                          <none>                          (no description available)
un  mysql-server-core-5.1                                 <none>                          <none>                          (no description available)
un  mysql-server-core-5.5                                 <none>                          <none>                          (no description available)
un  mysql-server-core-5.6                                 <none>                          <none>                          (no description available)
```

### Simplest Possible Self-Contained Example Showing the Bug
Suppose that a record in a table named "offices" at MySQL server.
```
$ mysql> select id, name from offices where id = 1083320;
| id      | name                     
+---------+------------+
| 1083320 | XXXXXXX   |
1 row in set (0.00 sec)
```

And Here is the IRB sesseion:
```
$ bundle exec irb
> require 'sequel'
> db = Sequel.connect('mysql2://root:@localhost/hoge')
> db[:offices][id: 1083320]
ArgumentError: argument out of range
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/mysql2.rb:256:in `local'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/mysql2.rb:256:in `each'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/mysql2.rb:256:in `block in fetch_rows'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/mysql2.rb:156:in `_execute'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `block in execute'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/database/connecting.rb:301:in `synchronize'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `execute'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/dataset/actions.rb:1073:in `execute'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/mysql2.rb:291:in `execute'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/adapters/mysql2.rb:254:in `fetch_rows'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/dataset/actions.rb:934:in `with_sql_each'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/dataset/actions.rb:942:in `with_sql_first'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/dataset/actions.rb:745:in `single_record!'
        from /XXXXXXXX/vendor/bundle/ruby/2.3.0/gems/sequel-4.46.0/lib/sequel/dataset/actions.rb:247:in `first'
... 2 levels...
        from /usr/bin/irb:11:in `<top (required)>'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `load'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:74:in `kernel_load'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli/exec.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli.rb:360:in `exec'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli.rb:20:in `dispatch'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/cli.rb:10:in `start'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/exe/bundle:35:in `block in <top (required)>'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from /var/lib/gems/2.3.0/gems/bundler-1.15.0/exe/bundle:27:in `<top (required)>'
        from /usr/local/bin/bundle:22:in `load'
        from /usr/local/bin/bundle:22:in `<main>'
```

Are there any possible mistakes I should take care of ?
Or Are there any problems which is already known related to this?

Thanks.

**Comment by jeremyevans** [comment]
This exception is raised inside the mysql2 driver, can you see if it works correctly if using the mysql2 driver directly?  Can you try using the mysql adapter instead of the mysql2 adapter and see if that fixes the problem? Can you provide a minimal, self contained, reproducible example?

**Comment by jeremyevans** [comment]
Actually, taking a more detailed look at the backtrace, I can see what the problem is.  You are selecting a datetime column with an invalid date/time value.  I don't think the mysql2 driver/adapter supports that.  You need to use the mysql adapter and set `db.convert_invalid_date_time = :string # or :nil`.  Alternatively, don't select the datetime column: `db[:offices].select(:id, :name)[id: 1083320]`

**Comment by gittmaekawa** [comment]
Thanks very much. I made sure your answer and that was right.
By the way, let me ask one more question to confirm "convert_invalid_date_time" method.
Is this method implemented for only Sequel::MySQL::Database?
I'm new to sequel and I might be wrong, but it seems that Sequel::MySQL2::Database doesn't have `#convert_invalid_date_time=`....
I just looked at these pages and tried to confirm in IRB session:
http://sequel.jeremyevans.net/rdoc-adapters/classes/Sequel/MySQL/Database.html
http://sequel.jeremyevans.net/rdoc-adapters/classes/Sequel/Mysql2/Database.html

```
$ bundle exec irb
> db = Sequel.connect('mysql://root:@localhost/hoge', encoding: 'utf8')
=> #<Sequel::Mysql2::Database: "mysql2://root:@localhost/hoge" {:encoding=>"utf8"}>
>  db.convert_invalid_date_time = nil
NoMethodError: undefined method `convert_invalid_date_time=' for #<Sequel::Mysql2::Database:0x00000001f04f78>
```

Is my guess right?

Thanks.

**Comment by jeremyevans** [comment]
Correct, it is only implemented in the mysql adapter, as that does it's own typecasting.  Sequel uses the mysql2 driver's typecasting, so if you want the mysql2 adapter to support this, you'll need to ask the mysql2 developers to add support for this to the driver.
