### ISSUE TITLE
Sequel::Model.freeze fails if model already frozen

### ISSUE THREAD

**Issue by mwpastore** [jeremyevans/sequel#1421]
### Complete Description of Issue

If a Sequel::Model subclass is frozen, calling `.freeze` on it raises an error. It's a small thing, but it would be nice if this were just a no-op. 

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
# frozen_string_literal: true

# Sequel extensions
Sequel.extension :pg_range_ops

# Sequel options
Sequel.default_timezone = :utc

DB = Sequel.connect ENV.delete('DATABASE_URL')

# Database options
DB.convert_infinite_timestamps = :nil

# Database extensions
DB.extension :connection_validator
DB.extension :date_arithmetic
DB.extension :pagination
DB.extension :pg_json
DB.extension :pg_range

# Pool options
DB.pool.connection_validation_timeout = -1

# Model plugins
Sequel::Model.plugin :auto_validations, :not_null=>:presence
Sequel::Model.plugin :tactical_eager_loading
Sequel::Model.plugin :whitelist_security
```

```ruby
# frozen_string_literal: true
class ProductGroup < Sequel::Model
end
```

```console
irb(main):004:0> ProductGroup.superclass
=> Sequel::Model
irb(main):005:0> ProductGroup.frozen?
=> false
irb(main):006:0> ProductGroup.freeze
=> ProductGroup
irb(main):007:0> ProductGroup.freeze
RuntimeError: can't modify frozen #<Class:ProductGroup>
```

### Full Backtrace of Exception (if any)

```
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:768:in `dataset_extend'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:353:in `dataset_module'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.0.0/lib/sequel/model/base.rb:448:in `freeze'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.0.0/lib/sequel/model/associations.rb:1855:in `freeze'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.0.0/lib/sequel/plugins/auto_validations.rb:137:in `freeze'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/sequel-5.0.0/lib/sequel/plugins/whitelist_security.rb:29:in `freeze'
from (irb):7
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli/console.rb:18:in `run'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:393:in `console'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:22:in `dispatch'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/cli.rb:13:in `start'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:30:in `block in <top (required)>'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
from /Users/mwp/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.15.4/exe/bundle:22:in `<top (required)>'
from /Users/mwp/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
from /Users/mwp/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
```

**Comment by jeremyevans** [comment]
This is definitely a bug, as calling freeze on a frozen model should be a no-op.  I'll work on a fix right away.
