### ISSUE TITLE
add_foreign_key not reversible without providing a name, but with a name it won't migrate up

### ISSUE THREAD

**Issue by bgentry** [jeremyevans/sequel#1422]
### Complete Description of Issue

I ran a reversible migration to add a new foreign key column to a table. The migration itself happens fine, but when attempting to reverse it, it appears that Sequel does not provide a constraint name automatically:

```
Sequel::DatabaseError: PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ALTER TABLE "plant_batches" DROP CONSTRAINT , DROP COLUMN "s...
```

If I explicitly provide a `:name` to the `add_foreign_key`, then the migration reverses correctly. However, it no longer migrates up:

```
Sequel::DatabaseError: PG::UndefinedColumn: ERROR:  column "source_package_id" does not exist
/Users/bgentry/my-app/db/migrate/20170920225314_migration_name.rb:3:in `block (2 levels) in <top (required)>'
```

### Simplest Possible Self-Contained Example Showing the Bug

Schema:

```sql
CREATE TABLE packages (
    id uuid DEFAULT uuid_generate_v4() NOT NULL
);
CREATE TABLE plant_batches (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
);
```

Migration file:

```ruby
Sequel.migration do
  change do
    alter_table :plant_batches do
      add_foreign_key :source_package_id, :packages, type: :uuid
    end
  end
end
```

The migration if I add `name: :plant_batches_source_package_id_fkey` to the end of the `add_foreign_key`:

```ruby
Sequel.migration do
  change do
    alter_table :plant_batches do
      add_foreign_key :source_package_id, :packages, type: :uuid, name: :plant_batches_source_package_id_fkey
    end
  end
end
```

### Full Backtrace of Exception (if any)

The relevant backtrace generated on rollback with no `name` provided:

```
Sequel::DatabaseError: PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: ALTER TABLE "plant_batches" DROP CONSTRAINT , DROP COLUMN "s...
                                                    ^
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `async_exec'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `block in execute_query'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `instrument'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `execute_query'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `block in execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:129:in `check_disconnect_errors'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:515:in `_execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block (2 levels) in execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:537:in `check_database_errors'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block in execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:54:in `execute_dui'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `block in apply_alter_table'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `each'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `apply_alter_table'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:449:in `apply_alter_table_generator'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:94:in `alter_table'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:185:in `block (2 levels) in reverse'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:182:in `each'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:182:in `block in reverse'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224:in `_transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:477:in `checked_transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/migrations.rb:9:in `migrate'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/railties/database.rake:175:in `block (2 levels) in <top (required)>'
```

And when attempting to migrate with a `name` provided:

```
Sequel::DatabaseError: PG::UndefinedColumn: ERROR:  column "source_package_id" does not exist
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `async_exec'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `block in execute_query'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `block in instrument'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/activesupport-5.1.3/lib/active_support/notifications.rb:166:in `instrument'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:166:in `execute_query'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `block in execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:129:in `check_disconnect_errors'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:153:in `execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:515:in `_execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block (2 levels) in execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:537:in `check_database_errors'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `block in execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:103:in `hold'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/adapters/postgres.rb:327:in `execute'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:54:in `execute_dui'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/query.rb:47:in `execute_ddl'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `block in apply_alter_table'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `each'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:436:in `apply_alter_table'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:449:in `apply_alter_table_generator'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:94:in `alter_table'
/Users/bgentry/myapp/db/migrate/20170920225314_my_migration.rb:3:in `block (2 levels) in <top (required)>'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224:in `_transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:477:in `checked_transaction'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/migrations.rb:9:in `migrate'
/Users/bgentry/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sequel-rails-0.9.17/lib/sequel_rails/railties/database.rake:164:in `block (2 levels) in <top (required)>'
```

### SQL Log (if any)

Didn't fetch this, but please lmk if this is insufficient info or if I can do anything more to help debug this.

**Comment by jeremyevans** [comment]
The `:name` option in `add_foreign_key` is not correct, since an array is not provided as the first argument.  You need to use the `:foreign_key_constraint_name` option if the first argument is a column name and not an array in order to specify the name of the constraint

I don't think reversing will work correctly with the `:foreign_key_constraint_name` option, that's a bug that should probably be fixed.  I'll work on that shortly.

**Comment by bgentry** [comment]
@jeremyevans are these docs also wrong then? http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-add_foreign_key

FWIW the `:name` option actually does make it reverse correctly.

**Comment by jeremyevans** [comment]
No, those docs are correct.  If you notice the first argument in both cases where the `:name` option is used is an array (indicating a composite foreign key, so constraint only, no column creation).

**Comment by bgentry** [comment]
Thanks for clarifying.

So that fact that a bare `add_foreign_key :source_package_id, :packages` is not reversible is also due to the one bug you mentioned?

**Comment by jeremyevans** [comment]
In general it should still be reversible if Sequel can determine the constraint name automatically by introspecting the database.  Not sure why Sequel isn't able to determine it in your case.
