### ISSUE TITLE
Sequel::Error: cannot determine database type to use for CHANGE COLUMN operation

### ISSUE THREAD

**Issue by LukasBeaton** [jeremyevans/sequel#1430]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue

I am trying to run a migration and I keep getting the following error.

Sequel::Error: cannot determine database type to use for CHANGE COLUMN operation

The migration looks like:

```
Sequel.migration do
  change do
    alter_table(:images) do
      add_column :ap_s3_key,  String
      add_column :ap_s3_bucket, String
      set_column_allow_null :url
      rename_column :url, :DEPRECATED_url, type: String, null: true

      add_index :ap_s3_key, null: false
      add_index :ap_s3_bucket, null: false
    end

    from(:images).each do |image|
      url = image[:DEPRECATED_url]
      next if url.nil?
      s3_bucket, s3_key = Anvil::Services::S3::URI.parse(url)

      from(:images).where(system_image_id: image[:system_image_id]).
        update(ap_s3_bucket: s3_bucket, ap_s3_key: s3_key)
    end
  end
end
```

**Comment by jeremyevans** [comment]
The problem here is that the database type (type of the column in the database) cannot be determined by Sequel, and MySQL requires that you know the existing type when changing the NULL/NOT NULL setting or renaming columns.  Usually Sequel can determine this information using `Database#schema`.  

I'm not sure if this error is happening in the `set_column_allow_null` method or in the `rename_column` method, though.  I can't recreate this on my end using this code:

```
DB.create_table!(:images) do
  String :url, null: false
end

DB.alter_table(:images) do
  set_column_allow_null :url
  rename_column :url, :DEPRECATED_url, type: String, null: true
end
```

This uses the following queries:

```
DROP TABLE IF EXISTS `images`
CREATE TABLE `images` (`url` varchar(255) NOT NULL)
DESCRIBE `images`
ALTER TABLE `images` CHANGE COLUMN `url` `url` varchar(255) NULL
DESCRIBE `images`
ALTER TABLE `images` CHANGE COLUMN `url` `DEPRECATED_url` varchar(255) NULL
```

Please reduce your problem to the most minimal example possible. Please include a full backtrace and a full SQL log (use the `-tE` option to `bin/sequel` if that is what you are using for the migrations).  There's a reason the issue template asks for this information.  Also include the output of `DB.schema(:images)`.

Additionally, this migration isn't reversible, so you should use `up` and not `change`.

**Comment by LukasBeaton** [comment]
it is happening on the add_column method, suprisingly


```
I, [2017-10-05T18:26:20.866621 #32672]  INFO -- : (0.000319s) SET NAMES utf8
I, [2017-10-05T18:26:20.866969 #32672]  INFO -- : (0.000251s) SET @@wait_timeout = 50000
I, [2017-10-05T18:26:20.867180 #32672]  INFO -- : (0.000180s) SET SQL_AUTO_IS_NULL=0
I, [2017-10-05T18:26:20.867799 #32672]  INFO -- : (0.000349s) SELECT NULL AS `nil` FROM `schema_migrations` LIMIT 1
I, [2017-10-05T18:26:20.868214 #32672]  INFO -- : (0.000269s) SELECT * FROM `schema_migrations` LIMIT 1
I, [2017-10-05T18:26:20.868948 #32672]  INFO -- : (0.000508s) SELECT `filename` FROM `schema_migrations` ORDER BY `filename`
I, [2017-10-05T18:26:20.873485 #32672]  INFO -- : Begin applying migration 201705111437_add_s3_bucket_and_s3_key_to_images.rb, direction: up
I, [2017-10-05T18:26:20.874612 #32672]  INFO -- : (0.000817s) DESCRIBE `images`
rake aborted!
Sequel::Error: cannot determine database type to use for CHANGE COLUMN operation
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/shared/mysql.rb:225:in `alter_table_change_column_sql'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:445:in `alter_table_op_sql'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:508:in `block in alter_table_sql_list'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:506:in `each'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:506:in `alter_table_sql_list'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/split_alter_table.rb:37:in `block in apply_alter_table'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `each'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `apply_alter_table'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:433:in `apply_alter_table_generator'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/database/schema_methods.rb:81:in `alter_table'
migrations/rest/201705111437_add_s3_bucket_and_s3_key_to_images.rb:5:in `block (2 levels) in <top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:106:in `apply'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:688:in `block (2 levels) in run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:476:in `checked_transaction'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:687:in `block in run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:684:in `each'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:684:in `run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/sequel-4.41.0/lib/sequel/extensions/migration.rb:401:in `run'
/vm/code/app/current/Rakefile:68:in `block (2 levels) in <top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/vm/code/app/current/Rakefile:39:in `block (2 levels) in <top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/airbrake-5.8.1/lib/airbrake/rake/task_ext.rb:19:in `execute'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/bin/rake:22:in `load'
/home/adparlor_deploy/.rbenv/versions/2.3.2/bin/rake:22:in `<top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `load'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:74:in `kernel_load'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/cli/exec.rb:27:in `run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/cli.rb:365:in `exec'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/home/adparlor_deploy/.rbenv/versions/2.3.2/lib/ruby/gems/2.3.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
/home/adparlor_deploy/.rbenv/versions/2.3.2/bin/bundle:22:in `load'
/home/adparlor_deploy/.rbenv/versions/2.3.2/bin/bundle:22:in `<main>'
Tasks: TOP => db:migrate_to
```

**Comment by jeremyevans** [comment]
Please test again using Sequel 5.1.0.  If it works, this can be closed.  If it fails, please produce a self-contained executable example showing the problem, similar to my earlier example.

**Comment by LukasBeaton** [comment]
Unfortunately there are other Gems that I can not change at this time that prevent me from upgrading. 

Not really sure what to do here...

**Comment by jeremyevans** [comment]
You don't need to upgrade the whole application.  If you want to see if this is still a problem, build a minimal reproducible example independent of your application that fails similarly on Sequel 4.41.0.  Then try the example on Sequel 5.1.0.  If it is still broken, submit it so I can test it.  If it is no longer broken, then close this, as only the latest version of Sequel is supported.

I can tell you this isn't failing in the `add_column` part, as `alter_table_change_column_sql` is not called for `add_column`.  You don't see directly which line is causing it, because the alter_table block runs to completion before Sequel processes the operations contained inside.  You could probably add:

```
def DB.alter_table_rename_column_sql(*a)
  p [:rename_column, a]
  super
end
def DB.alter_table_set_column_null_sql(*a)
  p [:set_column_null, a]
  super
end
```

and that will help determine what is failing.

**Comment by LukasBeaton** [comment]
Hey Jeremy,

Thanks for your timely feedback and tips on debugging. I was able to determine that the issue was with the following line of code 
```
set_column_allow_null :url
```
I refactored the migration use raw SQL for that logic and everything is working now.

```
    run <<-SQL
      ALTER TABLE images CHANGE COLUMN `url` `deprecated_url` VARCHAR(255);
    SQL
```

Thanks again for your help!

Best,
Lukas

**Comment by vbrazo** [comment]
I'm having the same issue. Check the backstrace out:

```
core:api vbrazo$ bundle exec rake db:migrate
rake aborted!
Sequel::Error: cannot determine database type to use for CHANGE COLUMN operation
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/shared/mysql.rb:211:in `alter_table_change_column_sql'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:437:in `alter_table_op_sql'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:500:in `block in alter_table_sql_list'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:498:in `each'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:498:in `alter_table_sql_list'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:37:in `block in apply_alter_table'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `each'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `apply_alter_table'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:424:in `apply_alter_table_generator'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:70:in `alter_table'
application/migrate/1523894525_make_name_optional_users_table.rb:3:in `block (2 levels) in <top (required)>'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:107:in `apply'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:688:in `block (2 levels) in run'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:472:in `checked_transaction'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:687:in `block in run'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:684:in `each'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:684:in `run'
/Users/vitoroliveira/rxvantage/api-ruby/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:398:in `run'
/Users/vitoroliveira/rxvantage/api-ruby/application/tasks/db.rake:36:in `block (2 levels) in <top (required)>
```

Here is my migration:
```
Sequel.migration do
  up do
    alter_table(:user) do
      set_column_allow_null :first_name
      set_column_allow_null :last_name
    end
  end

  down do
    alter_table(:user) do
      set_column_not_null :first_name
      set_column_not_null :last_name
    end
  end
end
```

**Comment by vbrazo** [comment]
I'm having the same issue. Check the backstrace out:

```
core:api vbrazo$ bundle exec rake db:migrate
rake aborted!
Sequel::Error: cannot determine database type to use for CHANGE COLUMN operation
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/shared/mysql.rb:211:in `alter_table_change_column_sql'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:437:in `alter_table_op_sql'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:500:in `block in alter_table_sql_list'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:498:in `each'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:498:in `alter_table_sql_list'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:37:in `block in apply_alter_table'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `each'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `apply_alter_table'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:424:in `apply_alter_table_generator'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:70:in `alter_table'
application/migrate/1523894525_make_name_optional_users_table.rb:3:in `block (2 levels) in <top (required)>'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:107:in `apply'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:688:in `block (2 levels) in run'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:472:in `checked_transaction'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:687:in `block in run'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:684:in `each'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:684:in `run'
/Users/vitoroliveira/rxvantage/api/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:398:in `run'
/Users/vitoroliveira/rxvantage/api/application/tasks/db.rake:36:in `block (2 levels) in <top (required)>
```

Here is my migration:
```
Sequel.migration do
  up do
    alter_table(:user) do
      set_column_allow_null :first_name
      set_column_allow_null :last_name
    end
  end

  down do
    alter_table(:user) do
      set_column_not_null :first_name
      set_column_not_null :last_name
    end
  end
end
```

**Comment by vbrazo** [comment]
I'm having the same issue. Check the backstrace out:

```
core:api vbrazo$ bundle exec rake db:migrate
rake aborted!
Sequel::Error: cannot determine database type to use for CHANGE COLUMN operation
/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/shared/mysql.rb:211:in `alter_table_change_column_sql'
/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:437:in `alter_table_op_sql'
/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:500:in `block in alter_table_sql_list'
/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:498:in `each'
/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:498:in `alter_table_sql_list'
/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:37:in `block in apply_alter_table'
/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `each'
/.bundle/gems/sequel-5.0.0/lib/sequel/adapters/utils/split_alter_table.rb:35:in `apply_alter_table'
/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:424:in `apply_alter_table_generator'
/.bundle/gems/sequel-5.0.0/lib/sequel/database/schema_methods.rb:70:in `alter_table'
application/migrate/1523894525_make_name_optional_users_table.rb:3:in `block (2 levels) in <top (required)>'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:107:in `apply'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:688:in `block (2 levels) in run'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:472:in `checked_transaction'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:687:in `block in run'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:684:in `each'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:684:in `run'
/.bundle/gems/sequel-5.0.0/lib/sequel/extensions/migration.rb:398:in `run'
/application/tasks/db.rake:36:in `block (2 levels) in <top (required)>
```

Here is my migration:
```
Sequel.migration do
  up do
    alter_table(:user) do
      set_column_allow_null :first_name
      set_column_allow_null :last_name
    end
  end

  down do
    alter_table(:user) do
      set_column_not_null :first_name
      set_column_not_null :last_name
    end
  end
end
```

**Comment by jeremyevans** [comment]
@vbrazo First, you'll need to put together a self contained example showing a problem (e.g. create_table first, then alter_table).  After that, test the example with the latest version of Sequel.  If it is still an issue, then create a new issue with the self contained example.
