### ISSUE TITLE
Schema qualified table names don't seem to work (pg)

### ISSUE THREAD

**Issue by u89012** [jeremyevans/sequel#1464]
### Complete Description of Issue
I understand Sequel can split schema names embedded in symbols (as mentioned in https://github.com/jeremyevans/sequel/blob/9cdb740c48b8fdb7407ca1961377d86ddbf523ae/spec/extensions/pg_loose_count_spec.rb) but I can't seem to get it to work. Is this a regression (because I remember this worked for me long time ago) or am I missing a require?

### Simplest Possible Self-Contained Example Showing the Bug
Assuming schema s and table t `DB["select * from s.t"].all` works as expected, however, `DB[:s__t].all` errors out (see below)

### Full Backtrace of Exception (if any)

```
head :001 > DB[:s__t].all
Sequel::DatabaseError: PG::UndefinedTable: ERROR:  relation "s__t" does not exist
LINE 1: SELECT * FROM "s__t"
                      ^

	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:133:in `block in execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:109:in `check_disconnect_errors'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:133:in `execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:449:in `_execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:273:in `block (2 levels) in execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:471:in `check_database_errors'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:273:in `block in execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/database/connecting.rb:264:in `synchronize'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:273:in `execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:1085:in `execute'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/adapters/postgres.rb:563:in `fetch_rows'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:151:in `each'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:51:in `block in all'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:1002:in `_all'
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/lib/sequel/dataset/actions.rb:51:in `all'
	from (irb):1
	from /Users/a/.rvm/gems/ruby-head/gems/sequel-5.3.0/bin/sequel:249:in `<top (required)>'
	from /Users/a/.rvm/gems/ruby-head/bin/sequel:23:in `load'
	from /Users/a/.rvm/gems/ruby-head/bin/sequel:23:in `<main>'
	from /Users/a/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
	from /Users/a/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
head :002 > DB["select * from s.t"].all
 => [] 

```

### SQL Log (if any)

###Versions
Ruby 2.5.0
Postgres 10.1
Sequel 5.3.0
Pg 0.21.0

**Comment by jeremyevans** [comment]
Symbol splitting was deprecated in 4.46.0 and disabled by default in Sequel 5.0.0.  This is mentioned in the release notes for both versions.  You can use `Sequel.split_symbols = true` to reenable it.
