### ISSUE TITLE
Exception in Database#copy_table (PostgreSQL) postponed to next query

### ISSUE THREAD

**Issue by oldgreen** [jeremyevans/sequel#1470]
Sequel 5.4.0., PostgreSQL 10.1, Ruby 2.3.4.

When a PostgreSQL ERROR (in this case ["duplicate category name"](https://github.com/postgres/postgres/blob/master/contrib/tablefunc/tablefunc.c#L152) by incorrectly using `crosstab` function from `tablefunc` extension) is triggered inside `Database#copy_table`, then the corresponding exception is raised on next db query.

```
irb(main):039:0> puts DB.from(Sequel.function(:crosstab, 'VALUES (1,2,3), (11,22,33)', 'VALUES (2), (22)').as(Sequel.lit('ct(a integer, b integer, c integer)'))).sql
SELECT * FROM crosstab('VALUES (1,2,3), (11,22,33)', 'VALUES (2), (22)') AS ct(a integer, b integer, c integer)
=> nil
irb(main):040:0> DB.copy_table(DB.from(Sequel.function(:crosstab, 'VALUES (1,2,3), (11,22,33)', 'VALUES (2), (22)').as(Sequel.lit('ct(a integer, b integer, c integer)'))), :format => :csv, :options => 'HEADER true')
=> "a,b,c\n1,3,\n11,,33\n"
irb(main):041:0> DB.copy_table(DB.from(Sequel.function(:crosstab, 'VALUES (1,2,3), (11,22,33)', 'VALUES (2), (2)').as(Sequel.lit('ct(a integer, b integer, c integer)'))), :format => :csv, :options => 'HEADER true')
=> "a,b,c\n"
irb(main):042:0> DB.get(1)
Sequel::DatabaseError: PG::DuplicateObject: ERROR:  duplicate category name

        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:145:in `async_exec'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:145:in `block in execute_query'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:145:in `execute_query'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:133:in `block in execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:109:in `check_disconnect_errors'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:133:in `execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:449:in `_execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:273:in `block (2 levels) in execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:471:in `check_database_errors'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:273:in `block in execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/database/connecting.rb:264:in `block in synchronize'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/database/connecting.rb:264:in `synchronize'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:273:in `execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/dataset/actions.rb:1085:in `execute'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/adapters/postgres.rb:563:in `fetch_rows'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/dataset/actions.rb:939:in `with_sql_each'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/dataset/actions.rb:947:in `with_sql_first'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/dataset/actions.rb:955:in `with_sql_single_value'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/dataset/placeholder_literalizer.rb:165:in `get'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/dataset/actions.rb:296:in `get'
        from /tmp/t/gems/gems/sequel-5.4.0/lib/sequel/database/query.rb:66:in `get'
```

**Comment by jeremyevans** [comment]
This does appear to be a bug.  Looking at the pg driver, get_copy_data doesn't raise an exception when it is called, you need to do always do additional checks after it returns `nil`.  `PG::Connection#copy_data` was added that does this cleanup, but it wasn't added until pg-0.17.0, and Sequel supports pg versions older than that.

I looked at the cleanup that `copy_data` does and it resulted in later failures when running the specs, so I'm going to do the safe thing and disconnect if there is an error detected, since that is what `copy_table` already does for other partial copy failures.
