### ISSUE TITLE
Finder plugin: Prepared statements should recover when table definition changes

### ISSUE THREAD

**Issue by csuhta** [jeremyevans/sequel#1481]
### Complete Description of Issue

- We have an application making heavy use of `prepared_finder` from the Finder plugin.
- We run multiple web processes that connect with Sequel
- We've found that when you change the definition of a table (even something that should be unobtrusive like adding a new column), all current Sequel connections using the finders will repeatedly raise exceptions with `Sequel::DatabaseError: PG::FeatureNotSupported: ERROR:  cached plan must not change result type`
- This makes it difficult to make minor table updates without bringing the entire application down for a maintenance window.

This is expected behavior from raw Postgres connections (you're supposed to `DEALLOCATE` your prepared statement if you change a table definition), but because Sequel is managing the connection, it can recover:

If Sequel is trying to execute a prepared statement  and it receives a `PG::FeatureNotSupported: ERROR:  cached plan must not change result type` exception, it should be able to retry by using the raw SQL or by deallocating and re-allocating the prepared statement

### Full Backtrace of Exception (if any)

```
vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:461:in `exec_prepared': PG::FeatureNotSupported: ERROR:  cached plan must not change result type
 (Sequel::DatabaseError)
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:461:in `_execute_prepared_statement'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:546:in `block (2 levels) in execute_prepared_statement'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/database/logging.rb:42:in `log_connection_yield'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:546:in `block in execute_prepared_statement'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:109:in `check_disconnect_errors'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:546:in `execute_prepared_statement'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:453:in `_execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:273:in `block (2 levels) in execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:477:in `check_database_errors'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:273:in `block in execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/database/connecting.rb:269:in `synchronize'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:273:in `execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:1085:in `execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/prepared_statements.rb:33:in `execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/prepared_statements.rb:33:in `execute'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/postgres.rb:569:in `fetch_rows'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:937:in `with_sql_each'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:947:in `with_sql_first'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:700:in `single_record!'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:688:in `single_record'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:207:in `first'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/prepared_statements.rb:189:in `run'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/prepared_statements.rb:59:in `call'
    from vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/plugins/finder.rb:206:in `block in def_prepare_method'
    from app/controllers/api/cards_controller.rb:59:in `show'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/abstract_controller/base.rb:186:in `process_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/rendering.rb:30:in `process_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
    from app/controllers/concerns/action_cacheable.rb:60:in `around'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:135:in `run_callbacks'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/rescue.rb:20:in `process_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `block in instrument'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/notifications.rb:166:in `instrument'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/abstract_controller/base.rb:124:in `process'
    from vendor/bundle/ruby/2.5.0/gems/actionview-5.1.5/lib/action_view/rendering.rb:30:in `process'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal.rb:189:in `dispatch'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_controller/metal.rb:253:in `dispatch'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:31:in `serve'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/journey/router.rb:50:in `block in serve'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/journey/router.rb:33:in `each'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/journey/router.rb:33:in `serve'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/routing/route_set.rb:844:in `call'
    from app/middleware/bad_request_handling.rb:23:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/conditional_get.rb:25:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/cookies.rb:613:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/callbacks.rb:97:in `run_callbacks'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
    from vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/rack/logger.rb:36:in `call_app'
    from vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/rack/logger.rb:24:in `block in call'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:69:in `block in tagged'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:26:in `tagged'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/tagged_logging.rb:69:in `tagged'
    from vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/rack/logger.rb:24:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
    from vendor/bundle/ruby/2.5.0/gems/activesupport-5.1.5/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/executor.rb:12:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/static.rb:125:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/deflater.rb:34:in `call'
    from vendor/bundle/ruby/2.5.0/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
    from vendor/bundle/ruby/2.5.0/gems/actionpack-5.1.5/lib/action_dispatch/middleware/ssl.rb:66:in `call'
    from vendor/bundle/ruby/2.5.0/gems/railties-5.1.5/lib/rails/engine.rb:522:in `call'
    from vendor/bundle/ruby/2.5.0/gems/puma-3.11.2/lib/puma/configuration.rb:225:in `call'
    from vendor/bundle/ruby/2.5.0/gems/puma-3.11.2/lib/puma/server.rb:624:in `handle_request'
    from vendor/bundle/ruby/2.5.0/gems/puma-3.11.2/lib/puma/server.rb:438:in `process_client'
    from vendor/bundle/ruby/2.5.0/gems/puma-3.11.2/lib/puma/server.rb:302:in `block in run'
    from vendor/bundle/ruby/2.5.0/gems/puma-3.11.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by jeremyevans** [comment]
In general if you are using prepared statements, you should avoid wildcard selections, or be willing to restart the process on schema changes if you do use wildcard selections.  One way to easily do this in Sequel for models is using the column_select plugin.  It's a much better approach to avoid the error than try to figure out ways to recover from it.

I wouldn't consider this a bug, but I agree there may be a way to improve the current situation. I'm not sure we could retry the prepared statement automatically in this case, as I'm not sure what side effects that could have, and if it would work inside a transaction.  I suppose it would be reasonable to attempt to deallocate the prepared statement if it recognizes that exception and then reraise the error.  Sequel would then reprepare the prepared statement on the connection the next time it was used.  Not sure if deallocate is allowed inside a failed transaction, so I would have to test that.

Another possible option is just treating that exception class as a database disconnect error, so Sequel would drop the connection from the pool and create a new connection as needed.  That may be better as you'll only get a single exception raised per connection, instead of one exception per affected prepared statement per connection.

**Comment by csuhta** [comment]
I will definitely try to see if the column_select plugin helps out as a tangent to this issue.

> I'm not sure we could retry the prepared statement automatically in this case, as I'm not sure what side effects that could have, and if it would work inside a transaction. I suppose it would be reasonable to attempt to deallocate the prepared statement if it recognizes that exception and then reraise the error. Sequel would then reprepare the prepared statement on the connection the next time it was used. Not sure if deallocate is allowed inside a failed transaction, so I would have to test that.

FWIW, in ActiveRecord, [the driver tries to deallocate the statement](https://github.com/rails/rails/pull/22170) (but that will fail inside a transaction and that failure is currently tolerated behavior)

> Another possible option is just treating that exception class as a database disconnect error, so Sequel would drop the connection from the pool and create a new connection as needed. That may be better as you'll only get a single exception raised per connection, instead of one exception per affected prepared statement per connection.

That would also be fine. Our application tends to use the "live database changes" workflow, ex:

1. Add new columns, copy or transform data
2. Deploy code that stops using the old columns
3. Remove the old data or columns

One error per connection would be much better than an unlimited number. Right now, even when the time between steps 1 and 2 is very small, we still can get hundreds failed queries.
