### ISSUE TITLE
Unable to Query a Database Using Symbolized Format, Only Using SQL

### ISSUE THREAD

**Issue by ACPPPF** [jeremyevans/sequel#1483]
When I Use TinyTds to connect to a SQL Server database, I can query using SQL, but not using a hash symbol.  For example:

#### SQL Expression
```
> DB['SELECT * FROM project'].single_record
 => {id: 1, key: 'foo', key2: 'bar'}
```
#### Calling using a symbol OR SQL with capitalized table name
```
> DB[:project].single_record
```
```
> DB['SELECT * FROM PROJECT'].single_record
```
Both of these calls throw the following exception:
```
Traceback (most recent call last):
       16: from /Users/ap047572/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
       15: from /Users/ap047572/.rvm/gems/ruby-2.5.0@global/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
       14: from /Users/ap047572/RubymineProjects/gc_automation/Rakefile:17:in `block in <top (required)>'
       13: from (irb):6
       12: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:688:in `single_record'
       11: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:700:in `single_record!'
       10: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:947:in `with_sql_first'
        9: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:939:in `with_sql_each'
        8: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:207:in `fetch_rows'
        7: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:1085:in `execute'
        6: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
        5: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        4: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        3: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:65:in `block in execute'
        2: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:210:in `block in fetch_rows'
        1: from /Users/ap047572/.rvm/gems/ruby-2.5.0@gc_automation/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:210:in `fields'
Sequel::DatabaseError (TinyTds::Error: Invalid object name 'PROJECT'.)
```
To make matters even stranger, if I run `DB.tables`, it gives me the whole list of tables with the associated database.  Is there any reason as to why this would be happening?  I really want to avoid using the SQL expressions if possible.

**Comment by jeremyevans** [comment]
It could be that your database uses case sensitive identifiers (not the default configuration for SQL Server), and that you have a table that uses lower case.  You can probably do the following:

```ruby
DB.extension :identifier_mangling
DB.identifier_input_method = DB.identifier_output_method = nil
```

Looks like SQL Server violates the SQL standard by being case sensitive even if the identifier is unquoted.

**Comment by ACPPPF** [comment]
Hey that worked!  Thank you so much!

**Comment by jeremyevans** [comment]
Closing as this appears to just be a configuration issue.
