### ISSUE TITLE
Add timestamp macro capability for Sequel migrations

### ISSUE THREAD

**Issue by genslein** [jeremyevans/sequel#1493]
### Complete Description of Issue
Can we add the timestamp macro for sequel migrations? It's a nice to have to stay in parity with community and promote adoption.

http://edgeguides.rubyonrails.org/active_record_migrations.html#migration-overview
### Simplest Possible Self-Contained Example Showing the Bug
```
Sequel.migration do
  change do
    create_table :customers do
      primary_key :id
      first_name :text
      last_name :text
      profile_metadata :json

      timestamps
    end
  end
end
```

### Full Backtrace of Exception (if any)
```
bundle exec rake db:migrate:up VERSION=20180318035358
rake aborted!
NameError: undefined local variable or method `timestamps' for #<Sequel::Postgres::CreateTableGenerator:0x00007fb07c059478>
Did you mean?  timeout
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/schema_generator.rb:230:in `method_missing'
/Users/genslein/Desktop/GitHubRepos/capricious_counterfeiter/db/migrate/20180318035358_create_customers.rb:15:in `block (3 levels) in <top (required)>'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/schema_generator.rb:40:in `instance_eval'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/schema_generator.rb:40:in `initialize'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:248:in `new'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:248:in `create_table_generator'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/schema_methods.rb:212:in `create_table'
/Users/genslein/Desktop/GitHubRepos/capricious_counterfeiter/db/migrate/20180318035358_create_customers.rb:6:in `block (2 levels) in <top (required)>'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `instance_eval'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:106:in `apply'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:705:in `block (2 levels) in run'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:224:in `_transaction'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:199:in `block in transaction'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/database/transactions.rb:165:in `transaction'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:477:in `checked_transaction'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:704:in `block in run'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `each'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:701:in `run'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-4.49.0/lib/sequel/extensions/migration.rb:404:in `run'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-rails-1.0.1/lib/sequel_rails/migrations.rb:11:in `migrate'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/sequel-rails-1.0.1/lib/sequel_rails/railties/database.rake:157:in `block (3 levels) in <top (required)>'
/Users/genslein/.rvm/gems/ruby-2.5.1@global/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `load'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:75:in `kernel_load'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli.rb:424:in `exec'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/cli.rb:18:in `start'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/exe/bundle:30:in `block in <top (required)>'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/Users/genslein/.rvm/gems/ruby-2.5.1/gems/bundler-1.16.1/exe/bundle:22:in `<top (required)>'
/Users/genslein/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `load'
/Users/genslein/.rvm/gems/ruby-2.5.1/bin/bundle:23:in `<main>'
/Users/genslein/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `eval'
/Users/genslein/.rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:migrate:up
(See full trace by running task with --trace)
```

**Comment by jeremyevans** [comment]
I dislike this approach.  It encourages adding both create and update timestamps to all tables without thinking about whether they are actually needed.  Sequel migrations are explicitly designed to be closer to SQL, hence the reason things like primary keys need to be explicitly added.

FWIW, the other code in your migration wouldn't work correctly on Sequel either, since you are swapping the database types and column name locations.

As explained in the contribution guidelines and in the issue template, feature requests should be made on the sequel-talk Google Group or IRC.  In the future, please open an issue on GitHub only if you are reporting a bug.
