### ISSUE TITLE
tactical eager loading breaks with an association block

### ISSUE THREAD

**Issue by bgentry** [jeremyevans/sequel#1494]
### Complete Description of Issue

I have the following model setup:

```rb
class Org < Sequel::Model
  one_to_many :users
end

class User < Sequel::Model
  plugin :tactical_eager_loading

  one_to_many :articles do |ds|
    ds.where(Sequel.qualify(:articles, :org_id) => org_id )
  end
  many_to_one :org
end

class Article
  many_to_one :org
  many_to_one :user
end

```

Loading a single User and checking its articles via `User.first.articles` works fine, and applies the correct filters to the dataset.

However, when I do the following:

```rb
User.all.map(&:articles)
```

I get this error:

```
NameError: undefined local variable or method `org_id' for User:Class
```

The reason for this is that when the association block is called, `self` is the `User` _class_ instead of the `User` _instance_ (as it normally is when the block is called).

It this supposed to work? The [docs](http://sequel.jeremyevans.net/rdoc-plugins/classes/Sequel/Plugins/TacticalEagerLoading.html) state:

> Note that if you are passing a callback to the association method via a block or :callback option, or using the :reload option to reload the association, eager loading will not be done.

That makes me think that eager loading is not supposed to be happening in this case. I'd certainly not expect eager loading to break otherwise functional associations like this.

Thanks! :pray:

### Simplest Possible Self-Contained Example Showing the Bug

Included above.

### Full Backtrace of Exception (if any)

<details>
```
/Users/bgentry/Code/myapp/app/models/user.rb:13:in `block in <class:User>'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:619:in `block in associated_eager_dataset'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:563:in `block in cached_fetch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:560:in `fetch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:560:in `cached_fetch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:616:in `associated_eager_dataset'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:628:in `eager_loading_dataset'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:721:in `block (2 levels) in placeholder_eager_loader'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/placeholder_literalizer.rb:83:in `loader'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/placeholder_literalizer.rb:120:in `loader'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:720:in `block in placeholder_eager_loader'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:563:in `block in cached_fetch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:560:in `fetch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:560:in `cached_fetch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:719:in `placeholder_eager_loader'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:309:in `eager_load_results'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:1845:in `eager_load_results'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:2158:in `block in def_one_to_many'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:3088:in `block in eager_load'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:3052:in `each'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:3052:in `eager_load'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/plugins/tactical_eager_loading.rb:99:in `load_associated_objects'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/sequel-5.6.0/lib/sequel/model/associations.rb:1919:in `block in def_association_method'
(pry):3:in `__pry__'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `eval'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:323:in `handle_line'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `catch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `catch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_instance.rb:241:in `eval'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:77:in `block in repl'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `loop'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:67:in `repl'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `block in start'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/input_lock.rb:61:in `__with_ownership'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/input_lock.rb:79:in `with_ownership'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:38:in `start'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/repl.rb:13:in `start'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/pry-0.11.3/lib/pry/pry_class.rb:192:in `start'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/commands/console/console_command.rb:62:in `start'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/commands/console/console_command.rb:17:in `start'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/commands/console/console_command.rb:97:in `perform'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/command/base.rb:63:in `perform'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/command.rb:44:in `invoke'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-5.1.5/lib/rails/commands.rb:16:in `<top (required)>'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/Users/bgentry/Code/myapp/bin/rails:9:in `<top (required)>'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `block in load'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:286:in `load'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/bgentry/.rbenv/versions/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
```
</details>

**Comment by jeremyevans** [comment]
I think there is a related bug here, but even with that bug fixed, it wouldn't make the given code work. Sequel doesn't know that the association block you used doesn't work for eager loading.  The default in Sequel is to assume that the block can be used for both regular loading and eager loading.  You should use the `:eager_block` option if you want to specify a different block for eager loading, and/or the `:eager_loader` option for a custom eager loading behavior.

I think the related bug is that tactical_eager_loading does not respect the `:allow_eager` option.  If `:allow_eager` option is set to `false`, tactical_eager_loading should not try to eager load.  I'll try to fix that bug today.  With that bug fixed, if you use the `:allow_eager=>false` association option, it will not try to eager load.

You can work around this problem temporarily by using a block when calling the association method: `User.all.map{|u| u.articles{|ds| ds}}`.

**Comment by bgentry** [comment]
Thanks @jeremyevans, it seems like what I actually want in this case is:

```rb
  one_to_many :articles, eager_block: (->(ds) { ds }) do |ds|
    ds.where(Sequel.qualify(:articles, :org_id) => org_id )
  end
```

This lets me filter the articles by `org_id` (i.e. a Citus sharding key) when that information is available, but lets the eager loader still work otherwise.
