### ISSUE TITLE
Problem with non-hash jsonb values and models

### ISSUE THREAD

**Issue by tycooon** [jeremyevans/sequel#1509]
### Complete Description of Issue
I am trying to write some plain json values like number or string into a jsonb column and it turns out that it only works if I am using `Dataset#insert`, but not `Model#create`.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
require "sequel"
require "pg"

DB = Sequel.connect("postgres://localhost/test_db")

DB.drop_table?(:test)

DB.create_table(:test) do
  column :data, "jsonb"
end

DB.extension :pg_json
Sequel.extension :pg_json_ops

model = Sequel::Model(:test)
model.create(data: 15) # doesn't work

DB[:test].insert(data: JSON.dump(15)) # works
```

### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
	38: from sequel_jsonb_problem.rb:16:in `<main>'
	37: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:254:in `create'
	36: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1439:in `save'
	35: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1845:in `checked_save_failure'
	34: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1439:in `block in save'
	33: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1857:in `checked_transaction'
	32: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/database/transactions.rb:145:in `transaction'
	31: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/database/connecting.rb:269:in `synchronize'
	30: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	29: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/database/transactions.rb:179:in `block in transaction'
	28: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/database/transactions.rb:204:in `_transaction'
	27: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1857:in `block in checked_transaction'
	26: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1439:in `block (2 levels) in save'
	25: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1710:in `_save'
	24: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1006:in `around_save'
	23: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1715:in `block in _save'
	22: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1006:in `around_create'
	21: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1718:in `block (2 levels) in _save'
	20: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1647:in `_insert'
	19: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/model/base.rb:1674:in `_insert_select_raw'
	18: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/shared/postgres.rb:1539:in `insert_select'
	17: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:944:in `with_sql_first'
	16: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:936:in `with_sql_each'
	15: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:592:in `fetch_rows'
	14: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/dataset/actions.rb:1082:in `execute'
	13: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `execute'
	12: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/database/connecting.rb:269:in `synchronize'
	11: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'
	10: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `block in execute'
	 9: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:500:in `check_database_errors'
	 8: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:296:in `block (2 levels) in execute'
	 7: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:478:in `_execute'
	 6: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:134:in `execute'
	 5: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:110:in `check_disconnect_errors'
	 4: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:134:in `block in execute'
	 3: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `execute_query'
	 2: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	 1: from /Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `block in execute_query'
/Users/tycooon/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.8.0/lib/sequel/adapters/postgres.rb:146:in `async_exec': PG::DatatypeMismatch: ERROR:  column "data" is of type jsonb but expression is of type integer (Sequel::DatabaseError)
LINE 1: INSERT INTO "test" ("data") VALUES (15) RETURNING *
                                            ^
HINT:  You will need to rewrite or cast the expression.
```

**Comment by tycooon** [comment]
Just found the answer in the docs, nevermind :)
