### ISSUE TITLE
ONLY_FULL_GROUP_BY SQL mode fails in MySQL spec

### ISSUE THREAD

**Issue by wjordan** [jeremyevans/sequel#1514]
### Complete Description of Issue

One MySQL adapter spec fails when running MySQL server version >= 5.7.5 configured with its default options, which includes [`ONLY_FULL_GROUP_BY`](https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html) SQL mode:

https://github.com/jeremyevans/sequel/blob/95438701d56ce45e15f094c09be77a5fbd5ed840/spec/adapters/mysql_spec.rb#L221-L229

I'm not sure if it's just this one spec that needs to be tweaked, or if this reflects broader work needed to support this stricter SQL mode in the implementation of `#distinct` for the MySQL adapter moving forward.

### Simplest Possible Self-Contained Example Showing the Bug

```
SEQUEL_MYSQL_URL=mysql2://localhost/sequel_test BUNDLE_GEMFILE=.travis.gemfile bundle exec ruby spec/adapters/mysql_spec.rb -n '/distinct/'
```

### Full Backtrace of Exception (if any)

```
Run options: --seed 13443

# Running:

E

Finished in 0.022885s, 43.6968 runs/s, 87.3937 assertions/s.

  1) Error:
Dataset#distinct#test_0001_#distinct with arguments should return results distinct on those arguments:
Sequel::DatabaseError: Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sequel_test.a.a' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    [GEM]/mysql2-0.5.0/lib/mysql2/client.rb:131:in `_query'
    [GEM]/mysql2-0.5.0/lib/mysql2/client.rb:131:in `block in query'
    [GEM]/mysql2-0.5.0/lib/mysql2/client.rb:130:in `handle_interrupt'
    [GEM]/mysql2-0.5.0/lib/mysql2/client.rb:130:in `query'
    [CODE]/sequel/lib/sequel/adapters/mysql2.rb:137:in `block in _execute'
    [CODE]/sequel/lib/sequel/database/logging.rb:38:in `log_connection_yield'
    [CODE]/sequel/lib/sequel/adapters/mysql2.rb:132:in `_execute'
    [CODE]/sequel/lib/sequel/adapters/utils/mysql_mysql2.rb:38:in `block in execute'
    [CODE]/sequel/lib/sequel/connection_pool/threaded.rb:91:in `hold'
    [CODE]/sequel/lib/sequel/database/connecting.rb:270:in `synchronize'
    [CODE]/sequel/lib/sequel/adapters/utils/mysql_mysql2.rb:38:in `execute'
    [CODE]/sequel/lib/sequel/dataset/actions.rb:1082:in `execute'
    [CODE]/sequel/lib/sequel/adapters/mysql2.rb:274:in `execute'
    [CODE]/sequel/lib/sequel/adapters/mysql2.rb:237:in `fetch_rows'
    [CODE]/sequel/lib/sequel/dataset/actions.rb:151:in `each'
    [CODE]/sequel/lib/sequel/dataset/actions.rb:438:in `map'
    [CODE]/sequel/lib/sequel/dataset/actions.rb:438:in `map'
    spec/adapters/mysql_spec.rb:233:in `block (2 levels) in <main>'

1 runs, 2 assertions, 0 failures, 1 errors, 0 skips
```

### SQL Log (if any)

```
2018-05-25T01:10:18.371251Z	  750 Connect	will@localhost on sequel_test using Socket
2018-05-25T01:10:18.371374Z	  750 Query	SET @@wait_timeout = 2147483
2018-05-25T01:10:18.371489Z	  750 Query	SET SQL_AUTO_IS_NULL=0
2018-05-25T01:10:18.376656Z	  750 Query	DROP TABLE IF EXISTS `a`
2018-05-25T01:10:18.376907Z	  750 Query	CREATE TABLE `a` (`a` integer, `b` integer)
2018-05-25T01:10:18.389669Z	  750 Query	INSERT INTO `a` VALUES (20, 10)
2018-05-25T01:10:18.390886Z	  750 Query	INSERT INTO `a` VALUES (30, 10)
2018-05-25T01:10:18.391897Z	  750 Query	SELECT version()
2018-05-25T01:10:18.392189Z	  750 Query	SELECT DISTINCT * FROM `a` ORDER BY `b`, `a`
2018-05-25T01:10:18.392593Z	  750 Query	SELECT DISTINCT * FROM `a` ORDER BY `b`, `a` DESC
2018-05-25T01:10:18.392934Z	  750 Query	SELECT * FROM `a` GROUP BY `b` ORDER BY `b`, `a`
2018-05-25T01:10:18.393177Z	  750 Query	DROP TABLE IF EXISTS `a`
2018-05-25T01:10:18.401148Z	  750 Quit	
```

**Comment by jeremyevans** [comment]
Odd.  I test on MySQL 8, which also has ONLY_FULL_GROUP_BY set by default, and I don't think the spec fails there.  I'll have to look at this in more detail tomorrow, maybe something is setting a non-default sql_mode.

For this issue, it would just be a spec guard to skip the spec on specific MySQL versions, since I don't think there is a way to emulate DISTINCT ON without it in all cases.  I don't think it makes sense to raise an exception in Sequel for this, because we don't know how the database is configured, and the database will raise anyway.  However, we should probably update the documentation to mention the issue and how to set the sql_mode to work around it.

**Comment by wjordan** [comment]
Great, thanks for looking into this!

To clarify, the default setting of [`sql_mode`](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode) changed in 5.7.5 to include `ONLY_FULL_GROUP_BY` which will show up in `@@sql_mode`, but the behavior of the empty-string `sql_mode` setting is the same. So I think the guard in 1d9ed74 doesn't need the version-check on the empty-string case:

https://github.com/jeremyevans/sequel/blob/1d9ed74b36963df307e344e3d0d4a7e40fccad67/spec/adapters/mysql_spec.rb#L223-L224

**Comment by jeremyevans** [comment]
Just to make sure I understand, if sql_mode is empty, then only_full_group_by should always be false?

**Comment by wjordan** [comment]
> Just to make sure I understand, if sql_mode is empty, then only_full_group_by should always be false?

Correct. Here's a console test confirming the spec passes when `sql_mode` is explicitly set to empty:

```
$ mysql -e 'select @@version'
+-----------+
| @@version |
+-----------+
| 8.0.11    |
+-----------+
$ mysql -e 'select @@sql_mode'
+-----------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+-----------------------------------------------------------------------------------------------------------------------+
$ SEQUEL_MYSQL_URL=mysql2://localhost/sequel_test?default_group=client BUNDLE_GEMFILE=.travis.gemfile bundle exec ruby spec/adapters/mysql_spec.rb -n '/distinct/'
Run options: -n /distinct/ --seed 36285

# Running:

E

Finished in 0.112230s, 8.9103 runs/s, 17.8205 assertions/s.

  1) Error:
Dataset#distinct#test_0001_#distinct with arguments should return results distinct on those arguments:
Sequel::DatabaseError: Mysql2::Error: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'sequel_test.a.a' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
    [GEM]/mysql2-0.5.1/lib/mysql2/client.rb:131:in `_query'
[...]
    spec/adapters/mysql_spec.rb:231:in `block (2 levels) in <main>'

1 runs, 2 assertions, 0 failures, 1 errors, 0 skips
$ mysql -e 'set global sql_mode=""'
$ mysql -e 'select @@sql_mode'
+------------+
| @@sql_mode |
+------------+
|            |
+------------+
$ SEQUEL_MYSQL_URL=mysql2://localhost/sequel_test?default_group=client BUNDLE_GEMFILE=.travis.gemfile bundle exec ruby spec/adapters/mysql_spec.rb -n '/distinct/'
Run options: -n /distinct/ --seed 4224

# Running:

.

Finished in 0.146640s, 6.8194 runs/s, 27.2777 assertions/s.

1 runs, 4 assertions, 0 failures, 0 errors, 0 skips
```

**Comment by jeremyevans** [comment]
Thanks for testing. I think that will simplify the guard logic significantly.  I'll push a patch later today to fix the spec.
