### ISSUE TITLE
Converting resultset to json return noMethodError

### ISSUE THREAD

**Issue by StanislavNaumov** [jeremyevans/sequel#1524]
Note: If you have a question about Sequel, would like help using
Sequel, want to request a feature, or do anything else other than
submit a bug report, please use the sequel-talk Google Group or IRC.

### Complete Description of Issue
I am trying to retrieve a dataset using dummy columns and then convert this resultset to JSON, using built in method.
I am using ruby 2.5.1, sequel 5.9.0

### Simplest Possible Self-Contained Example Showing the Bug
```
[38] pry(main)> select_array = [:name, :code, Sequel.as('2', :disabled), Sequel.as('1', :selected)]
[
    [0] :name,
    [1] :code,
    [2] #<Sequel::SQL::AliasedExpression @expression=>"2", @alias=>:disabled, @columns=>nil>,
    [3] #<Sequel::SQL::AliasedExpression @expression=>"1", @alias=>:selected, @columns=>nil>
]
[39] pry(main)> packages     = BoxberryPackage.select(*select_array).all
[
    [ 0] #<BoxberryPackage:0x00005654d1653c00> {
            :code => "800",
        :disabled => "2",
            :name => "Конверт А4 для документов",
        :selected => "1"
    },
    [ 1] #<BoxberryPackage:0x00005654d1653b10> {
            :code => "801",
        :disabled => "2",
            :name => "Короб L",
        :selected => "1"
    },
    [ 2] #<BoxberryPackage:0x00005654d1653a20> {
            :code => "797",
        :disabled => "2",
            :name => "Короб M",
        :selected => "1"
    },
    [ 3] #<BoxberryPackage:0x00005654d1653930> {
            :code => "798",
        :disabled => "2",
            :name => "Короб S",
        :selected => "1"
    },
    [ 4] #<BoxberryPackage:0x00005654d16537f0> {
            :code => "802",
        :disabled => "2",
            :name => "Короб XL",
        :selected => "1"
    },
    [ 5] #<BoxberryPackage:0x00005654d16536d8> {
            :code => "799",
        :disabled => "2",
            :name => "Короб ХS",
        :selected => "1"
    },
    [ 6] #<BoxberryPackage:0x00005654d16535c0> {
            :code => "793",
        :disabled => "2",
            :name => "Пакет с клапаном L",
        :selected => "1"
    },
    [ 7] #<BoxberryPackage:0x00005654d16534d0> {
            :code => "794",
        :disabled => "2",
            :name => "Пакет с клапаном M",
        :selected => "1"
    },
    [ 8] #<BoxberryPackage:0x00005654d16533b8> {
            :code => "795",
        :disabled => "2",
            :name => "Пакет с клапаном S",
        :selected => "1"
    },
    [ 9] #<BoxberryPackage:0x00005654d16532a0> {
            :code => "978",
        :disabled => "2",
            :name => "Пакет с клапаном XL",
        :selected => "1"
    },
    [10] #<BoxberryPackage:0x00005654d1653188> {
            :code => "796",
        :disabled => "2",
            :name => "Пакет с клапаном XS",
        :selected => "1"
    }
]
[40] pry(main)> packages.to_json
NoMethodError: undefined method `disabled' for #<BoxberryPackage:0x00005654d1653c00>
from /home/killer/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.9.0/lib/sequel/plugins/json_serializer.rb:319:in `block in to_json'
```
### Full Backtrace of Exception (if any)

NoMethodError: undefined method `disabled' for #<BoxberryPackage:0x00005654d1653c00>
from /home/killer/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/sequel-5.9.0/lib/sequel/plugins/json_serializer.rb:319:in `block in to_json'

**Comment by jeremyevans** [comment]
You have to add `disabled` and `selected` methods to `BoxberryPackage` use the json_serializer plugin in this case (the json_serializer plugin calls methods for each of the keys in the hash).  Alternatively, since you aren't actually using the json_serializer specific options, you can do: `packages.map(&:values).to_json`.
