### ISSUE TITLE
Can't connect to both mysql and pg within same app

### ISSUE THREAD

**Issue by kubenstein** [jeremyevans/sequel#1531]
Im building an app on Heroku which connects to two databases, one contains events and the second calculated current state. Because I can't provision two Postgres db on Heroku, second db is MySql installed as an addon. Unfortunately I get an error when I attempt to connect to pg, after I already connected to mysql. Worth mentioning is if I use pg gem directly I am able to connect.  

Here are steps:
```ruby
require 'sequel'

mysql_connection_url = ENV['CLEARDB_DATABASE_URL']
# => "mysql://xxx:yyy@eu-cdbr-west-02.cleardb.net/heroku_59d04a7d8fc807d?reconnect=true"

pg_connection_url = ENV['DATABASE_URL']
# => "postgres://zzz:aaa@ec2-79-125-117-53.eu-west-1.compute.amazonaws.com:5432/ddpofjmvo21mm2"

Sequel.connect(mysql_connection_url) 
#=> #<Sequel::MySQL::Database: "mysql://xxx:yyy@eu-cdbr-west-02.cleardb.net/heroku_59d04a7d8fc807d?reconnect=true">

Sequel.connect(pg_connection_url)
Sequel::AdapterNotFound: LoadError: LoadError
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/adapters/postgres.rb:9:in `<top (required)>'
        from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:104:in `load_adapter'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:32:in `adapter_class'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:52:in `connect'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/core.rb:116:in `connect'
        from (irb):5
        from /app/bin/irb:15:in `<main>'
```

I also noticed that if I try to connect to pg twice (without even connecting to mysql first) I get additional warning:

```ruby
require 'sequel'
pg_connection_url = ENV['DATABASE_URL']
Sequel.connect(pg_connection_url)
Sequel::AdapterNotFound: LoadError: LoadError
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/adapters/postgres.rb:9:in `<top (required)>'
        from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:104:in `load_adapter'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:32:in `adapter_class'

        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:52:in `connect'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/core.rb:116:in `connect'
        from (irb):3
        from /app/bin/irb:15:in `<main>'


Sequel.connect(pg_connection_url)
/app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/adapters/postgres.rb:13: warning: already initialized con
stant Sequel::Postgres::USES_PG
/app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/adapters/postgres.rb:13: warning: previous definition of
USES_PG was here
Sequel::AdapterNotFound: LoadError: LoadError
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/adapters/postgres.rb:9:in `<top (required)>'
        from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:104:in `load_adapter'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:32:in `adapter_class'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/database/connecting.rb:52:in `connect'
        from /app/vendor/bundle/ruby/2.3.0/gems/sequel-4.45.0/lib/sequel/core.rb:116:in `connect'
        from (irb):4
        from /app/bin/irb:15:in `<main>'
```

and my gemfile:
```ruby
gem 'sequel'
group :production do
  gem 'mysql'
  gem 'pg', '~>1.0.0'
end
```
I am not sure what can be the reason but it looks like there is some conflict, maybe cross monkey patching, during loading.

Thank you for great work for so many years!

**Comment by jeremyevans** [comment]
Please upgrade to the latest version of Sequel and try again.  The version you are using is over a year old.  

Alternatively, you could try downgrading the `pg` version to `0.20.0`, since that is the latest version available when Sequel 4.45.0 was released.
