### ISSUE TITLE
Adapter TinyTDS is struggling with table alias in model dataset

### ISSUE THREAD

**Issue by QuAcK3RjAcK** [jeremyevans/sequel#1574]
### Complete Description of Issue
I have a small model with a default dataset. But the query i build is not working but in IRB without the model the query works fine. What im doing wrong here?

### Simplest Possible Self-Contained Example Showing the Bug
*Model*
```
class Ipod < Sequel::Model(DB_MDM[:dbo__device])

  dataset_module do
    def only_obf_ipods
      DB_MDM[:dbo__device___d].left_join(:dbo__device_property___dp, dp__device_id: :d__device_id).where(dp__name: 'DEVICE_NAME').where(Sequel.like(:dp__value, '%iPod%')).where(Sequel.like(:d__last_username, '%mdmvkst____%'))#.order(:d__last_username)
    end
  end
  set_dataset(self.only_obf_ipods)

  FILTER_VALUES = {
    all: 'alle',
    active: 'aktive',
    inactive: 'inaktive'
  }.freeze

  def self.active
    self.select{|ipod| ipod.last_activity >= (Date.today - 7).to_time}
  end

  def self.inactive
    self.select{|ipod| ipod.last_activity < (Date.today - 7).to_time}
  end
end
```
*IRB*
```
$ irb
irb(main):001:0> require_relative 'management'
=> true
irb(main):002:0> Ipod.first
Sequel::DatabaseError: TinyTds::Error: The column 'DEVICE_ID' was specified multiple times for 'D'.
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:210:in `fields'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:210:in `block in fetch_rows'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:65:in `block in execute'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:1083:in `execute'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:207:in `fetch_rows'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:151:in `each'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:85:in `columns!'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:75:in `columns'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:242:in `columns'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:809:in `block (2 levels) in get_db_schema'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:725:in `block in check_non_connection_error'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/transactions.rb:151:in `block in transaction'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/transactions.rb:145:in `transaction'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:725:in `check_non_connection_error'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:809:in `block in get_db_schema'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:842:in `call'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:842:in `get_db_schema'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:644:in `set_dataset'
        from C:/Projekte/localware/management/models/ipod.rb:8:in `<class:Ipod>'
        from C:/Projekte/localware/management/models/ipod.rb:1:in `<top (required)>'
        from C:/Ruby226/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from C:/Ruby226/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from C:/Projekte/localware/management/management.rb:222:in `const_missing'
        from (irb):2
        from C:/Ruby226/bin/irb:11:in `<main>'

irb(main):003:0> DB_MDM[:dbo__device___d].left_join(:dbo__device_property___dp, dp__device_id: :d__device_id).where(dp__name: 'DEVICE_NAME').where(Sequel.like(:dp__value, '%iPod%')).where(Sequel.like(:d__last_username, '%mdmvkst____%')).first
=>{:device_id=>1890, :serial_number=>"xxxxx", :imei=>nil, :wifi_mac_addr=>"F0:76:6F:2A:73:13", :bluetooth_mac_addr=>"F0:76:6F:1F:AA:EF", :activesync_id=>"I00DT9QJO57S7E6QJSPJMKOFGS", :strong_id=>"PNMJ6Q5H", :last_inventory_time=>2018-11-21 10:24:28 +0100, :first_connection_date=>2018-08-15 09:28:42 +0200, :last_auth_date=>2018-11-21 10:24:31 +0100, :last_username=>"xxxxx", :last_profile_invent_time=>2018-11-21 10:24:32 +0100, :os_family=>"iOS", :last_user_id=>492, :whitelist_compliant=>1, :blacklist_compliant=>1, :device_properties_timestamp=>2018-08-15 09:29:48 +0200, :all_whitelist_compliant=>1, :last_activity=>2018-11-21 10:24:31 +0100, :managed=>1, :cookie_token=>nil, :cookie_exp=>nil, :profile_status=>3, :mam_device_id=>nil, :device_token=>nil, :device_type=>nil, :type_inst=>nil, :app_lock=>0, :app_wipe=>0, :mdm_known=>1, :mam_registered=>0, :mam_ready=>0, :dep_account_id=>1, :dep_profile_id=>1, :property_id=>111202, :name=>"DEVICE_NAME", :value=>"iPod touch", :is_internal=>0}
```

In addition my workaround at the moment was to convert that query in SQL and it is working, but now i need more dynamic in that query so i want to use query again.
```
      # sql = %{
      #         SELECT * FROM [DBO].[DEVICE] AS [D]
      #         LEFT JOIN [DBO].[DEVICE_PROPERTY] AS [DP]
      #                   ON ([DP].[DEVICE_ID] = [D].[DEVICE_ID])
      #         WHERE (([DP].[NAME] = N'DEVICE_NAME') AND
      #               (([DP].[VALUE] COLLATE Latin1_General_CS_AS) LIKE (N'%iPod%' COLLATE Latin1_General_CS_AS) ESCAPE N'\\') AND
      #               (([D].[LAST_USERNAME] COLLATE Latin1_General_CS_AS) LIKE (N'%mdmvkst____@%' COLLATE Latin1_General_CS_AS) ESCAPE N'\\'))))
      #         ORDER BY [D].[LAST_USERNAME]
      #       }.gsub(/\s+/, " ").strip
      # DB_MDM[sql]
```

After that maybe there is a second issue. When i add `.order(:d__last_username)` to my query above. 
I get following error:
```
irb(main):002:0> Ipod.first
Sequel::DatabaseError: TinyTds::Error: The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:210:in `fields'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:210:in `block in fetch_rows'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:65:in `block in execute'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:1083:in `execute'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/adapters/tinytds.rb:207:in `fetch_rows'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:151:in `each'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:85:in `columns!'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/dataset/actions.rb:75:in `columns'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:242:in `columns'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:809:in `block (2 levels) in get_db_schema'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:725:in `block in check_non_connection_error'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/transactions.rb:151:in `block in transaction'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/connecting.rb:253:in `synchronize'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/database/transactions.rb:145:in `transaction'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:725:in `check_non_connection_error'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:809:in `block in get_db_schema'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:842:in `call'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:842:in `get_db_schema'
        from C:/Ruby226/lib/ruby/gems/2.2.0/gems/sequel-5.10.0/lib/sequel/model/base.rb:644:in `set_dataset'
        from C:/Projekte/localware/management/models/ipod.rb:8:in `<class:Ipod>'
        from C:/Projekte/localware/management/models/ipod.rb:1:in `<top (required)>'
        from C:/Ruby226/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from C:/Ruby226/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:122:in `require'
        from C:/Projekte/localware/management/management.rb:222:in `const_missing'
        from (irb):2
        from C:/Ruby226/bin/irb:11:in `<main>'
```
Again as plain query with my Database connection it is working fine.

Cause of the working queries with plain DB connection i suspect the error is a combination of the model dataset and the adapter logic.

Thx in advance!

**Comment by jeremyevans** [comment]
The error message is probably caused because you are selecting multiple columns with the same alias.  You should use `select` on the dataset you are passing to `set_dataset` and give each column in the dataset a unique alias.

The ORDER BY issue is because you can't use ORDER BY in subqueries, and Sequel wraps your dataset in a subquery because model datasets are designed to only select from a single table or subquery.

Note that this is a request for help using Sequel, so in the future you should make requests like this on the sequel-talk Google Group or the IRC channel.  Please only use GitHub Issues to report bugs in Sequel itself, as specified by the contribution guidelines.
