### ISSUE TITLE
Limited SQLite schema modification circumvention breaks foreign keys

### ISSUE THREAD

**Issue by misson20000** [jeremyevans/sequel#1582]
### Complete Description of Issue
As described in this comment, SQLite has limited support for `ALTER TABLE`. https://github.com/jeremyevans/sequel/blob/622cab53f40be9b9066a7f618152f30b2d71ddc8/lib/sequel/adapters/shared/sqlite.rb#L202-L206
As a way to circumvent this, Sequel renames the old table, makes a new table with the new schema, copies all the data, and deletes the old table. However, this breaks any foreign keys pointing to the old table.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
require "sequel"
require "logger"

DB = Sequel.sqlite :logger => Logger.new($stderr)

DB.create_table(:table_a) do
  primary_key :id
  column :text, String
end

DB.create_table(:table_b) do
  primary_key :id
  foreign_key :a_id, :table_a
end

DB.alter_table(:table_a) do
  drop_column :text
end

DB[:table_b].insert(:a_id => 0)
```
### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
	13: from schema_mod_fk_bug.rb:20:in `<main>'
	12: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:399:in `insert'
	11: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:1099:in `execute_insert'
	10: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:146:in `execute_insert'
	 9: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
	 8: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	 7: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	 6: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:189:in `block in _execute'
	 5: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
	 4: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:189:in `block (2 levels) in _execute'
	 3: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:137:in `execute'
	 2: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `prepare'
	 1: from /home/misson20000/.rvm/gems/ruby-2.5.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `new'
/home/misson20000/.rvm/gems/ruby-2.5.1/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:91:in `initialize': SQLite3::SQLException: no such table: main.table_a_backup0 (Sequel::DatabaseError)
```
### SQL Log (if any)
```
I, [2018-12-14T23:21:46.024059 #11316]  INFO -- : (0.000077s) PRAGMA foreign_keys = 1
I, [2018-12-14T23:21:46.024115 #11316]  INFO -- : (0.000013s) PRAGMA case_sensitive_like = 1
I, [2018-12-14T23:21:46.024320 #11316]  INFO -- : (0.000105s) CREATE TABLE `table_a` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `text` varchar(255))
I, [2018-12-14T23:21:46.024453 #11316]  INFO -- : (0.000056s) CREATE TABLE `table_b` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `a_id` integer REFERENCES `table_a`)
I, [2018-12-14T23:21:46.024523 #11316]  INFO -- : (0.000015s) PRAGMA foreign_keys = 0
I, [2018-12-14T23:21:46.024614 #11316]  INFO -- : (0.000042s) SELECT sqlite_version()
I, [2018-12-14T23:21:46.024676 #11316]  INFO -- : (0.000030s) BEGIN
I, [2018-12-14T23:21:46.024781 #11316]  INFO -- : (0.000046s) PRAGMA table_info('table_a')
I, [2018-12-14T23:21:46.024848 #11316]  INFO -- : (0.000024s) PRAGMA foreign_key_list('table_a')
I, [2018-12-14T23:21:46.024904 #11316]  INFO -- : (0.000018s) PRAGMA index_list('table_a')
I, [2018-12-14T23:21:46.024976 #11316]  INFO -- : (0.000011s) SAVEPOINT autopoint_1
E, [2018-12-14T23:21:46.025061 #11316] ERROR -- : SQLite3::SQLException: no such table: table_a_backup0: SELECT NULL AS 'nil' FROM `table_a_backup0` LIMIT 1
I, [2018-12-14T23:21:46.025151 #11316]  INFO -- : (0.000024s) ROLLBACK TO SAVEPOINT autopoint_1
I, [2018-12-14T23:21:46.025232 #11316]  INFO -- : (0.000022s) PRAGMA index_list('table_a')
I, [2018-12-14T23:21:46.025464 #11316]  INFO -- : (0.000204s) ALTER TABLE `table_a` RENAME TO `table_a_backup0`
I, [2018-12-14T23:21:46.025540 #11316]  INFO -- : (0.000047s) CREATE TABLE `table_a`(`id` integer DEFAULT (NULL) NOT NULL PRIMARY KEY AUTOINCREMENT)
I, [2018-12-14T23:21:46.025590 #11316]  INFO -- : (0.000023s) INSERT INTO `table_a`(`id`) SELECT `id` FROM `table_a_backup0`
I, [2018-12-14T23:21:46.025652 #11316]  INFO -- : (0.000037s) DROP TABLE `table_a_backup0`
I, [2018-12-14T23:21:46.025693 #11316]  INFO -- : (0.000016s) COMMIT
I, [2018-12-14T23:21:46.025740 #11316]  INFO -- : (0.000010s) PRAGMA foreign_keys = 1
E, [2018-12-14T23:21:46.025826 #11316] ERROR -- : SQLite3::SQLException: no such table: main.table_a_backup0: INSERT INTO `table_b` (`a_id`) VALUES (0)
```

**Comment by jeremyevans** [comment]
I'm guessing you are using an old version of SQLite, as I remember SQLite fixing this issue. When I try with SQLite 3.25.1, I get expected behavior:

```
DB[:table_b].insert(:a_id => 0)
# ERROR -- : SQLite3::ConstraintException: FOREIGN KEY constraint failed: INSERT INTO `table_b` (`a_id`) VALUES (0)
DB[:table_a].insert(:id => 0)
# INSERT INTO `table_a` (`id`) VALUES (0)
# => 0
DB[:table_b].insert(:a_id => 0)
# INSERT INTO `table_b` (`a_id`) VALUES (0)
# => 1
DB.sqlite_version
# => 32501
```

If you are still getting the broken behavior and you are on a recent version of SQLite, please post back with details, including the SQLite version you are using.

**Comment by misson20000** [comment]
I'm still getting the broken behavior on the latest version of SQLite (3.26.0, if I'm not mistaken).
```
Sequel.sqlite.sqlite_version
# => 32600
```

**Comment by jeremyevans** [comment]
Weird, I wonder if this is a regression or behavior change in the newest SQLite version.  Can you try this diff?

```diff
diff --git a/lib/sequel/adapters/shared/sqlite.rb b/lib/sequel/adapters/shared/sqlite.rb
index 22aa502ad..b60a675bd 100644
--- a/lib/sequel/adapters/shared/sqlite.rb
+++ b/lib/sequel/adapters/shared/sqlite.rb
@@ -177,7 +177,7 @@ module Sequel
       # needed for drop column.
       def apply_alter_table(table, ops)
         fks = fetch("PRAGMA foreign_keys")
-        run "PRAGMA foreign_keys = 0" if fks
+        run "PRAGMA foreign_keys = 0" if fks && sqlite_version < 32600
         transaction do 
           if ops.length > 1 && ops.all?{|op| op[:op] == :add_constraint || op[:op] == :set_column_null}
             null_ops, ops = ops.partition{|op| op[:op] == :set_column_null}
@@ -196,7 +196,7 @@ module Sequel
         end
         remove_cached_schema(table)
       ensure
-        run "PRAGMA foreign_keys = 1" if fks
+        run "PRAGMA foreign_keys = 1" if fks && sqlite_version < 32600
       end
 
       # SQLite supports limited table modification.  You can add a column
```

**Comment by jeremyevans** [comment]
From reading the SQLite 3.26.0 release notes (https://sqlite.org/releaselog/3_26_0.html), can you try this and let me know whether it fixes the problem:

```diff
diff --git a/lib/sequel/adapters/shared/sqlite.rb b/lib/sequel/adapters/shared/sqlite.rb
index 22aa502ad..d6cda5581 100644
--- a/lib/sequel/adapters/shared/sqlite.rb
+++ b/lib/sequel/adapters/shared/sqlite.rb
@@ -177,7 +177,10 @@ module Sequel
       # needed for drop column.
       def apply_alter_table(table, ops)
         fks = fetch("PRAGMA foreign_keys")
-        run "PRAGMA foreign_keys = 0" if fks
+        if fks
+          run "PRAGMA foreign_keys = 0"
+          run "PRAGMA legacy_alter_table = 1" if sqlite_version >= 32600
+        end
         transaction do 
           if ops.length > 1 && ops.all?{|op| op[:op] == :add_constraint || op[:op] == :set_column_null}
             null_ops, ops = ops.partition{|op| op[:op] == :set_column_null}
@@ -196,7 +199,10 @@ module Sequel
         end
         remove_cached_schema(table)
       ensure
-        run "PRAGMA foreign_keys = 1" if fks
+        if fks
+          run "PRAGMA foreign_keys = 1"
+          run "PRAGMA legacy_alter_table = 0" if sqlite_version >= 32600
+        end
       end
 
       # SQLite supports limited table modification.  You can add a column
```

**Comment by misson20000** [comment]
That seems to fix the problem.

**Comment by glaszig** [comment]
without trying i think the more compatible way would be to

- first create the altered table `altered_table_a`
- copy the data `INSERT INTO altered_table_a ... SELECT table_a ...`
- drop `table_a` -- which sqlite will not prevent because `foreign_key=off`
- rename `altered_table_a` to `table_a`

this way the foreign keys won't get renamed, just end up orphaned, until the new table takes the place of the old one. am i wrong?

**Comment by jeremyevans** [comment]
@glaszig I'm not sure.  You may want to try your approach and run the tests with:

* SQLite <3.6.19
* SQLite >=3.6.19, <3.25.0
* SQLite >=3.25.0

If you can get the tests passing on those three versions, then such a change can be considered.
