### ISSUE TITLE
gem fails to install macOS 10.14

### ISSUE THREAD

**Issue by sslupsky** [jeremyevans/sequel#1584]
### Complete Description of Issue

Attempted to migrate a grafana sqlite3 database to postgres.

Encountered the following error:

/usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:152:in `async_exec': PG::NumericValueOutOfRange: ERROR:  integer out of range (Sequel::DatabaseError)

There error was encountered while copying the "annotation" table:

Begin copying records for table: annotation

### Full Backtrace of Exception (if any)

	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:140:in `execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:496:in `_execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:314:in `block (2 levels) in execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:518:in `check_database_errors'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:314:in `block in execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:314:in `execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:1083:in `execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/postgres.rb:610:in `fetch_rows'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:1186:in `returning_fetch_rows'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:397:in `insert'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/shared/postgres.rb:1485:in `insert'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/shared/postgres.rb:1494:in `insert'
	from /usr/local/share/gems/gems/sequel-5.15.0/bin/sequel:221:in `block (4 levels) in <top (required)>'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:151:in `block in each'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:330:in `block (2 levels) in fetch_rows'
	from /usr/local/share/gems/gems/sqlite3-1.3.13/lib/sqlite3/resultset.rb:138:in `each'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:321:in `block in fetch_rows'
	from /usr/local/share/gems/gems/sqlite3-1.3.13/lib/sqlite3/database.rb:267:in `query'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:187:in `block (2 levels) in _execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:187:in `block in _execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:126:in `execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:1083:in `execute'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/adapters/sqlite.rb:315:in `fetch_rows'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:151:in `each'
	from /usr/local/share/gems/gems/sequel-5.15.0/bin/sequel:216:in `block (3 levels) in <top (required)>'
	from /usr/local/share/gems/gems/sequel-5.15.0/bin/sequel:211:in `each'
	from /usr/local/share/gems/gems/sequel-5.15.0/bin/sequel:211:in `block (2 levels) in <top (required)>'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/transactions.rb:204:in `_transaction'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/transactions.rb:179:in `block in transaction'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/transactions.rb:145:in `transaction'
	from /usr/local/share/gems/gems/sequel-5.15.0/bin/sequel:210:in `block in <top (required)>'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/transactions.rb:204:in `_transaction'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/transactions.rb:179:in `block in transaction'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `synchronize'
	from /usr/local/share/gems/gems/sequel-5.15.0/lib/sequel/database/transactions.rb:145:in `transaction'
	from /usr/local/share/gems/gems/sequel-5.15.0/bin/sequel:209:in `<top (required)>'
	from /usr/local/bin/sequel:23:in `load'
	from /usr/local/bin/sequel:23:in `<main>'

**Comment by sslupsky** [comment]
I looked at the data in the annotation table.  All the integer values appear to be ok.  There is one field where I noticed there were some null values (no value).  I went though and sell them all to 0 and tried again.  I observed the same error.

There is a field "epoch" that contains the epoch time in milliseconds which requires a 48 or 64 bit integer.  Could this be causing the problem?

**Comment by jeremyevans** [comment]
It looks like your table in SQLite uses the integer type to store values that a 32-bit integer will not hold (the postgres integer type uses 32-bit integers).  You could try making a copy of the SQLite database, then altering the SQLite table to use the bigint type for that column, then doing the conversion to postgres.  You could also try using the integer64 extension, though if you are using the the `bin/sequel` command line that is a little tricky.  Something like `echo 'DB.extension :integer64' > ext.rb; sequel -r ./ext -C ...` may work for that.
