### ISSUE TITLE
Alias not working with eager_graph

### ISSUE THREAD

**Issue by tycooon** [jeremyevans/sequel#1588]
### Complete Description of Issue
For some reason the example from the docs (`Album.eager_graph(Sequel[:artist].as(:a)).all`) is not working.

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
require "sequel"

DB = Sequel.sqlite

DB.create_table :artists do
  primary_key :id
end

DB.create_table :albums do
  primary_key :id
  foreign_key :artist_id, :artists
end

class Album < Sequel::Model
  many_to_one :artist
end

class Artist < Sequel::Model
end

p Album.eager_graph(Sequel[:artist].as(:a)).all
```

### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
	8: from /tmp/sequel.rb:21:in `<main>'
	7: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/plugins.rb:33:in `eager_graph'
	6: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3009:in `eager_graph'
	5: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3049:in `eager_graph_with_options'
	4: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3155:in `eager_graph_associations'
	3: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3155:in `each'
	2: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3158:in `block in eager_graph_associations'
	1: from /Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3276:in `eager_graph_check_association'
/Users/tycooon/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sequel-5.16.0/lib/sequel/model/associations.rb:3267:in `check_association': Invalid association #<Sequel::SQL::Identifier:0x00007fdf089fb368> for Album (Sequel::UndefinedAssociation)
```

**Comment by jeremyevans** [comment]
Thanks for the report. As the error message indicates, the issue is not with the use of an alias, but with the usage of an SQL::Identifier.  `Sequel.as(:artist, :a)` should work instead of `Sequel[:artist].as(:a)`.  However, as the docs have already shown usage with an identifier, and Sequel users are more likely to use `Sequel[].as` for constructing aliases (compared to `Sequel.as`), this should probably be supported.  I'll add support for this shortly.
