### ISSUE TITLE
Infinite loop when when saving parent in nested attributes save

### ISSUE THREAD

**Issue by shanecav84** [jeremyevans/sequel#1589]
### Complete Description of Issue

This occured after updating from `5.13.0` to `5.16.0`. When creating a model with nested attributes, saving the parent from within a child association causes an infinite loop.

### Simplest Possible Self-Contained Example Showing the Bug
<details>
<summary>Click to expand</summary>

```ruby
require 'sequel'

Sequel::Model.plugin :nested_attributes
Sequel::Model.plugin :touch

DB = Sequel.sqlite # memory database, requires sqlite3

DB.create_table :parents do
  primary_key :id
  DateTime :updated_at
end

DB.create_table :children do
  primary_key :id
  Bignum :parent_id
  String :name
end

class Parent < Sequel::Model
  one_to_many :children
  nested_attributes :children
  plugin :touch
end

class Child < Sequel::Model
  many_to_one :parent

  def before_save
    super
    parent.touch
  end
end

Parent.create(children_attributes: [{ name: 'Foo' }])
```

</details>

### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
  16: 'sequel-5.16.0/lib/sequel/model/base.rb:1745:in `_save'
  15: 'sequel-5.16.0/lib/sequel/model/base.rb:1015:in `around_save'
  14: 'sequel-5.16.0/lib/sequel/model/base.rb:1763:in `block in _save'
  13: 'sequel-5.16.0/lib/sequel/model/base.rb:1015:in `around_update'
  12: 'sequel-5.16.0/lib/sequel/model/base.rb:1781:in `block (2 levels) in _save'
  11: 'sequel-5.16.0/lib/sequel/model/base.rb:1840:in `_update_columns'
  10: 'sequel-5.16.0/lib/sequel/model/base.rb:1846:in `_update'
   9: 'sequel-5.16.0/lib/sequel/model/base.rb:1859:in `_update_without_checking'
   8: 'sequel-5.16.0/lib/sequel/model/base.rb:1854:in `_update_dataset'
   7: 'sequel-5.16.0/lib/sequel/model/base.rb:1572:in `this'
   6: 'sequel-5.16.0/lib/sequel/dataset/query.rb:1046:in `where'
   5: 'sequel-5.16.0/lib/sequel/dataset/query.rb:1255:in `add_filter'
   4: 'sequel-5.16.0/lib/sequel/dataset/query.rb:1284:in `filter_expr'
   3: 'sequel-5.16.0/lib/sequel/sql.rb:1074:in `from_value_pairs'
   2: 'sequel-5.16.0/lib/sequel/sql.rb:1074:in `map'
   1: 'sequel-5.16.0/lib/sequel/sql.rb:1074:in `each'
```

**Comment by shanecav84** [comment]
Thanks very much for the analysis and work-around. I suspected the source of the problem and the change that introduced it but didn't know if it was intended behavior. Thanks for clearing that up. Also wast't aware of the `touch` configuration. Thanks again.
