### ISSUE TITLE
Teradata NOT operator "<>" does not exist in EQUALITY_OPERATORS and throws "Invalid operator <>"

### ISSUE THREAD

**Issue by centuryfall** [jeremyevans/sequel#1599]
### Complete Description of Issue
I am attempting to use Teradata as a data source for my project. For creating a statement where I want to filter out an item, I need to use the Teradata NOT "<>" operator as Teradata does not use "!=" operator for negative comparisons. 

For example, a Teradata statement to exclude Column_1 values that equal 'Foo' would be
`SELECT * FROM DB.table Where Column_1 <> 'Foo'`

In the actual SQL gem, there is no assignment for this "<>" operator.

Under sql.rb file,
```
# Operators that check for equality
EQUALITY_OPERATORS = [:'=', :'!='].freeze
```

is all that exists. It does not include "<>" operator as the negation operator.

As well, the Operator Inversions does not include "<>" operator.
```
OPERTATOR_INVERSIONS = {:AND => :OR, :OR => :AND, :< => :>=, :> => :<=,
        :<= => :>, :>= => :<, :'=' => :'!=' , :'!=' => :'=', :LIKE => :'NOT LIKE',
        :'NOT LIKE' => :LIKE, :~ => :'!~', :'!~' => :~, :IN => :'NOT IN',
        :'NOT IN' => :IN, :IS => :'IS NOT', :'IS NOT' => :IS, :'~*' => :'!~*',
        :'!~*' => :'~*', :NOT => :NOOP, :NOOP => :NOT, :ILIKE => :'NOT ILIKE',
        :'NOT ILIKE'=>:ILIKE}.freeze

```

### Simplest Possible Self-Contained Example Showing the Bug
I cannot provide examples to production code, but assume the following Sequel statements where the issue occurs

Assume a connection to Teradata.
```
$connection = DatabaseConnection::connect_to_teradata
#Teradata connection established

DB[:teradata].exclude(column_1: 'foo')

DB[:teradata].where(column_1: 'foo', column_2: 'baz').invert
```
These will produce the error
`Invalid operator <>`

### Full Backtrace of Exception (if any)
I removed the user trace and project name but this is the backtrace from RubyMine.
```
[0] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/sql.rb:238:in `initialize'"
[1] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/sql.rb:1115:in `invert'"
[2] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/sql.rb:1113:in `block in invert'"
[3] = "org/jruby/RubyArray.java:2487:in `map'"
[4] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/sql.rb:1113:in `invert'"
[5] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/dataset/query.rb:1256:in `add_filter'"
[6] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/dataset/query.rb:181:in `exclude'"
[7] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/sequel-5.12.0/lib/sequel/model/plugins.rb:33:in `exclude'"
[8] = "C:/Users/testuser/RubymineProjects/project/spec/test_spec.rb:66:in `<eval>'"
[9] = "org/jruby/RubyKernel.java:995:in `eval'"
[10] = "org/jruby/RubyMethod.java:127:in `call'"
[11] = "C:/jruby-9.1.17.0/lib/ruby/stdlib/delegate.rb:85:in `method_missing'"
[12] = "org/jruby/RubyArray.java:1735:in `each'"
[13] = "org/jruby/RubyKernel.java:1138:in `catch'"
[14] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/ruby-debug-base-0.10.6-java/lib/ruby-debug-base.rb:53:in `at_line'"
[15] = "C:/Users/testuser/RubymineProjects/project/spec/test_spec.rb:66:in `block in (root)'"
[16] = "org/jruby/RubyBasicObject.java:1728:in `instance_exec'"
[17] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'"
[18] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `block in with_around_and_singleton_context_hooks'"
[19] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `block in with_around_example_hooks'"
[20] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `block in run'"
[21] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:602:in `run_around_example_hooks_for'"
[22] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/hooks.rb:464:in `run'"
[23] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:457:in `with_around_example_hooks'"
[24] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:500:in `with_around_and_singleton_context_hooks'"
[25] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:251:in `run'"
[26] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:629:in `block in run_examples'"
[27] = "org/jruby/RubyArray.java:2487:in `map'"
[28] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:625:in `run_examples'"
[29] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/example_group.rb:591:in `run'"
[30] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block in run_specs'"
[31] = "org/jruby/RubyArray.java:2487:in `map'"
[32] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:116:in `block in run_specs'"
[33] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/configuration.rb:1989:in `with_suite_hooks'"
[34] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:111:in `block in run_specs'"
[35] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/reporter.rb:74:in `report'"
[36] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:110:in `run_specs'"
[37] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:87:in `run'"
[38] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:71:in `run'"
[39] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/lib/rspec/core/runner.rb:45:in `invoke'"
[40] = "C:/jruby-9.1.17.0/lib/ruby/gems/shared/gems/rspec-core-3.8.0/exe/rspec:4:in `<main>'"
[41] = "org/jruby/RubyKernel.java:974:in `load'"
[42] = "C:/jruby-9.1.17.0/bin/rspec:1:in `<main>'"
[43] = "org/jruby/debug/RubyDebugger.java:209:in `debug_load'"
[44] = "C:/jruby-9.1.17.0/bin/rspec:23:in `(root)'"
[45] = "org/jruby/RubyKernel.java:974:in `load'"
```

### SQL Log (if any)
N/A

**Comment by jeremyevans** [comment]
The correct way to handle this is to not modify those constants, but to use the `:'!='` operator at the ruby level and the `<>` operator at the SQL level.  You can do that by literalizing the `!=` operator as `<>` by overriding `Dataset#complex_expression_sql_append`.  Maybe something like this (untested):

```ruby
def complex_expression_sql_append(sql, op, args)
  op = :'<>' if op == :'!='
  super
end
```

**Comment by centuryfall** [comment]
Would this affect anything if we were to later use a second database connection that would use the ‘!=‘ operator instead? As in, supporting two variants of the same negation operator?

**Comment by jeremyevans** [comment]
No, it would only affect Database instances that use the Teradata adapter (assuming this change was made to the adapter).  You could actually limit this change to a specific Database instance (`def DB.complex_expression_sql_append`)

**Comment by centuryfall** [comment]
Ok I can attempt that and see if it solves the issue.

**Comment by jeremyevans** [comment]
I'm going to close this now.  If you find that it doesn't work for you, please post on the sequel-talk Google Group and we can continue the discussion there.
