### ISSUE TITLE
nested_attributes not compatible with ActiveController::Parameters from fields_for in rails

### ISSUE THREAD

**Issue by jonjonw** [jeremyevans/sequel#1600]
### Complete Description of Issue
The nested_attributes plugin is not playing nicely with fields_for in rails. Specifically, when the response is wrapped in ActiveController::Parameters, it seems the {"0" => {"k" => "v"},...} hash to represent arrays causes issues. I suspect the issue is somewhere around here: https://github.com/jeremyevans/sequel/blob/1ba6f44800f8df876be5bfc64c84d2c4db22f22b/lib/sequel/plugins/nested_attributes.rb#L208

The example below is based on the parameters that would be produced by
```ruby
form_with(model: car, local: true) do |form|
  form.fields_for :wheels, include_id: false do |w| %>
    w.text_field :name
  end
  form.submit
end
```

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'action_controller'
require 'sequel'
require 'logger'

DB = Sequel.sqlite
DB.loggers = [Logger.new(STDOUT)]

DB.create_table? :cars do
  primary_key :id
end
DB.create_table? :wheels do
  primary_key :id
  foreign_key :car_id, :cars
  String :name
end

class Car < Sequel::Model
  one_to_many :wheels
  plugin :association_dependencies, wheels: :destroy # destroy documents when batch is destroyed
  plugin :nested_attributes
  nested_attributes :wheels, destroy: true
end
class Wheel < Sequel::Model
  many_to_one :car
end

puts "database is set..."

raw_params = {
  "wheels_attributes" => {
    "0" => { "name" => "w0" },
    "1" => { "name" => "w1" }
  }
}
params = ActionController::Parameters.new(raw_params)

# This parses ok
car = Car.new(raw_params)

# But it fails if using an ActionController::Parameters object
begin
  car = Car.new(params)
rescue
  puts "BOOM!!"
end

DB.drop_table :wheels, :cars
```

### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
	18: from example.rb:42:in `<main>'
	17: from example.rb:42:in `new'
	16: from gems/sequel-5.17.0/lib/sequel/model/base.rb:1071:in `initialize'
	15: from gems/sequel-5.17.0/lib/sequel/model/base.rb:1940:in `initialize_set'
	14: from gems/sequel-5.17.0/lib/sequel/model/base.rb:1489:in `set'
	13: from gems/sequel-5.17.0/lib/sequel/model/base.rb:1984:in `set_restricted'
	12: from gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:337:in `each_pair'
	11: from gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:337:in `each_pair'
	10: from gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:338:in `block in each_pair'
	 9: from gems/sequel-5.17.0/lib/sequel/model/base.rb:1987:in `block in set_restricted'
	 8: from gems/sequel-5.17.0/lib/sequel/plugins/nested_attributes.rb:134:in `block (2 levels) in def_nested_attribute_method'
	 7: from gems/sequel-5.17.0/lib/sequel/plugins/nested_attributes.rb:150:in `set_nested_attributes'
	 6: from gems/sequel-5.17.0/lib/sequel/plugins/nested_attributes.rb:213:in `nested_attributes_list_setter'
	 5: from gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:337:in `each_pair'
	 4: from gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:337:in `each_pair'
	 3: from gems/actionpack-5.2.2/lib/action_controller/metal/strong_parameters.rb:338:in `block in each_pair'
	 2: from gems/sequel-5.17.0/lib/sequel/plugins/nested_attributes.rb:213:in `block in nested_attributes_list_setter'
	 1: from gems/sequel-5.17.0/lib/sequel/plugins/nested_attributes.rb:269:in `nested_attributes_setter'
gems/sequel-5.17.0/lib/sequel/plugins/nested_attributes.rb:269:in `values_at': no implicit conversion of Symbol into Integer (TypeError)

```

**Comment by jeremyevans** [comment]
Thanks for the report.

This is not a bug in Sequel, the documentation does not state compatibility with ActionController::Parameters.  It works with most other ruby web frameworks and probably worked correctly in older versions of Rails.  However, considering Rails' popularity, it would probably be appropriate to mentioned the incompatibility and how to work around it.  I'll work on a documentation patch shortly.
