### ISSUE TITLE
Unable to use one_to_one association with class_table_inheritance plugin

### ISSUE THREAD

**Issue by rolftimmermans** [jeremyevans/sequel#1612]
### Complete Description of Issue

When using the `class_table_inheritance` plugin, setting an associated object to the setter of a `one_to_one` association leads to an SQL syntax error when attempting to nullify the previously present object.

Side question: is it possible to disable this behaviour? In this specific case I know 100% sure that no associated object exists when attempting to save it and can rely only on the database `UNIQUE` constraint to catch any bugs.

### Simplest Possible Self-Contained Example Showing the Bug

```
require "sequel"

Sequel::Model.db = Sequel.postgres("test-db")

Sequel::Model.db.create_table("items") do
  primary_key :id
end

Sequel::Model.db.create_table("associations") do
  primary_key :id
  text :kind, null: false
  text :value, null: false
end

Sequel::Model.db.create_table("child_associations") do
  primary_key :id, table: :associations
  integer :item_id, table: :items, null: false, index: {unique: true}
end

class Association < Sequel::Model(:associations)
  plugin :class_table_inheritance, key: :kind,
    table_map: {ChildAssociation: :child_associations},
    model_map: {"child" => :ChildAssociation}
end

class ChildAssociation < Association
  many_to_one :item
end

class Item < Sequel::Model(:items)
  one_to_one :child_association
end

item = Item.new.save
item.child_association = ChildAssociation.new(value: "foo")
# Raises:
# PG::SyntaxError: ERROR:  syntax error at or near "(" (Sequel::DatabaseError)
# LINE 1: UPDATE (SELECT "associations"."id", "associations"."kind", "...
```

### Full Backtrace of Exception (if any)

```
Traceback (most recent call last):
	29: from foo.rb:36:in `<main>'
	28: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/associations.rb:2216:in `block in def_one_to_many'
	27: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/associations.rb:2646:in `set_one_to_one_associated_object'
	26: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/associations.rb:2616:in `_set_associated_object'
	25: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/associations.rb:2211:in `block in def_one_to_many'
	24: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/base.rb:1905:in `checked_transaction'
	23: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/transactions.rb:186:in `transaction'
	22: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	21: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	20: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
	19: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/transactions.rb:245:in `_transaction'
	18: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/base.rb:1905:in `block in checked_transaction'
	17: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/model/associations.rb:2212:in `block (2 levels) in def_one_to_many'
	16: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/dataset/actions.rb:872:in `update'
	15: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/dataset/actions.rb:1099:in `execute_dui'
	14: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/query.rb:50:in `execute_dui'
	13: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:314:in `execute'
	12: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	11: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
	10: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:314:in `block in execute'
	 9: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:518:in `check_database_errors'
	 8: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:314:in `block (2 levels) in execute'
	 7: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:496:in `_execute'
	 6: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:140:in `execute'
	 5: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:116:in `check_disconnect_errors'
	 4: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:140:in `block in execute'
	 3: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:152:in `execute_query'
	 2: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	 1: from /Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:152:in `block in execute_query'
/Users/rolftimmermans/.gem/ruby/2.5.0/gems/sequel-5.19.0/lib/sequel/adapters/postgres.rb:152:in `async_exec': PG::SyntaxError: ERROR:  syntax error at or near "(" (Sequel::DatabaseError)
LINE 1: UPDATE (SELECT "associations"."id", "associations"."kind", "...
               ^
```

### SQL Log (if any)

```
LOG:  statement: CREATE TABLE "items" ("id" serial PRIMARY KEY)
DEBUG:  CREATE TABLE will create implicit sequence "items_id_seq" for serial column "items.id"
DEBUG:  CREATE TABLE / PRIMARY KEY will create implicit index "items_pkey" for table "items"
DEBUG:  building index "items_pkey" on table "items"
LOG:  statement: CREATE TABLE "associations" ("id" serial PRIMARY KEY, "kind" text NOT NULL, "value" text NOT NULL)
DEBUG:  CREATE TABLE will create implicit sequence "associations_id_seq" for serial column "associations.id"
DEBUG:  building index "pg_toast_7152075_index" on table "pg_toast_7152075"
DEBUG:  CREATE TABLE / PRIMARY KEY will create implicit index "associations_pkey" for table "associations"
DEBUG:  building index "associations_pkey" on table "associations"
LOG:  statement: CREATE TABLE "child_associations" ("id" serial PRIMARY KEY REFERENCES "associations", "item_id" integer NOT NULL REFERENCES "items")
DEBUG:  CREATE TABLE will create implicit sequence "child_associations_id_seq" for serial column "child_associations.id"
DEBUG:  CREATE TABLE / PRIMARY KEY will create implicit index "child_associations_pkey" for table "child_associations"
DEBUG:  building index "child_associations_pkey" on table "child_associations"
LOG:  statement: CREATE UNIQUE INDEX "child_associations_item_id_index" ON "child_associations" ("item_id")
DEBUG:  building index "child_associations_item_id_index" on table "child_associations"
LOG:  statement: SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"associations"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
LOG:  statement: SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"child_associations"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
LOG:  statement: SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"items"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
LOG:  statement: BEGIN
LOG:  statement: INSERT INTO "items" DEFAULT VALUES RETURNING *
LOG:  statement: COMMIT
LOG:  statement: BEGIN
ERROR:  syntax error at or near "(" at character 8
STATEMENT:  UPDATE (SELECT "associations"."id", "associations"."kind", "associations"."value", "child_associations"."item_id" FROM "associations" INNER JOIN "child_associations" ON ("child_associations"."id" = "associations"."id")) AS "associations" SET "item_id" = NULL WHERE ("item_id" = 1)
LOG:  statement: ROLLBACK
```

**Comment by jeremyevans** [comment]
Thank you for the report.  This is definitely a bug, probably in the one_to_one association as opposed to something class table inheritance specific.  I'll definitely work on a fix for this before the next release.

**Comment by rolftimmermans** [comment]
Perfect, thanks!
