### ISSUE TITLE
BigDecimal conversion fails for ado decimal values when system is configured for specific locales

### ISSUE THREAD

**Issue by hapm** [jeremyevans/sequel#1619]
### Complete Description of Issue

Given the following situation:

* Windows system configure with locale using "," as a decimal separator (de,fr,...)
* Using the ado adapter with mssql database (could possibly happen with access as well, didn't test that)
* Having a decimal column in a result set of a query

results in an error similar to the following when fetching the row values:

`error: invalid value for BigDecimal(): "1234,56"`

But I expected it to be converted correctly into a BigDecimal with a value of `1234.56`.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
#!/usr/bin/env ruby
require 'sequel'
require 'win32ole'
# Make sure we have a locale with a decimal separator of "," like german = 1031
WIN32OLE.locale=1031

# Make sure you provide an connection ado:// connection string for an mssql database in ARGV[0]
DB = Sequel.connect(ARGV[0])

# Make sure we query a decimal
tmp = DB["SELECT CAST(1234.56 AS decimal(16,4)) AS value"]

# Try to get first record from the dataset, but fails because of bad conversion
STDERR.puts tmp.first.inspect
```

### Full Backtrace of Exception (if any)

```
Traceback (most recent call last):
        19: from ./bin/test.rb:12:in `<main>'

        18: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/dataset/actions.rb:208:in `first'
        17: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/dataset/actions.rb:692:in `single_record'
        16: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/dataset/actions.rb:704:in `single_record!'
        15: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/dataset/actions.rb:949:in `with_sql_first'
        14: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/dataset/actions.rb:941:in `with_sql_each'
        13: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:226:in `fetch_rows'
        12: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/dataset/actions.rb:1088:in `execute'
        11: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:154:in `execute'
        10: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/database/connecting.rb:270:in `synchronize'
         9: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
         8: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:158:in `block in execute'
         7: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:258:in `block in fetch_rows'
         6: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:258:in `each'
         5: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:263:in `block (2 levels) in fetch_rows'
         4: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:263:in `each'
         3: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:265:in `block (3 levels) in fetch_rows'
         2: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:265:in `[]'
         1: from C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:57:in `numeric'
C:/tools/ruby26/lib/ruby/gems/2.6.0/gems/sequel-5.20.0/lib/sequel/adapters/ado.rb:57:in `BigDecimal': invalid value for BigDecimal(): "1234,56" (ArgumentError)
```

### Workaround

I currently explicitly change the locale to lcid 1033 (en-us) before querying anything to fix this, but that could lead to unwanted side effects. 

### Suggested solutions

1. Add a reminder to the docs, that suggests to set the locale properly (possible side effects)
2. Change the locale to one with a "." point as a decimal separator before calling `GetRows` on the `ADO.Recordset` and revert the locale to the old one after that. 
3. Handle different separators in the converter method of columns with `AdVarNumeric` or `AdNumeric` type.

**Comment by jeremyevans** [comment]
I'll see if this is something we can handle automatically in the ADO adapter.  If not, I'll update the docs.
