### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by alexandrule** [jeremyevans/sequel#1626]
### Complete Description of Issue
I'm not sure if it is related to Sequel, but I'm trying to understand where is the issue. 
The application is scraping a big amount of data and doing multiple calls to the database.

### Simplest Possible Self-Contained Example Showing the Bug
```
user.add_comment(data)
```
### Full Backtrace of Exception (if any)
```
22:20:43 sidekiq.1     | 2019-06-23T22:20:43.966Z 3053 TID-ov5q5t4a9 WARN: SystemStackError: stack level too deep
22:20:43 sidekiq.1     | 2019-06-23T22:20:43.966Z 3053 TID-ov5q5t4a9 WARN: /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:243:in `block in owned_connection'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:283:in `block in sync'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:283:in `synchronize'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:283:in `sync'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:243:in `owned_connection'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/database/connecting.rb:270:in `synchronize'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/adapters/mysql2.rb:292:in `literal_string_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:82:in `literal_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:1028:in `block in expression_list_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:1026:in `each'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:1026:in `expression_list_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:281:in `array_sql_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:1192:in `literal_array_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:101:in `literal_append'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:1159:in `insert_values_sql'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/adapters/shared/mysql.rb:955:in `insert_values_sql'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:242:in `_insert_sql'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/sql.rb:56:in `insert_sql'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/dataset/actions.rb:396:in `insert'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1704:in `_insert_raw'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1686:in `_insert'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1753:in `block (2 levels) in _save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1015:in `around_create'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1750:in `block in _save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1015:in `around_save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1745:in `_save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1465:in `block (2 levels) in save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1905:in `block in checked_transaction'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/database/transactions.rb:258:in `_transaction'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/database/connecting.rb:270:in `synchronize'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/database/transactions.rb:199:in `transaction'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1905:in `checked_transaction'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1465:in `block in save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1893:in `checked_save_failure'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/base.rb:1465:in `save'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/associations.rb:2246:in `block in def_one_to_many'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/associations.rb:2403:in `add_associated_object'
22:20:43 sidekiq.1     | /var/www/apps/scraper/shared/bundle/ruby/2.6.0/gems/sequel-5.21.0/lib/sequel/model/associations.rb:1967:in `block in def_association_instance_methods'
```

**Comment by shanecav84** [comment]
I got the same error when updating a parent association in a child, which would re-save the child, which would re-update the parent, and so on: https://github.com/jeremyevans/sequel/issues/1589

Check that `add_comment` isn't somehow causing a re-save of `user`.

**Comment by jeremyevans** [comment]
You probably have a save hook on Comment that is causing it to save the related user.  If your application is not checking for loops when doing that, that is a bug in the application.  Since your example is not self contained, that is just a guess.  I'm going to close this now.  If you still think this is a bug in Sequel, please update with a minimal self contained example.

**Comment by alexandrule** [comment]
@shanecav84, @jeremyevans Thanks.
