### ISSUE TITLE
MSSQL Dataset#multi_insert NoMethodError: undefined method `length'

### ISSUE THREAD

**Issue by bunnrf** [jeremyevans/sequel#1627]
### Complete Description of Issue

multi_insert with just hashes provided succeeds. multi_insert with return: :primary_key succeeds in persisting records, but encounters a NoMethodError afterwards.

### Simplest Possible Self-Contained Example Showing the Bug

```
2.3.8 :003 > User.multi_insert([{name: 'test'}], return: :primary_key)
NoMethodError: undefined method `length' for #<User @values={:userid=>3921168}>
	from (irb):3
```

### Full Backtrace of Exception (if any)

```
2.3.8 :004 > def test
2.3.8 :005?>   User.multi_insert([{name: 'test'}], return: :primary_key)
2.3.8 :006?>   end
 => :test
2.3.8 :007 > begin
2.3.8 :008 >     test
2.3.8 :009?>   rescue => exception
2.3.8 :010?>     puts exception.backtrace
2.3.8 :011?>     raise # always reraise
2.3.8 :012?>   end
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/shared/mssql.rb:770:in `block in _import'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:149:in `block in each'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/tinytds.rb:224:in `block (2 levels) in fetch_rows'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/tinytds.rb:224:in `each'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/tinytds.rb:224:in `block in fetch_rows'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/tinytds.rb:65:in `block in execute'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/database/connecting.rb:253:in `synchronize'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:1083:in `execute'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/tinytds.rb:202:in `fetch_rows'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:149:in `each'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:442:in `map'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:442:in `map'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/shared/mssql.rb:770:in `_import'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/adapters/shared/mssql.rb:765:in `_import'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:354:in `import'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/dataset/actions.rb:483:in `multi_insert'
~/.rvm/gems/ruby-2.3.8/gems/sequel-5.15.0/lib/sequel/model/plugins.rb:33:in `multi_insert'
(irb):5:in `test'
(irb):8:in `irb_binding'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/context.rb:380:in `evaluate'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:489:in `block (2 levels) in eval_input'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:623:in `signal_status'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:486:in `block in eval_input'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:485:in `eval_input'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:395:in `block in start'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:394:in `catch'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/2.3.0/irb.rb:394:in `start'
~/.rvm/gems/ruby-2.3.8/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:62:in `start'
~/.rvm/gems/ruby-2.3.8/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:17:in `start'
~/.rvm/gems/ruby-2.3.8/gems/railties-5.1.6/lib/rails/commands/console/console_command.rb:97:in `perform'
~/.rvm/gems/ruby-2.3.8/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
~/.rvm/gems/ruby-2.3.8/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
~/.rvm/gems/ruby-2.3.8/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
~/.rvm/gems/ruby-2.3.8/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
~/.rvm/gems/ruby-2.3.8/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
~/.rvm/gems/ruby-2.3.8/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `block in require'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:292:in `require'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `block in load'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:258:in `load_dependency'
~/.rvm/gems/ruby-2.3.8/gems/activesupport-5.1.6/lib/active_support/dependencies.rb:286:in `load'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
~/.rvm/gems/ruby-2.3.8/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
~/.rvm/rubies/ruby-2.3.8/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
NoMethodError: undefined method `length' for #<User @values={:userid=>3921170}>
	from (irb):5:in `test'
	from (irb):8
2.3.8 :013 >
```

**Comment by jeremyevans** [comment]
Thanks for the report. Looks like multi_insert with `return: :primary_key` on a dataset with a row_proc (e.g. a model dataset) doesn't work.  I should be able to fix that.

**Comment by jeremyevans** [comment]
Actually, turns out this is specific to the optimized handling in the mssql support.  I'm running some tests with a fix now.
