### ISSUE TITLE
SystemStackError on association load with the same name as key

### ISSUE THREAD

**Issue by unleashy** [jeremyevans/sequel#1669]
### Complete Description of Issue

When trying to load an association where its key has the same name as the association, sequel enters an infinite loop and crashes. If the key has a different name it works perfectly.

### Simplest Possible Self-Contained Example Showing the Bug

https://gist.github.com/unleashy/a7eeb948b40cca4caf813f9a8a746f91

### Full Backtrace of Exception (if any)

```ruby
Traceback (most recent call last):
	10483: from demo.rb:30:in `<main>'
	10482: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:1925:in `block in def_association_method'
	10481: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:2499:in `load_associated_objects'
	10480: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:2377:in `_load_associated_objects'
	10479: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:809:in `can_have_associated_objects?'
	10478: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:809:in `any?'
	10477: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:809:in `block in can_have_associated_objects?'
	10476: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:1925:in `block in def_association_method'
	 ... 10471 levels...
	    4: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:2377:in `_load_associated_objects'
	    3: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:809:in `can_have_associated_objects?'
	    2: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:809:in `any?'
	    1: from ~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:809:in `block in can_have_associated_objects?'
~/.rvm/gems/ruby-2.6.5/gems/sequel-5.28.0/lib/sequel/model/associations.rb:1925:in `block in def_association_method': stack level too deep (SystemStackError)
```

**Comment by jeremyevans** [comment]
This behavior is expected, as by Sequel calls the method name specified by the `:key` option to get the column value.  The simplest way around it is to use the column_conflicts plugin:

```ruby
class Album < Sequel::Model
  plugin :column_conflicts
  get_column_conflict!(:artist)
  many_to_one :artist, key: :artist
end
```

**Comment by unleashy** [comment]
Thank you!
