### ISSUE TITLE
Cannot create_table for sqlite3

### ISSUE THREAD

**Issue by dteoh** [jeremyevans/sequel#1671]
### Complete Description of Issue

I cannot create a table in a new SQLite 3 database.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require 'rubygems'
require 'bundler/setup'
Bundler.require :default

DB = Sequel.sqlite 'world.db'

DB.create_table 'World' do
  primary_key :id, type: Integer
  column :randomNumber, type: Integer
end
```

Gemfile:

```ruby
source 'https://rubygems.org'

gem 'sequel'
gem 'sqlite3'
```

Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    sequel (5.28.0)
    sqlite3 (1.4.2)

PLATFORMS
  ruby

DEPENDENCIES
  sequel
  sqlite3

BUNDLED WITH
   2.0.1
```

```
$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]
```

### Full Backtrace of Exception (if any)

```
Traceback (most recent call last):
	18: from world.rb:6:in `<main>'
	17: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/database/schema_methods.rb:194:in `create_table'
	16: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/database/schema_methods.rb:684:in `create_table_from_generator'
	15: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/adapters/sqlite.rb:151:in `execute_ddl'
	14: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	13: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	12: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/adapters/sqlite.rb:154:in `block in execute_ddl'
	11: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/database/query.rb:43:in `execute_ddl'
	10: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/adapters/sqlite.rb:144:in `execute_dui'
	9: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/adapters/sqlite.rb:193:in `_execute'
	8: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	7: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
	6: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/adapters/sqlite.rb:205:in `block in _execute'
	5: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
	4: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sequel-5.28.0/lib/sequel/adapters/sqlite.rb:205:in `block (2 levels) in _execute'
	3: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:269:in `execute_batch'
	2: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
	1: from /Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
/Users/dteoh/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize': SQLite3::SQLException: unrecognized token: "{" (Sequel::DatabaseError)
```

**Comment by adam12** [comment]
The `column` method for altering tables doesn't accept a `type` argument, like the `primary_key` method does.

You're likely looking at this instead:

```ruby
column :randomNumber, Integer
```

**Comment by dteoh** [comment]
Thanks, that was the issue.
