### ISSUE TITLE
Getting error while ran execute_ddl method

### ISSUE THREAD

**Issue by mathanpt** [jeremyevans/sequel#1677]
I want to fetch schema for all tables so I execute the **GET_DDL** query as follows but returns an error 

```
client.execute_ddl("SELECT 'SELECT GET_DDL(''TABLE'',''' || table_name || ''');' AS stmt FROM INFORMATION_SCHEMA.TABLES")

Sequel::DatabaseConnectionError: ODBC::Error: 28000 (20032) [unixODBC][Snowflake][DSI] (20032) Required setting 'UID' is not present in the connection settings.

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/adapters/odbc.rb:33:in `initialize'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/adapters/odbc.rb:33:in `connect'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/adapters/odbc.rb:33:in `connect'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool.rb:103:in `make_new'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:224:in `make_new'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:197:in `available'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:133:in `_acquire'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:147:in `block in acquire'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:265:in `block in sync'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:265:in `synchronize'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:265:in `sync'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:146:in `acquire'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:104:in `hold'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/adapters/odbc.rb:58:in `execute_dui'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/sequel-4.32.0/lib/sequel/database/query.rb:45:in `execute_ddl'

	from (irb):29

	from /home/user/.rvm/gems/ruby-2.1.10/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'

	from /home/user/.rvm/gems/ruby-2.1.10/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'

	from bin/rails:4:in `require'

	from bin/rails:4:in `<main>'
```

**Comment by jeremyevans** [comment]
First, Sequel 4.32 is way out of support.  The only supported versions of Sequel are the master branch and the latest release.

Second, the error you are getting is unrelated to your query, it is happening when making a connection to the database.  Your connection setup is wrong (missing Uid according to the exception message), and you'll need to fix that.  If you have an actual ODBC connection string, try using it with the `:drvconnect` option.  If not, make sure the `:user` setting is filled in correctly.
