### ISSUE TITLE
generated_always_as incorrectly setting default value for Postgresql 12

### ISSUE THREAD

**Issue by joeosburn** [jeremyevans/sequel#1680]
### Complete Description of Issue

I am using Postgresql 12.2 and adding a column with a `:generated_always_as` option. The schema is setting a default value that uses the `generated_always_as` value, which causes issues when trying to load the schema. In this case, the `generated_always_as` option references columns in the db, but `default` values can't do that.

### Simplest Possible Self-Contained Example Showing the Bug

This is the line from my migration:
```
add_column :donations, :search, :text, generated_always_as: Sequel.join([:name, :description])
```

This creates a schema with a column line this:
```
column :search, "text", :default=>Sequel::LiteralString.new("(name || description)")
```

### Full Backtrace of Exception (if any)

```
rake aborted!
       Sequel::DatabaseError: PG::FeatureNotSupported: ERROR:  cannot use column reference in DEFAULT expression
       LINE 1: ...::text[], "match" boolean, "search" text DEFAULT (name || de...
                                                                    ^
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:156:in `exec'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:156:in `block in execute_query'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:156:in `execute_query'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:144:in `block in execute'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:120:in `check_disconnect_errors'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:144:in `execute'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/database/connecting.rb:270:in `synchronize'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/adapters/postgres.rb:318:in `execute'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/database/query.rb:50:in `execute_dui'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/database/query.rb:43:in `execute_ddl'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/database/schema_methods.rb:684:in `create_table_from_generator'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/database/schema_methods.rb:194:in `create_table'
       /app/db/schema.rb:154:in `block (2 levels) in <top (required)>'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
       /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.30.0/lib/sequel/extensions/migration.rb:107:in `apply'
       /app/tasks/db/sequel.rake:67:in `block (4 levels) in <top (required)>'
       /app/tasks/db/sequel.rake:67:in `each'
       /app/tasks/db/sequel.rake:67:in `block (3 levels) in <top (required)>'
       /app/vendor/bundle/ruby/2.6.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
```

### SQL Log (if any)

n/a

**Comment by jeremyevans** [comment]
This definitely looks like an issue in the schema dumper.  It should at least recognize when the column is generated and not include a default in that case.

I'll have to see how difficult it would be to actually dump a correct :generated_always_as option.  If it isn't too difficult, that may be possible.  However, I can't make any promises in that area.  There are tons of other things the schema dumper doesn't handle, after all.
