### ISSUE TITLE
Mysql2::Error: Invalid date in field 'XXX': 2030-11-00 (Sequel::DatabaseError)

### ISSUE THREAD

**Issue by nhh** [jeremyevans/sequel#1687]
### Complete Description of Issue
Mysql2 Adapter cannot be configured to skip type casting. There is a issue describing this behavior.  (https://github.com/brianmario/mysql2/issues/1009)

The main consent in solving this problem is deactivating type casts. I cannot see where i can access the configuration of an adapter. Would appreciate any pointer to good docs or some educated guess what i cant do about this.

### Simplest Possible Self-Contained Example Showing the Bug
Having an invalid date row and firing a single query.

### Full Backtrace of Exception (if any)
app.rb:6:in `DB[:table].first(100)`
```
Traceback (most recent call last):
        15: from app.rb:6:in `<main>'
        14: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/dataset/actions.rb:229:in `first'
        13: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/dataset/actions.rb:51:in `all'
        12: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/dataset/actions.rb:1006:in `_all'
        11: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/dataset/actions.rb:51:in `block in all'
        10: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/dataset/actions.rb:152:in `each'
         9: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/mysql2.rb:236:in `fetch_rows'
         8: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/mysql2.rb:276:in `execute'
         7: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/dataset/actions.rb:1089:in `execute'
         6: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `execute'
         5: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/database/connecting.rb:270:in `synchronize'
         4: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
         3: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/utils/mysql_mysql2.rb:39:in `block in execute'
         2: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/mysql2.rb:151:in `_execute'
         1: from /Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/mysql2.rb:238:in `block in fetch_rows'
/Users/niklashanft/.rvm/gems/ruby-2.6.5/gems/sequel-5.30.0/lib/sequel/adapters/mysql2.rb:238:in `each': Invalid date in field 'datum_vertraege': 2030-11-00 (Mysql2::Error)
```

### SQL Log (if any)

Thank you!

**Comment by nhh** [comment]
Finally resolved it with string comparison:

```
UPDATE _table_ SET _column_ = '1970-01-01' where DATE_FORMAT(_column_, '%Y-%m-%d') = '2030-11-00';
```

Step by step the error gone away.
