### ISSUE TITLE
Creating partitioned table with `create_table?` causes `LocalJumpError (no block given)`

### ISSUE THREAD

**Issue by Gurrium** [jeremyevans/sequel#1690]
### Complete Description of Issue
`LocalJumpError (no block given)` will cause when try to create partitioned table with `create_table?`.
I'm using postgres adapter.

IMHO, it's caused by creating table generater without postgres adapter.
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/database/schema_methods.rb#L218-L220
https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/postgres.rb#L455

### Simplest Possible Self-Contained Example Showing the Bug
```sql
-- in psql
CREATE DATABASE database_name
```
```ruby
require 'sequel'

db = Sequel.connect(
  adapter: 'postgres',
  host: 'host_name',
  user: 'user_name',
  password: 'password',
  database: 'database_name'
)
db.create_table('base_table', partition_by: :column, partition_type: :range) do
  Integer :id
  Date :column
end
db.create_table?('base_table_202001', partition_of: 'base_table') do
  from '2020-01-01'
  to '2020-02-01'
end
```

### Full Backtrace of Exception (if any)
```ruby
# irb
begin
  # code above
rescue => exception
  puts exception.backtrace
end
```

```
/usr/local/bundle/ruby/2.6.0/gems/sequel-5.31.0/lib/sequel/adapters/shared/postgres.rb:143:in `instance_exec'
/usr/local/bundle/ruby/2.6.0/gems/sequel-5.31.0/lib/sequel/adapters/shared/postgres.rb:143:in `initialize'
/usr/local/bundle/ruby/2.6.0/gems/sequel-5.31.0/lib/sequel/adapters/shared/postgres.rb:455:in `new'
/usr/local/bundle/ruby/2.6.0/gems/sequel-5.31.0/lib/sequel/adapters/shared/postgres.rb:455:in `create_table'
/usr/local/bundle/ruby/2.6.0/gems/sequel-5.31.0/lib/sequel/database/schema_methods.rb:220:in `create_table?'
(irb):20:in `rescue in irb_binding'
(irb):19:in `irb_binding'
/usr/local/lib/ruby/2.6.0/irb/workspace.rb:85:in `eval'
/usr/local/lib/ruby/2.6.0/irb/workspace.rb:85:in `evaluate'
/usr/local/lib/ruby/2.6.0/irb/context.rb:385:in `evaluate'
/usr/local/lib/ruby/2.6.0/irb.rb:493:in `block (2 levels) in eval_input'
/usr/local/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
/usr/local/lib/ruby/2.6.0/irb.rb:490:in `block in eval_input'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
/usr/local/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/usr/local/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
/usr/local/lib/ruby/2.6.0/irb.rb:428:in `block in run'
/usr/local/lib/ruby/2.6.0/irb.rb:427:in `catch'
/usr/local/lib/ruby/2.6.0/irb.rb:427:in `run'
/usr/local/lib/ruby/2.6.0/irb.rb:383:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
/usr/local/bin/irb:23:in `load'
/usr/local/bin/irb:23:in `<main>'
```

**Comment by jeremyevans** [comment]
Thanks for the report.  This is definitely a bug.  I've got a fix ready for it, just need to run more tests with it and then commit it.
