### ISSUE TITLE
Attempt to update object did not result in a single row modification

### ISSUE THREAD

**Issue by lloydpick** [jeremyevans/sequel#1696]
Since the latest release, 5.32.0, I am seeing this error occur a lot, compared to not happening at all before. We don't delete rows at all in this database so it's 100% there. UUIDs are used for primary keys & it's a mySQL Aurora DB.

```
I, [2020-05-18T12:03:52.811198 #9] INFO -- : (0.005941s) BEGIN
I, [2020-05-18T12:03:52.812663 #9] INFO -- : (0.001225s) SELECT * FROM `tasks` WHERE (`uuid` = '1edd183c-98ff-11ea-b985-02fd4200f08c') LIMIT 1 FOR UPDATE
I, [2020-05-18T12:03:52.815324 #9] INFO -- : (0.001983s) UPDATE `tasks` SET `started_at` = '2020-05-18T12:01:30.873Z' WHERE (`uuid` = '1edd183c-98ff-11ea-b985-02fd4200f08c') LIMIT 1
I, [2020-05-18T12:03:52.830921 #9] INFO -- : (0.015364s) ROLLBACK
Error raised from handler method
{
"errorMessage": "Attempt to update object did not result in a single row modification (SQL: UPDATE `tasks` SET `started_at` = '2020-05-18T12:01:30.873Z' WHERE (`uuid` = '1edd183c-98ff-11ea-b985-02fd4200f08c') LIMIT 1)",
"errorType": "Function<Sequel::NoExistingObject>",
"stackTrace": [
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1861:in `_update'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1854:in `_update_columns'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1787:in `block (2 levels) in _save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1015:in `around_update'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1771:in `block in _save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1015:in `around_save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1753:in `_save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1465:in `block (2 levels) in save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1919:in `block in checked_transaction'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/transactions.rb:225:in `block in transaction'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/connecting.rb:270:in `synchronize'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/transactions.rb:195:in `transaction'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1919:in `checked_transaction'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1465:in `block in save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1907:in `checked_save_failure'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1465:in `save'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1478:in `save_changes'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:2068:in `update_restricted'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/model/base.rb:1579:in `update'",
  "/var/task/handler.rb:34:in `block (2 levels) in execute'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/transactions.rb:254:in `_transaction'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/transactions.rb:229:in `block in transaction'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/connecting.rb:270:in `synchronize'",
  "/var/task/vendor/bundle/ruby/2.5.0/gems/sequel-5.32.0/lib/sequel/database/transactions.rb:195:in `transaction'",
  "/var/task/handler.rb:21:in `block in execute'",
  "/var/task/handler.rb:15:in `each'",
  "/var/task/handler.rb:15:in `execute'",
  "/var/task/main.rb:50:in `lambda_handler'"
]
```

I've downgraded back to 5.31.0 and the errors disappear.

**Comment by jeremyevans** [comment]
Can you please post a self contained reproducible example showing the problem?

**Comment by jeremyevans** [comment]
I attempted to reproduce the issue and I'm unable to.  The following code runs without errors:

```ruby
DB.create_table!(:tasks){String :uuid, :primary_key=>true; Time :started_at, :default=>Sequel::CURRENT_TIMESTAMP}
class Task < Sequel::Model; end
Task.create{|task| task.uuid = '1edd183c-98ff-11ea-b985-02fd4200f08c'}
DB.transaction do
  Task.for_update.first.save
end
```

SQL Log for the transaction:

```ruby
I, [2020-05-18T08:03:46.605994 #85965]  INFO -- : (0.000164s) BEGIN
I, [2020-05-18T08:03:46.606733 #85965]  INFO -- : (0.000457s) SELECT * FROM `tasks` LIMIT 1 FOR UPDATE
I, [2020-05-18T08:03:46.607580 #85965]  INFO -- : (0.000308s) UPDATE `tasks` SET `started_at` = '2020-05-18 08:03:40' WHERE (`uuid` = '1edd183c-98ff-11ea-b985-02fd4200f08c') LIMIT 1
I, [2020-05-18T08:03:46.607856 #85965]  INFO -- : (0.000154s) COMMIT
```

Maybe this issue is specific to Aurora.  Can you reproduce it on standard MySQL or MariaDB?

I looked at changes between 5.31.0 and 5.32.0 and nothing jumps out as being related to this.

**Comment by jeremyevans** [comment]
Closing this due to lack of response.  If you can put together a self contained reproducible example, please post it so I can review and consider whether to reopen this.
