### ISSUE TITLE
Passwordless connection to PostgreSQL 13 fails, when it works fine with PostgreSQL 12.4

### ISSUE THREAD

**Issue by clonezone** [jeremyevans/sequel#1718]
#### Versions

ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

sequel 5.36.0
pg 1.2.3
(identical results with and without sequel_pg 1.13.0 present)

CentOS Linux release 7.7.1908

PostgreSQL binaries are the RPMs under https://yum.postgresql.org/12/redhat/rhel-7-x86_64/ and https://yum.postgresql.org/13/redhat/rhel-7-x86_64/

#### PostgreSQL set-up

`postgresql.conf` is unmodified from the default, i.e. we're using the identd protocol to identify the user to the database. No password required.

#### This is not a driver issue

Stealing from the PG `README.md`:

    ruby -e 'require "pg"; PG.connect(dbname: "my-database").exec("select * from pg_stat_activity").each { |row| puts row.inspect}'

works with both PostgreSQL 12.4 and 13.0.

#### The Sequel issue

Simply attempting connection with PostgreSQL v13.0 fails, when it succeeds with v12.4.

### Simplest Possible Self-Contained Example Showing the Bug

    ruby -e 'require "sequel"; Sequel.connect("postgres://localhost/my-database")'

This succeeds with PostgreSQL v12.4 and fails with the below exception with PostgreSQL v13.0.

### Full Backtrace of Exception (if any)

```
> ruby -e 'require "sequel"; Sequel.connect("postgres://localhost/my-database")'
Traceback (most recent call last):
	11: from -e:1:in `<main>'
	10: from /install/path/gems/sequel-5.36.0/lib/sequel/core.rb:125:in `connect'
	 9: from /install/path/gems/sequel-5.36.0/lib/sequel/database/connecting.rb:58:in `connect'
	 8: from /install/path/gems/sequel-5.36.0/lib/sequel/database/connecting.rb:279:in `test_connection'
	 7: from /install/path/gems/sequel-5.36.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	 6: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	 5: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
	 4: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
	 3: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool.rb:122:in `make_new'
	 2: from /install/path/gems/sequel-5.36.0/lib/sequel/adapters/postgres.rb:210:in `connect'
	 1: from /install/path/gems/sequel-5.36.0/lib/sequel/adapters/postgres.rb:210:in `new'
/install/path/gems/sequel-5.36.0/lib/sequel/adapters/postgres.rb:210:in `initialize': fe_sendauth: no password supplied (PG::ConnectionBad)
	11: from -e:1:in `<main>'
	10: from /install/path/gems/sequel-5.36.0/lib/sequel/core.rb:125:in `connect'
	 9: from /install/path/gems/sequel-5.36.0/lib/sequel/database/connecting.rb:58:in `connect'
	 8: from /install/path/gems/sequel-5.36.0/lib/sequel/database/connecting.rb:279:in `test_connection'
	 7: from /install/path/gems/sequel-5.36.0/lib/sequel/database/connecting.rb:270:in `synchronize'
	 6: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
	 5: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
	 4: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
	 3: from /install/path/gems/sequel-5.36.0/lib/sequel/connection_pool.rb:122:in `make_new'
	 2: from /install/path/gems/sequel-5.36.0/lib/sequel/adapters/postgres.rb:210:in `connect'
	 1: from /install/path/gems/sequel-5.36.0/lib/sequel/adapters/postgres.rb:210:in `new'
/install/path/gems/sequel-5.36.0/lib/sequel/adapters/postgres.rb:210:in `initialize': PG::ConnectionBad: fe_sendauth: no password supplied (Sequel::DatabaseConnectionError)
```

**Comment by jeremyevans** [comment]
Does the following work?:

```ruby
ruby -e 'require "sequel"; Sequel.postgres(:conn_str=>{dbname: "my-database"})'
```

**Comment by clonezone** [comment]
Yes.

**Comment by jeremyevans** [comment]
The only parameter Sequel passes to PG in addition to what you pass in the URL is `:connect_timeout`.  Does the following work when using PG directly?:

```
ruby -e 'require "pg"; PG.connect(dbname: "my-database", connect_timeout: 20).exec("select * from pg_stat_activity").each { |row| puts row.inspect}'
```

**Comment by jeremyevans** [comment]
The only other thing I think it could be is the explicit use of localhost, so you could try:

```
ruby -e 'require "sequel"; Sequel.connect("postgres:///my-database")'
```

**Comment by clonezone** [comment]
Yes.

**Comment by clonezone** [comment]
Removing `localhost` from the URI works.

**Comment by jeremyevans** [comment]
`localhost` is not the same as empty host, as `localhost` uses IP connection and empty host uses Unix socket.  This isn't a bug in Sequel.  I'm not sure why it worked in earlier versions.

**Comment by clonezone** [comment]
Thanks!
