### ISSUE TITLE
Sequel::Error (delayed evaluations cannot be used in prepared statements) when using `prepared_statements` and `single_table_inheritance` plugins together

### ISSUE THREAD

**Issue by pashpashkin** [jeremyevans/sequel#1721]
### Complete Description of Issue
An error is raising while using `prepared_statements` and `single_table_inheritance` plugins together and trying to update the existing "child" record
```
ruby:   2.7.1
sequel: 5.36.0
```

### Simplest Possible Self-Contained Example Showing the Bug
```ruby
require 'sequel/core'
require 'sequel/model'
require 'logger'

DB = Sequel.connect('postgres:///database')
DB.loggers << Logger.new($stdout)

DB.create_table(:parents) do
  primary_key :id

  column :kind, String, null: false
  column :content, String, null: false, text: true
end

class Parent < Sequel::Model
  plugin :prepared_statements
  plugin :single_table_inheritance, :kind
end

class Child < Parent; end

child = Child.create(content: 'Test')
child.update(content: 'Updated test')
```

### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
       16: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/prepared_statements.rb:154:in `prepared_sql'
       15: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:185:in `update_sql'
       14: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:244:in `_update_sql'
       13: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:1495:in `select_where_sql'
       12: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:89:in `literal_append'
       11: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:1249:in `literal_expression_append'
       10: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/sql.rb:112:in `to_s_append'
        9: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/model/associations.rb:2870:in `complex_expression_sql_append'
        8: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/adapters/shared/postgres.rb:1556:in `complex_expression_sql_append'
        7: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:414:in `complex_expression_sql_append'
        6: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:414:in `each'
        5: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:416:in `block in complex_expression_sql_append'
        4: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:89:in `literal_append'
        3: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/sql.rb:1249:in `literal_expression_append'
        2: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/sql.rb:112:in `to_s_append'
        1: from /Users/pavelkuzovkin/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.36.0/lib/sequel/dataset/prepared_statements.rb:136:in `delayed_evaluation_sql_append'
Sequel::Error (delayed evaluations cannot be used in prepared statements)
```

### SQL Log (if any)
```
I, [2020-09-30T20:30:21.764430 #32879]  INFO -- : (0.000319s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
I, [2020-09-30T20:30:21.769408 #32879]  INFO -- : (0.004764s) CREATE TABLE "parents" ("id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "kind" text NOT NULL, "content" text NOT NULL)
I, [2020-09-30T20:30:21.772723 #32879]  INFO -- : (0.002380s) SELECT "pg_attribute"."attname" AS "name", CAST("pg_attribute"."atttypid" AS integer) AS "oid", CAST("basetype"."oid" AS integer) AS "base_oid", format_type("basetype"."oid", "pg_type"."typtypmod") AS "db_base_type", format_type("pg_type"."oid", "pg_attribute"."atttypmod") AS "db_type", pg_get_expr("pg_attrdef"."adbin", "pg_class"."oid") AS "default", NOT "pg_attribute"."attnotnull" AS "allow_null", COALESCE(("pg_attribute"."attnum" = ANY("pg_index"."indkey")), false) AS "primary_key", "pg_attribute"."attidentity", ("pg_attribute"."attgenerated" != '') AS "generated" FROM "pg_class" INNER JOIN "pg_attribute" ON ("pg_attribute"."attrelid" = "pg_class"."oid") INNER JOIN "pg_type" ON ("pg_type"."oid" = "pg_attribute"."atttypid") LEFT OUTER JOIN "pg_type" AS "basetype" ON ("basetype"."oid" = "pg_type"."typbasetype") LEFT OUTER JOIN "pg_attrdef" ON (("pg_attrdef"."adrelid" = "pg_class"."oid") AND ("pg_attrdef"."adnum" = "pg_attribute"."attnum")) LEFT OUTER JOIN "pg_index" ON (("pg_index"."indrelid" = "pg_class"."oid") AND ("pg_index"."indisprimary" IS TRUE)) WHERE (("pg_attribute"."attisdropped" IS FALSE) AND ("pg_attribute"."attnum" > 0) AND ("pg_class"."oid" = CAST(CAST('"parents"' AS regclass) AS oid))) ORDER BY "pg_attribute"."attnum"
I, [2020-09-30T20:30:21.775189 #32879]  INFO -- : (0.000087s) BEGIN
I, [2020-09-30T20:30:21.775651 #32879]  INFO -- : (0.000102s) PREPARE smpsp_1 AS INSERT INTO "parents" ("content", "kind") VALUES ($1, $2) RETURNING "id", "kind", "content"
I, [2020-09-30T20:30:21.775983 #32879]  INFO -- : (0.000285s) EXECUTE smpsp_1 (INSERT INTO "parents" ("content", "kind") VALUES ($1, $2) RETURNING "id", "kind", "content"); ["Test", "Child"]
I, [2020-09-30T20:30:21.776185 #32879]  INFO -- : (0.000158s) COMMIT
I, [2020-09-30T20:30:21.776274 #32879]  INFO -- : (0.000026s) BEGIN
I, [2020-09-30T20:30:21.776487 #32879]  INFO -- : (0.000029s) ROLLBACK
```

**Comment by jeremyevans** [comment]
It is expected that delayed evaluations are not compatible with prepared statements.  So we should probably have the single_table_inheritance plugin automatically disable prepared statements.

I've already performed the acceptance testing for tomorrow's release, so I'll make thechange after the release.  In the meantime, you can probably add the following method to the Parent model to work around the problem:

```ruby
private def use_prepared_statements_for?(type); false end
```

**Comment by pashpashkin** [comment]
@jeremyevans Sorry, I've just realized that it was already solved in the `class_table_inheritance` plugin and I've missed how it was done. 
Thanks a lot!
