### ISSUE TITLE
Connecting Postgres with certificate

### ISSUE THREAD

**Issue by gustavodiel** [jeremyevans/sequel#1728]
### Complete Description of Issue

When trying to connect into a Postgres server with SSL mode as `verify-ca`, it will result in a `Sequel::DatabaseConnectionError (PG::ConnectionBad: FATAL:  connection requires a valid client certificate)` error.

#### Possible Reason

Reading [Postgres documentation](https://www.postgresql.org/docs/9.1/libpq-ssl.html) both `sslcert` and `sslkey` are needed, but in the [code](https://github.com/jeremyevans/sequel/blob/8a8a93983aad97f3e1dbdf17a9a13fb659227dbb/lib/sequel/adapters/postgres.rb#L208) and [doc](https://github.com/jeremyevans/sequel/blob/a84e8368d7f5b9816474eb92bd198052fec103f7/doc/opening_databases.rdoc#postgres-) it only supports `sslmode` and `sslrootcert`

#### Possible workaround

In order to fix this, one could define both ENV variables:
```ruby
ENV["PGSSLCERT"] = "~/client-cert.pem"
ENV["PGSSLKEY"] = "~/client-key.pem"
```

### Simplest Possible Self-Contained Example Showing the Bug

1. Setup a PG with SSL certificates (like in Google CloudSQL) and that allows certificated connections only
2. The connection code should look like this:
```ruby
url = "postgres://user:password@12.34.56.78/my_base"

conn = Sequel.connect(
    url,
    sslmode: 'verify-ca',
    sslrootcert: "server-ca.pem",
    sslcert: "client-cert.pem",
    sslkey: "client-key.pem"
)
```
3. It will raise the error

### Full Backtrace of Exception (if any)

```
Traceback (most recent call last):
       16: from /home/user/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
       15: from /home/user/.rbenv/versions/2.7.1/bin/irb:23:in `load'
       14: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb:11:in `<top (required)>'
       13: from (irb):38
       12: from (irb):39:in `rescue in irb_binding'
       11: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/core.rb:124:in `connect'
       10: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/database/connecting.rb:58:in `connect'
        9: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/database/connecting.rb:279:in `test_connection'
        8: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/database/connecting.rb:270:in `synchronize'
        7: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
        6: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/connection_pool/threaded.rb:139:in `acquire'
        5: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/connection_pool/threaded.rb:209:in `assign_connection'
        4: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/connection_pool.rb:122:in `make_new'
        3: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/adapters/postgres.rb:210:in `connect'
        2: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/adapters/postgres.rb:210:in `new'
        1: from /home/user/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/sequel-5.37.0/lib/sequel/adapters/postgres.rb:210:in `initialize'
Sequel::DatabaseConnectionError (PG::ConnectionBad: FATAL:  connection requires a valid client certificate)
```

**Comment by janko** [comment]
You should be able to use `:driver_options`, which are all passed to `PG::Connection.connect`:

```rb
```

**Comment by jeremyevans** [comment]
Sequel only supports the :sslmode and :sslrootcert options.  For other SSL options, you need to set driver_options, as @janko mentioned.
