### ISSUE TITLE
create_table -> String, type: text, size: :long - not working on PostgreSQL

### ISSUE THREAD

**Issue by hmdne** [jeremyevans/sequel#1750]
### Complete Description of Issue

MySQL/MariaDB has various versions of `text` type, most importantly, `longtext`. We used the code below to make our application database agnostic - the default `text` type is limited in MariaDB to 65535 characters (same with `blob` vs `longblob`). This kind of code works perfectly well in SQLite (and MariaDB), but it breaks with Postgres, for which it generates invalid SQL. Postgres has only 1 version, `text`, yet this code translates the type to `varchar(long)`.

Do note that `File :blob, size: :long` works with all 3 database engines.

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
require "sequel"
require "logger"

for db in [Sequel.sqlite(logger: Logger.new($stdout)),
           Sequel.connect("postgres://", logger: Logger.new($stdout))]
  db.create_table :tags do
    String :description, text: true, size: :long
  end
end
```

### Full Backtrace of Exception (if any)

```
/home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:156:in `exec': PG::SyntaxError: ERROR:  syntax error at or near "long" (Sequel::DatabaseError)
LINE 1: CREATE TABLE "tags" ("description" varchar(long))
                                                   ^
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:156:in `block in execute_query'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:156:in `execute_query'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:144:in `block in execute'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:120:in `check_disconnect_errors'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:144:in `execute'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/database/connecting.rb:269:in `synchronize'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/postgres.rb:318:in `execute'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/database/query.rb:50:in `execute_dui'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/database/query.rb:43:in `execute_ddl'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/database/schema_methods.rb:686:in `create_table_from_generator'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/database/schema_methods.rb:194:in `create_table'
	from /home/user/Code/.gem/gems/sequel-5.40.0/lib/sequel/adapters/shared/postgres.rb:459:in `create_table'
	from sequel.rb:6:in `block in <main>'
	from sequel.rb:4:in `each'
	from sequel.rb:4:in `<main>'
```

### SQL Log (if any)

```
I, [2021-01-29T08:07:14.633861 #131284]  SQLITE INFO -- : (0.000089s) PRAGMA foreign_keys = 1
I, [2021-01-29T08:07:14.633919 #131284]  SQLITE INFO -- : (0.000011s) PRAGMA case_sensitive_like = 1
I, [2021-01-29T08:07:14.693621 #131284]  POSTGRES INFO -- : (0.000067s) SET standard_conforming_strings = ON
I, [2021-01-29T08:07:14.693689 #131284]  POSTGRES INFO -- : (0.000024s) SET client_min_messages = 'WARNING'
I, [2021-01-29T08:07:14.693728 #131284]  POSTGRES INFO -- : (0.000022s) SET DateStyle = 'ISO'
I, [2021-01-29T08:07:14.694020 #131284]  SQLITE INFO -- : (0.000154s) CREATE TABLE `tags` (`description` text)

Failed POSTGRES: CREATE TABLE "tags" ("description" varchar(long))
```

**Comment by jeremyevans** [comment]
Thanks for the report! It doesn't really make sense to use both `text: true` and `size: :long` on PostgreSQL or SQLite.  However, the PostgreSQL support should operate the same as Sequel's default, where the `:text` takes priority over the `:size` option.  I'll push a fix for that shortly.
