### ISSUE TITLE
sqlite: set_column_allow_null deletes indexes

### ISSUE THREAD

**Issue by x-yuri** [jeremyevans/sequel#1761]
### Complete Description of Issue

The following migration:

```rb
    alter_table :users do
      set_column_allow_null :last_name
    end
```

deletes indexes created by the following migration:

```rb
    alter_table(:users) do
      add_index :fb_id, unique: true, where: 'fb_id IS NOT NULL'
    end
```

That happens because `Database#indexes` [doesn't return][a] partial indexes. That leads to `Database#duplicate_table` [not recreating][b] the indexes. A couple more references:

https://github.com/jeremyevans/sequel/blob/5.43.0/lib/sequel/database/schema_generator.rb#L630 (`set_column_allow_null` -> `set_column_null`)
https://github.com/jeremyevans/sequel/blob/5.43.0/lib/sequel/adapters/shared/sqlite.rb#L254 (`set_column_null` -> `duplicate_table`)

[a]: https://github.com/jeremyevans/sequel/commit/5954cd6d2733eec4ac3697f25ed1d6ea92f1b310#diff-9a07e9ea825021ea7117238d04accfc79dc951839fae70b8c8b9233b03e60c01R138
[b]: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/adapters/shared/sqlite.rb#L455-L460

### Simplest Possible Self-Contained Example Showing the Bug

`migrations/001_create_users_table.rb`:

```rb
Sequel.migration do
  change do
    create_table(:users) do
      primary_key :id
      String :last_name
      String :fb_id
    end
  end
end
```
`migrations/002_users_add_index.rb`:

```rb
Sequel.migration do
  change do
    alter_table(:users) do
      add_index :fb_id, unique: true, where: 'fb_id IS NOT NULL'
    end
  end
end
```

`migrations/003_users_set_null.rb`:

```rb
Sequel.migration do
  change do
    alter_table :users do
      set_column_allow_null :last_name
    end
  end
end
```

### Full Backtrace of Exception (if any)

```
Sequel::DatabaseError: SQLite3::SQLException: no such index: users_fb_id_index
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:275:in `execute_batch'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:196:in `block (2 levels) in _execute'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:196:in `block in _execute'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:182:in `_execute'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:131:in `execute_dui'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/query.rb:43:in `execute_ddl'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:143:in `block in execute_ddl'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:138:in `execute_ddl'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `block (3 levels) in apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `each'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `block (2 levels) in apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `each'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `block in apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/transactions.rb:245:in `_transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/transactions.rb:186:in `transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:187:in `apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/schema_methods.rb:433:in `apply_alter_table_generator'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/schema_methods.rb:70:in `alter_table'
migrations/003_users_set_null.rb:3:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:107:in `apply'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:558:in `block (2 levels) in run'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:477:in `checked_transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:554:in `block in run'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:551:in `each'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:551:in `run'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:402:in `run'
/app/src/tasks/db.rake:23:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'

Caused by:
SQLite3::SQLException: no such index: users_fb_id_index
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `initialize'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `new'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:147:in `prepare'
/usr/local/bundle/gems/sqlite3-1.4.2/lib/sqlite3/database.rb:275:in `execute_batch'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:196:in `block (2 levels) in _execute'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/logging.rb:43:in `log_connection_yield'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:196:in `block in _execute'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:182:in `_execute'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:131:in `execute_dui'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/query.rb:43:in `execute_ddl'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:143:in `block in execute_ddl'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/sqlite.rb:138:in `execute_ddl'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `block (3 levels) in apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `each'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `block (2 levels) in apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `each'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:200:in `block in apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/transactions.rb:245:in `_transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/transactions.rb:220:in `block in transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/connecting.rb:270:in `synchronize'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/transactions.rb:186:in `transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/adapters/shared/sqlite.rb:187:in `apply_alter_table'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/schema_methods.rb:433:in `apply_alter_table_generator'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/database/schema_methods.rb:70:in `alter_table'
migrations/003_users_set_null.rb:3:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:107:in `instance_exec'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:107:in `apply'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:558:in `block (2 levels) in run'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:477:in `checked_transaction'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:554:in `block in run'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:551:in `each'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:551:in `run'
/usr/local/bundle/gems/sequel-5.17.0/lib/sequel/extensions/migration.rb:402:in `run'
/app/src/tasks/db.rake:23:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by jeremyevans** [comment]
This is expected.  SQLite does not support the operation you want to make.  Sequel attempts to emulate `create_table` on SQLite to support many things that SQLite doesn't natively support, but I'm not planning to add emulation of support for partial indexes.

Note on the current version of Sequel, instead of an error being raised, the index is silently dropped.  Here's the SQL executed by the third migration:

```
PRAGMA foreign_keys = 0
PRAGMA legacy_alter_table = 1
BEGIN
PRAGMA table_xinfo('users')
PRAGMA foreign_key_list('users')
PRAGMA index_list('users')
SAVEPOINT autopoint_1
Exception: no such table: users_backup0: SELECT NULL AS 'nil' FROM `users_backup0` LIMIT 1
ROLLBACK TO SAVEPOINT autopoint_1
PRAGMA index_list('users')
ALTER TABLE `users` RENAME TO `users_backup0`
CREATE TABLE `users`(`id` integer DEFAULT (NULL) NOT NULL PRIMARY KEY AUTOINCREMENT, `last_name` varchar(255) DEFAULT (NULL) NULL, `fb_id` varchar(255) DEFAULT (NULL) NULL)
INSERT INTO `users`(`id`, `last_name`, `fb_id`) SELECT `id`, `last_name`, `fb_id` FROM `users_backup0`
DROP TABLE `users_backup0`
COMMIT
PRAGMA foreign_keys = 1
PRAGMA legacy_alter_table = 0
```

You can work around this by adding the `add_index` line to the third migration, after the `set_column_allow_null`.

If you really want to get this fixed, get SQLite to implement support for changing the NULL/NOT NULL setting for a column in a table.

**Comment by x-yuri** [comment]
Well, actually my situation is a bit more complex than that. I'm trying to apply PostgreSQL migrations to SQlite to not run PostgreSQL during `docker` build. My goal is to generate api documentation ([`grape-swagger`][a]). And I'm not sure it will work without db. So my options probably are:

* make migrations behave differently for SQlite (`if ENV['DATABASE_ADAPTER'] == 'sqlite'`)
* run PostgreSQL after all
* give up on `docker`
* give up on humanity :)

P.S. I'm kind of jealous of the number of open issues in your repository. Given the popularity of your project... Well, about that I'm not sure. In any case, you don't often see that. And thanks for your work :)

[a]: https://github.com/ruby-grape/grape-swagger

**Comment by jeremyevans** [comment]
For the first option, you can use `database_type` in the migrations (you can't call it directly inside the `alter_table` block though):

```ruby
    db_type = database_type
    alter_table :users do
      set_column_allow_null :last_name
      add_index :fb_id, unique: true, where: 'fb_id IS NOT NULL' if db_type == :sqlite
    end
```

If that will work for you, it may be the simplest solution.  Running PostgreSQL is also fine, but if it complicates your docker setup, I'm guessing a one-line workaround is easier.  If you can get your api documentation generated without docker, that's probably an even better solution, but it may also require more work.

Don't give up on humanity, even though it may appear beyond hope. :)
