### ISSUE TITLE
Using Quota as a model name creates confusion for relation name resolution

### ISSUE THREAD

**Issue by furkansahin** [jeremyevans/sequel#1770]
### Complete Description of Issue
Using "Quota" as model name creates a resolution issue. The plural form of "quota" is "quotas", so, my table name in database is Quotas. The model is defined as 
```
class Quota < Sequel::Model
```

However, the resolution of this model to database relation name is as Quota. So it fails to find the model in DB.

### Simplest Possible Self-Contained Example Showing the Bug
```
Sequel.migration do
  change do
    create_table(:quotas) do
      timestamptz :created_at, default: Sequel.function(:now), null: false
      timestamptz :updated_at, default: Sequel.function(:now), null: false
    end
  end
end
```

```
class Quota < Sequel::Model
  plugin :timestamps, update_on_create: true
end
```

when we try to run that

### Full Backtrace of Exception (if any)
```
/home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:156:in `exec': ERROR:  relation "quota" does not exist (PG::UndefinedTable)
LINE 1: SELECT * FROM "quota" LIMIT 1
                      ^
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:156:in `block in execute_query'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:156:in `execute_query'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:144:in `block in execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:120:in `check_disconnect_errors'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:144:in `execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:500:in `_execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:318:in `block (2 levels) in execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:522:in `check_database_errors'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:318:in `block in execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/connection_pool/threaded.rb:88:in `hold'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/database/connecting.rb:270:in `synchronize'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:318:in `execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/dataset/actions.rb:1089:in `execute'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/adapters/postgres.rb:614:in `fetch_rows'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/dataset/actions.rb:152:in `each'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel_pg-1.14.0/lib/sequel_pg/sequel_pg.rb:81:in `each'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/dataset/actions.rb:86:in `columns!'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/dataset/actions.rb:76:in `columns'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:242:in `columns'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:769:in `block (2 levels) in get_db_schema'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:683:in `block in check_non_connection_error'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/database/transactions.rb:201:in `block in transaction'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/database/connecting.rb:270:in `synchronize'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/database/transactions.rb:195:in `transaction'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:683:in `check_non_connection_error'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:769:in `block in get_db_schema'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:802:in `get_db_schema'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:603:in `set_dataset'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/sequel-5.35.0/lib/sequel/model/base.rb:850:in `inherited'
        from /home/furkan/Workspace/PetProject/lib/models/quota.rb:1:in `<top (required)>'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/pliny-0.30.0/lib/pliny/utils.rb:25:in `require'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/pliny-0.30.0/lib/pliny/utils.rb:25:in `block in require_glob'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/pliny-0.30.0/lib/pliny/utils.rb:24:in `each'
        from /home/furkan/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/pliny-0.30.0/lib/pliny/utils.rb:24:in `require_glob'
        from /home/furkan/Workspace/PetProject/lib/initializer.rb:84:in `block in require!'
        from /home/furkan/Workspace/PetProject/lib/initializer.rb:82:in `each'
        from /home/furkan/Workspace/PetProject/lib/initializer.rb:82:in `require!'
        from /home/furkan/Workspace/PetProject/lib/initializer.rb:61:in `require_models'
        from /home/furkan/Workspace/PetProject/lib/initializer.rb:31:in `run'
        from /home/furkan/Workspace/PetProject/lib/initializer.rb:89:in `<top (required)>'
        from /home/furkan/Workspace/PetProject/lib/application.rb:4:in `require_relative'
        from /home/furkan/Workspace/PetProject/lib/application.rb:4:in `<top (required)>'
        from ./bin/console:3:in `require_relative'
        from ./bin/console:3:in `<main>'
```

**Comment by jeremyevans** [comment]
You must be using an inflector or custom inflection rules  that pluralizes `quota` incorrectly, as Sequel's default does not do this:

```
$ bin/sequel -E 
Your database is stored in DB...
irb(main):001:1* class Quota < Sequel::Model
irb(main):002:0> end
I, [2021-06-18T07:11:25.490393 #1616]  INFO -- : (0.000003s) SELECT * FROM quotas LIMIT 1
=> nil
```

Try running `String.instance_method(:pluralize)`.  If that returns a result, you are using a custom inflector, and you need to fix the issue in that inflector, or remove the use of that inflector.
