### ISSUE TITLE
Concurrent drivers load exception

### ISSUE THREAD

**Issue by andsel** [jeremyevans/sequel#1785]
### Complete Description of Issue
Having multiple threads that concurrently load multiple divers and one of these is SyBase (`jconn4.jar`) then the `load_driver` method raises an exception at 
```
jruby-9.2.19.0/gems/sequel-5.48.0/lib/sequel/adapters/jdbc.rb:68
```
The problem doesn't happen at the SyBase driver loading, it happens for example duringn MySQL driver loading, but the problem manifests if the SyBase's driver is in the mix (in my experiments).
The base operation sequence that trigger the problem, is a concurrent execution of:
```ruby
require "drivers/mysql-connector-java-8.0.26.jar"
Sequel::JDBC.load_driver("Java::com.mysql.cj.jdbc.Driver")
```
The problem is not deterministic, it happens sometimes

### Simplest Possible Self-Contained Example Showing the Bug
I used the following Ruby script, launching it multiple times, it has a medium hit rate of 25%

```ruby
require "sequel"
require "sequel/adapters/jdbc"
require "java"

lock = java.util.concurrent.locks.ReentrantLock.new()

def load_driver_test(db_type, jar_path, driver_class_name, lock)
	sleep(rand(0.1..0.2))
	#begin
	#    lock.lock()
		require jar_path
	#ensure	
	#	lock.unlock()
	#end	
	begin
	#	lock.lock()
		driver_impl = Sequel::JDBC.load_driver(driver_class_name)
	rescue Sequel::AdapterNotFound => e
		puts "Problem loading driver #{db_type} #{e}, #{e.backtrace}"
	#ensure
	#    lock.unlock()	
	end	
end

th_mysql = Thread.new { load_driver_test("MySQL", "/tmp/drivers/mysql-connector-java-8.0.26.jar", "Java::com.mysql.cj.jdbc.Driver", lock) }
th_postgres = Thread.new { load_driver_test("Postgres", "/tmp/drivers/postgresql-42.2.23.jar", "Java::org.postgresql.Driver", lock) }
th_postgres2 = Thread.new { load_driver_test("Postgres", "/tmp/drivers/postgresql-42.2.23.jar", "Java::org.postgresql.Driver", lock) }
th_postgres3 = Thread.new { load_driver_test("Postgres", "/tmp/drivers/postgresql-42.2.23.jar", "Java::org.postgresql.Driver", lock) }
th_db2 = Thread.new { load_driver_test("DB2", "/tmp/drivers/db2jcc4.jar", "Java::com.ibm.db2.jcc.DB2Driver", lock) }
th_h2 = Thread.new { load_driver_test("MSSQL", "/tmp/drivers/h2-1.4.200.jar", "Java::org.h2.Driver", lock) }
th_sybase = Thread.new { load_driver_test("SyBase", "/tmp/drivers/jconn4.jar", "Java::com.sybase.jdbc4.jdbc.SybDriver", lock) }


puts "Shutting down"
th_mysql.join
th_postgres.join
th_postgres2.join
th_postgres3.join
th_sybase.join
th_db2.join
th_h2.join
puts "Terminated"
```

Some drivers could be downloaded from https://dbschema.com/databases.html but for SyBase has to be downloaded from SAP website.

The solution I've experimented in the scripts is to lock both `require` and `load_driver` or lock separately. This issue is related to https://github.com/logstash-plugins/logstash-integration-jdbc/issues/83

### Full Backtrace of Exception (if any)
```
Problem loading driver MySQL Java::com.mysql.cj.jdbc.Driver not loaded, [
"/home/andrea/.rvm/gems/jruby-9.2.19.0/gems/sequel-5.48.0/lib/sequel/adapters/jdbc.rb:68:in `load_driver'", 
"jruby_multi_threader_load.rb:17:in `load_driver_test'", 
"jruby_multi_threader_load.rb:25:in `block in jruby_multi_threader_load.rb'"]

Problem loading driver MSSQL Java::org.h2.Driver not loaded, [
"/home/andrea/.rvm/gems/jruby-9.2.19.0/gems/sequel-5.48.0/lib/sequel/adapters/jdbc.rb:68:in `load_driver'", 
"jruby_multi_threader_load.rb:17:in `load_driver_test'", 
"jruby_multi_threader_load.rb:34:in `block in jruby_multi_threader_load.rb'"]
```

**Comment by andsel** [comment]
I would agree with you if locking only the `require` part fix the problem, like in:
```ruby
begin
   lock.lock()
   require jar_path
ensure	
  lock.unlock()
end	

driver_impl = Sequel::JDBC.load_driver(driver_class_name)
```

but it's not enough, also the `load_driver' has to be locked, by the same lock used in the require.
Have you ever seen similar behavior with some drivers?

**Comment by andsel** [comment]
Thanks for looking at it, I understand you point.
In my use case I reached serialization with lock because can't control the threads from a Logstash plugin. 
However we have this issue as a future note if somebody else reach the same problem.
