### ISSUE TITLE
Unclear error if column_encryption is used without a key

### ISSUE THREAD

**Issue by rgalanakis** [jeremyevans/sequel#1815]
### Complete Description of Issue

We used the `column_encryption` plugin but had incorrectly registered a key. When using `enc.column :my_col` we got an ambiguous error:

```

Failure/Error:
    plugin :column_encryption do |enc|
      enc.column :admin_connection_url
    end

NoMethodError:
  undefined method `empty?' for nil:NilClass
```

It's because here: https://github.com/jeremyevans/sequel/blob/master/lib/sequel/plugins/column_encryption.rb#L359

`keys` is nil. I guess it should be checking `keys.nil? || keys.empty?`

(I have not verified this under the latest version since the descendants change is causing some issues with our models I haven't tracked down yet, but given the location of the exception, it seems like it's likely still present).

### Full Backtrace of Exception (if any)

```
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:342:in `initialize'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:589:in `new'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:589:in `column_encryption_cryptor'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:599:in `_encrypt_column'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:568:in `block (2 levels) in configure'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:567:in `each'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:567:in `block in configure'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:559:in `instance_exec'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/plugins/column_encryption.rb:559:in `configure'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-5.43.0/lib/sequel/model/base.rb:509:in `plugin'
# ./lib/webhookdb/organization.rb:11:in `<class:Organization>'
# ./lib/webhookdb/organization.rb:8:in `<top (required)>'
# ./lib/webhookdb/postgres.rb:99:in `require'
# ./lib/webhookdb/postgres.rb:99:in `block in require_models'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/set.rb:328:in `each_key'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/2.7.0/set.rb:328:in `each'
# ./lib/webhookdb/postgres.rb:98:in `require_models'
# ./lib/webhookdb/postgres.rb:149:in `block in load_models'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/semantic_logger-4.7.4/lib/semantic_logger/semantic_logger.rb:455:in `silence'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/semantic_logger-4.7.4/lib/semantic_logger/base.rb:234:in `silence'
# ./lib/webhookdb/postgres.rb:148:in `load_models'
# ./lib/webhookdb.rb:71:in `load_app'
# ./spec/spec_helper.rb:27:in `block in <top (required)>'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core.rb:98:in `configure'
# ./spec/spec_helper.rb:24:in `<top (required)>'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `require'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2112:in `load_file_handling_errors'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1574:in `block in requires='
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1574:in `each'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:1574:in `requires='
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:113:in `block in process_options_into'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:112:in `each'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:112:in `process_options_into'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration_options.rb:22:in `configure'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:132:in `configure'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:99:in `setup'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:86:in `run'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
# /Users/me/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
```

**Comment by jeremyevans** [comment]
I agree it would be a good idea to raise a nicer error message in this case of misuse.  I'll make this change shortly
