### ISSUE TITLE
Sequel SELECTs with zero (0) primary key after insert conflict (SQLite 3.34.1)

### ISSUE THREAD

**Issue by adam12** [jeremyevans/sequel#1845]
### Complete Description of Issue

Using Sequel with the `:insert_conflict` plugin and SQLite 3.34.1, I've noticed a very strange bug. The conflict is safely ignored during the first run of my example, but if you run it again, you'll notice that the `SELECT` after the conflict looks for a PK of `0`.

Command I used: `sequel -E sqlite://bug.sqlite3 bug.rb`

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB.create_table?(:widgets) do
  primary_key :id

  column :name, String
  column :version, Integer
  unique [:name, :version]
end

class Widget < Sequel::Model
  plugin :insert_conflict
end

2.times do
  Widget.new(name: "Foobar", version: 1).insert_conflict.save
end
```

### Full Backtrace of Exception (if any)

```
/usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1825:in `_save_refresh': Record not found (Sequel::NoExistingObject)
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1784:in `block (2 levels) in _save'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1036:in `around_create'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1777:in `block in _save'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1036:in `around_save'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1772:in `_save'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1486:in `block (2 levels) in save'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1938:in `block in checked_transaction'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/database/transactions.rb:258:in `_transaction'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/database/transactions.rb:233:in `block in transaction'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/database/connecting.rb:269:in `synchronize'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/database/transactions.rb:195:in `transaction'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1938:in `checked_transaction'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1486:in `block in save'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1926:in `checked_save_failure'
        from /usr/local/bundle/gems/sequel-5.54.0/lib/sequel/model/base.rb:1486:in `save'
        from bug.rb:14:in `block in <top (required)>'
        from bug.rb:13:in `times'
        from bug.rb:13:in `<top (required)>'
        from /usr/local/bundle/gems/sequel-5.54.0/bin/sequel:260:in `load'
        from /usr/local/bundle/gems/sequel-5.54.0/bin/sequel:260:in `block in <top (required)>'
        from /usr/local/bundle/gems/sequel-5.54.0/bin/sequel:260:in `each'
        from /usr/local/bundle/gems/sequel-5.54.0/bin/sequel:260:in `<top (required)>'
        from /usr/local/bundle/bin/sequel:25:in `load'
        from /usr/local/bundle/bin/sequel:25:in `<main>'
```

### SQL Log (if any)

First run (successful, also creates DB)

```
I, [2022-03-03T15:26:40.254223 #72469]  INFO -- : (0.002240s) PRAGMA foreign_keys = 1
I, [2022-03-03T15:26:40.254279 #72469]  INFO -- : (0.000010s) PRAGMA case_sensitive_like = 1
I, [2022-03-03T15:26:40.261808 #72469]  INFO -- : (0.000078s) SELECT sqlite_version()
I, [2022-03-03T15:26:40.272160 #72469]  INFO -- : (0.010183s) CREATE TABLE IF NOT EXISTS `widgets` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` varchar(255), `version` integer, UNIQUE (`name`, `version`))
I, [2022-03-03T15:26:40.276092 #72469]  INFO -- : (0.003635s) PRAGMA table_xinfo('widgets')
I, [2022-03-03T15:26:40.276897 #72469]  INFO -- : (0.000022s) BEGIN
I, [2022-03-03T15:26:40.290739 #72469]  INFO -- : (0.013687s) INSERT INTO `widgets` (`name`, `version`) VALUES ('Foobar', 1) ON CONFLICT DO NOTHING
I, [2022-03-03T15:26:40.290961 #72469]  INFO -- : (0.000076s) SELECT * FROM `widgets` WHERE `id` = 1
I, [2022-03-03T15:26:40.301324 #72469]  INFO -- : (0.010174s) COMMIT
I, [2022-03-03T15:26:40.301500 #72469]  INFO -- : (0.000023s) BEGIN
I, [2022-03-03T15:26:40.312637 #72469]  INFO -- : (0.010976s) INSERT INTO `widgets` (`name`, `version`) VALUES ('Foobar', 1) ON CONFLICT DO NOTHING
I, [2022-03-03T15:26:40.313330 #72469]  INFO -- : (0.000143s) SELECT * FROM `widgets` WHERE `id` = 1
I, [2022-03-03T15:26:40.322381 #72469]  INFO -- : (0.008971s) COMMIT
```

Second run, which triggers exception

```
I, [2022-03-03T15:26:41.087109 #72477]  INFO -- : (0.002101s) PRAGMA foreign_keys = 1
I, [2022-03-03T15:26:41.087165 #72477]  INFO -- : (0.000010s) PRAGMA case_sensitive_like = 1
I, [2022-03-03T15:26:41.089356 #72477]  INFO -- : (0.000053s) SELECT sqlite_version()
I, [2022-03-03T15:26:41.090875 #72477]  INFO -- : (0.001356s) CREATE TABLE IF NOT EXISTS `widgets` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` varchar(255), `version` integer, UNIQUE (`name`, `version`))
I, [2022-03-03T15:26:41.092728 #72477]  INFO -- : (0.001422s) PRAGMA table_xinfo('widgets')
I, [2022-03-03T15:26:41.093301 #72477]  INFO -- : (0.000013s) BEGIN
I, [2022-03-03T15:26:41.101889 #72477]  INFO -- : (0.008477s) INSERT INTO `widgets` (`name`, `version`) VALUES ('Foobar', 1) ON CONFLICT DO NOTHING
I, [2022-03-03T15:26:41.102240 #72477]  INFO -- : (0.000093s) SELECT * FROM `widgets` WHERE `id` = 0
I, [2022-03-03T15:26:41.106974 #72477]  INFO -- : (0.004608s) ROLLBACK
```

```
$ sqlite3 --version
3.34.1 2021-01-20 14:10:07 10e20c0b43500cfb9bbc0eaa061c57514f715d87238f4d835880cd846b9ealt1
```

```
$ gem list sqlite3 sequel

*** LOCAL GEMS ***

sqlite3 (1.4.2)
sequel (5.54.0)
```

```
$ ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [aarch64-linux]
```

**Comment by jeremyevans** [comment]
Because of the `ON CONFLICT DO NOTHING`, Sequel cannot know that the second query actually failed, because the database does not indicate an error (because you told it not to).  So Sequel assumes it succeeded.  SQLite must return 0 as the primary key in this place, so when Sequel tries to refresh the model after the insert, it fails.  This is different than the normal use, where the existing database row becomes the new record, which Sequel returns.

I think this condition should raise an error.  You tried to save a record and it didn't save.  Maybe your expectation is that it should return the values from the already saved record?  In my mind, that doesn't make sense, because it doesn't represent the model being saved.  Maybe we could detect this case and raise a different error?

Can you explain what you would like to happen in this case?

**Comment by adam12** [comment]
> Because of the `ON CONFLICT DO NOTHING`, Sequel cannot know that the second query actually failed, because the database does not indicate an error (because you told it not to). So Sequel assumes it succeeded. SQLite must return 0 as the primary key in this place, so when Sequel tries to refresh the model after the insert, it fails. This is different than the normal use, where the existing database row becomes the new record, which Sequel returns.

This makes sense.

> I think this condition should raise an error. You tried to save a record and it didn't save.

I agree.

> Maybe your expectation is that it should return the values from the already saved record? In my mind, that doesn't make sense, because it doesn't represent the model being saved.

Perhaps what's caused me to think this is a bug is because this behaviour is what appears to be happening during the first run of the example. The second time through the loop during the first run returns the object of conflict. It's only the second run of the example that causes the exception.

```
I, [2022-03-03T15:58:40.682250 #77488]  INFO -- : (0.002363s) PRAGMA foreign_keys = 1
I, [2022-03-03T15:58:40.682306 #77488]  INFO -- : (0.000011s) PRAGMA case_sensitive_like = 1
I, [2022-03-03T15:58:40.689367 #77488]  INFO -- : (0.000080s) SELECT sqlite_version()
I, [2022-03-03T15:58:40.703622 #77488]  INFO -- : (0.014035s) CREATE TABLE IF NOT EXISTS `widgets` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` varchar(255), `version` integer, UNIQUE (`name`, `version`))
I, [2022-03-03T15:58:40.709936 #77488]  INFO -- : (0.005764s) PRAGMA table_xinfo('widgets')
I, [2022-03-03T15:58:40.710686 #77488]  INFO -- : (0.000020s) BEGIN
I, [2022-03-03T15:58:40.725249 #77488]  INFO -- : (0.014430s) INSERT INTO `widgets` (`name`, `version`) VALUES ('Foobar', 1) ON CONFLICT DO NOTHING
I, [2022-03-03T15:58:40.725507 #77488]  INFO -- : (0.000078s) SELECT * FROM `widgets` WHERE `id` = 1
I, [2022-03-03T15:58:40.734491 #77488]  INFO -- : (0.008924s) COMMIT
#<Widget @values={:id=>1, :name=>"Foobar", :version=>1}>
I, [2022-03-03T15:58:40.734677 #77488]  INFO -- : (0.000023s) BEGIN
I, [2022-03-03T15:58:40.746278 #77488]  INFO -- : (0.011477s) INSERT INTO `widgets` (`name`, `version`) VALUES ('Foobar', 1) ON CONFLICT DO NOTHING
I, [2022-03-03T15:58:40.746529 #77488]  INFO -- : (0.000080s) SELECT * FROM `widgets` WHERE `id` = 1
I, [2022-03-03T15:58:40.757813 #77488]  INFO -- : (0.011196s) COMMIT
#<Widget @values={:id=>1, :name=>"Foobar", :version=>1}>
```

> Can you explain what you would like to happen in this case?

I had expected this to work in an UPSERT style, where the record of conflict is returned, but perhaps this is naive of me to think since the SQLite docs suggest that `ON CONFLICT DO NOTHING` is exactly that: it remains silent. I normally use PostgreSQL so this could just be my unfamiliarity with SQLite. I _thought_ this worked on PostgreSQL without issue, at least I remember it doing so.

**Comment by jeremyevans** [comment]
I tested on PostgreSQL (14.2) and SQLite (3.36.0), and the behavior for both is the same (different from the behavior you are seeing).  In my tests, the second save does not raise an error, and the resulting Widget does not have an id set.  I guess not raising an error also makes sense, since you are telling it to `DO NOTHING` on conflict.

I don't think there is a way to return the already existing record if you are using `DO NOTHING`.  What you could do is to update the existing record using the existing value instead of the excluded value.

Can you replicate this with a current or more recent version of SQLite?  My guess would be more recent versions of SQLite return NULL instead of 0 in this case (i.e. this was an SQLite bug that was fixed).

**Comment by adam12** [comment]
> I don't think there is a way to return the already existing record if you are using `DO NOTHING`. What you could do is to update the existing record using the existing value instead of the excluded value.

Using `insert_conflict(:replace)` is probably close enough to work around this for me.





> I tested on PostgreSQL (14.2) and SQLite (3.36.0), and the behavior for both is the same (different from the behavior you are seeing). In my tests, the second save does not raise an error, and the resulting Widget does not have an id set. I guess not raising an error also makes sense, since you are telling it to `DO NOTHING` on conflict.

Interesting! Thanks for checking.

> Can you replicate this with a current or more recent version of SQLite? My guess would be more recent versions of SQLite return NULL instead of 0 in this case (i.e. this was an SQLite bug that was fixed).

I suspect you are right, and I had considered it before submitting the PR. I just presumed it was a safe version to base the test on, as it's the current in Debian Bullseye, which is probably seeing quite a bit of use. I will try a new version to rule out it being a Sequel bug.

Thanks.

**Comment by adam12** [comment]
I believe it's related in part to the support for `RETURNING` in SQLite 3.35+.

If I run against SQLite 3.38.0 but with Sequel 5.45.0, it doesn't add the `RETURNING` clause and I see the exception. If I force Sequel to 5.54.0 with SQLite 3.38.0, then the `RETURNING` clause is added and everything works as expected.

This makes some sense because `RETURNING` support was added in Sequel 5.47.0.

It doesn't explain the original bug, but without the `RETURNING` clause, perhaps this behaviour is undefined and SQLite is acting differently internally (using some sort of cached INSERT in the first run) between versions.

I'd be OK if this was closed.
