### ISSUE TITLE
Prevent model aggregate methods from initialize model when placeholder_literalizer was cached

### ISSUE THREAD

**Issue by belousovAV** [jeremyevans/sequel#1847]
### Complete Description of Issue

When you call aggregate methods on model it does not initialize model internally until `placeholder_literalizer` was cached. After that each such call initializes the model in order to then call `#each` on it.
First, after caching the request, we change its further processing. Secondly, an extra object is created. And finally, we can neither override the `.call` method nor the `#each` method, although we probably shouldn't.

### Simplest Possible Self-Contained Example Showing the Bug

```RUBY
@db = Sequel.mock
@c = Class.new(Sequel::Model(@db[:items].with_extend{def supports_cte?(*) true end}.with_fetch(:id=>1).with_autoid(1).with_numrows(0)))
@c.define_singleton_method(:call) { |*| raise 'Should not be called for aggregate methods' }
@c.max(:id)
@c.max(:id)
@c.max(:id) # Boom Sequel::DatabaseError: RuntimeError: Should not be called for aggregate methods

Sequel::DatabaseError: RuntimeError: Should not be called for aggregate methods
    /sequel/spec/model/class_dataset_methods_spec.rb:12:in `block (3 levels) in <top (required)>'
    /sequel/lib/sequel/dataset/actions.rb:944:in `block in with_sql_each'
    /sequel/lib/sequel/adapters/mock.rb:178:in `_fetch'
    /sequel/lib/sequel/adapters/mock.rb:154:in `_execute'
    /sequel/lib/sequel/adapters/mock.rb:112:in `block in execute'
    /sequel/lib/sequel/connection_pool/threaded.rb:92:in `hold'
    /sequel/lib/sequel/database/connecting.rb:269:in `synchronize'
    /sequel/lib/sequel/adapters/mock.rb:112:in `execute'
    /sequel/lib/sequel/dataset/actions.rb:1093:in `execute'
    /sequel/lib/sequel/adapters/mock.rb:365:in `execute'
    /sequel/lib/sequel/adapters/mock.rb:340:in `fetch_rows'
    /sequel/lib/sequel/dataset/actions.rb:944:in `with_sql_each'
    /sequel/lib/sequel/dataset/actions.rb:954:in `with_sql_first'
    /sequel/lib/sequel/dataset/actions.rb:962:in `with_sql_single_value'
    /sequel/lib/sequel/dataset/placeholder_literalizer.rb:196:in `get'
    /sequel/lib/sequel/dataset/actions.rb:1021:in `_aggregate'
    /sequel/lib/sequel/dataset/actions.rb:457:in `max'
    /sequel/lib/sequel/model/plugins.rb:33:in `max'
    /sequel/spec/model/class_dataset_methods_spec.rb:16:in `block (2 levels) in <top (required)>'
```

```RUBY
@db = Sequel.mock
@c = Class.new(Sequel::Model(@db[:items].with_extend{def supports_cte?(*) true end}.with_fetch(:id=>1).with_autoid(1).with_numrows(0)))
@c.class_eval do
  def each(*)
    raise 'Should not be called'
  end
end
@c.max(:id)
@c.max(:id)
@c.max(:id) # Boom RuntimeError: Should not be called

RuntimeError: Should not be called
    /sequel/spec/model/class_dataset_methods_spec.rb:14:in `each'
    /sequel/lib/sequel/dataset/actions.rb:963:in `with_sql_single_value'
    /sequel/lib/sequel/dataset/placeholder_literalizer.rb:196:in `get'
    /sequel/lib/sequel/dataset/actions.rb:1021:in `_aggregate'
    /sequel/lib/sequel/dataset/actions.rb:457:in `max'
    /sequel/lib/sequel/model/plugins.rb:33:in `max'
    /sequel/spec/model/class_dataset_methods_spec.rb:18:in `block (3 levels) in <top (required)>'
    /sequel/spec/model/class_dataset_methods_spec.rb:17:in `times'
    /sequel/spec/model/class_dataset_methods_spec.rb:17:in `block (2 levels) in <top (required)>'
```

**Comment by jeremyevans** [comment]
Thanks for the patch!  I'll test and merge today.
