### ISSUE TITLE
Tactical eager loading breaks block passing for associations

### ISSUE THREAD

**Issue by rgalanakis** [jeremyevans/sequel#1893]
### Complete Description of Issue

When the `tactical_eager_loading` plugin is used, associations such as:

```ruby
class C < Sequel::Model(DB[:repro_c])
  one_to_many :d_s, class: "D", readonly: true do |ds|
    puts self.inspect
    puts ds.inspect
    puts caller
    D.dataset.where(c_id: id)
  end
end
```

begin to break using certain call styles. Specifically, the first is okay, but the second is not (see example for context):

```ruby
C.dataset.first.d_s # okay
C.dataset.first.b.c_s.first.d_s # errors
```

Normally, `self` is a model instance, so `id` is `self.id` and `ds` is the correct database:

```
#<C @values={:id=>1, :b_id=>1}>
#<Sequel::Postgres::Dataset: "SELECT * FROM \"repro_d\" WHERE (\"repro_d\".\"c_id\" = 1)">
```

However, running the second line, with `C.plugin(:tactical_eager_loading)` loaded, `self` is the *class* and `ds` has no conditions:

```
C
#<Sequel::Postgres::Dataset: "SELECT * FROM \"repro_d\"">
```

I will note that the stack trace is different as well. With the first style, or always without tactical eager loading:

```
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2489:in `_apply_association_options'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2518:in `_dataset'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2034:in `block in def_association_instance_methods'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2495:in `public_send'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2495:in `_associated_dataset'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2544:in `_load_associated_object_array'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2558:in `_load_associated_objects'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2681:in `load_associated_objects'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/plugins/tactical_eager_loading.rb:163:in `load_associated_objects'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2012:in `block in def_association_method'
```

And with the problematic call style and tactical eager loading:

```
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:633:in `block in associated_eager_dataset'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:577:in `block in cached_fetch'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:574:in `fetch'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:574:in `cached_fetch'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:630:in `associated_eager_dataset'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:642:in `eager_loading_dataset'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:747:in `block (2 levels) in placeholder_eager_loader'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/dataset/placeholder_literalizer.rb:127:in `process'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/dataset/placeholder_literalizer.rb:81:in `loader'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/dataset/placeholder_literalizer.rb:148:in `loader'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:746:in `block in placeholder_eager_loader'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:577:in `block in cached_fetch'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:574:in `fetch'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:574:in `cached_fetch'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:745:in `placeholder_eager_loader'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:313:in `eager_load_results'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:1910:in `eager_load_results'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2335:in `block in def_one_to_many'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:3614:in `perform_eager_load'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:3608:in `block in perform_eager_loads'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:3607:in `each'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:3607:in `map'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:3607:in `perform_eager_loads'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:3544:in `eager_load'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/plugins/tactical_eager_loading.rb:154:in `load_associated_objects'
/Users/rob/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sequel-5.58.0/lib/sequel/model/associations.rb:2012:in `block in def_association_method'
```

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
DB = Sequel.connect('postgres://dev:dev@localhost:22005/dev')
DB.drop_table?(:repro_b, cascade: true)
DB.drop_table?(:repro_c, cascade: true)
DB.drop_table?(:repro_d, cascade: true)
DB.create_table(:repro_b) do
  primary_key :id
end
DB.create_table(:repro_c) do
  primary_key :id
  foreign_key :b_id, :repro_b
end
DB.create_table(:repro_d) do
  primary_key :id
  foreign_key :c_id, :repro_c
end
class B < Sequel::Model(DB[:repro_b])
  one_to_many :c_s, class: 'C'
end
class C < Sequel::Model(DB[:repro_c])
  many_to_one :b, class: 'B'
  one_to_many :d_s, class: "D", readonly: true do |_ds|
    puts 'in association'
    puts self.inspect
    puts _ds.inspect
    puts caller
    D.dataset.where(c_id: id)
  end
end
class D < Sequel::Model(DB[:repro_d])
end
C.plugin(:tactical_eager_loading)
b_id = DB[:repro_b].insert({})
c_id = DB[:repro_c].insert({b_id:})
DB[:repro_d].insert({c_id:})
C.dataset.first.d_s
C.dataset.first.b.c_s.first.d_s
```

If the `C.plugin` line is commented out, the exception goes away.

I'll note that the example is contrived but I ran across this this in a very non-contrived situation (ie, something like `B.first.c_s.map(&:d_s).flatten`).

I'll also add that in 4+ years of using tactical eager loading this is the first bug I've noticed. TEL is absolutely a killer feature of Sequel. Thank you for it!

**Comment by jeremyevans** [comment]
This is expected behavior as the association you are using does not allow eager loading, and tactical eager loading will implicitly use eager loading (you'll get the same error if you try to eager load manually).

Pass the `allow_eager: false` flag to the `d_s` association, that will fix the issue.  The `allow_eager: false` is not set by default because Sequel doesn't know you are using the block in a way that would break eager loading, almost all association blocks are used in a way that works with eager loading, and it seems like a bad idea to disallow the use of eager loading by default just because an association block is used (significant negative effect on performance).

**Comment by rgalanakis** [comment]
Thanks Jeremy! That makes a lot of sense. It took a couple hours to diagnose and reproduce this issue. I don't have a great way off-hand to indicate a better error message or detect this case, as well. Plus, recognizing it was the TEL plugin came very late in the process, so docs wouldn't help (the the TEL docs allude to issues with association blocks). Hopefully it's rare for others to run into.

**Comment by jeremyevans** [comment]
I reviewed the tactical_eager_loading plugin documentation and couldn't see where this was mentioned, so I'll update the documentation to explain this issue.
