### ISSUE TITLE
Can't connect to MariaDB (via Mysql2 adapter)

### ISSUE THREAD

**Issue by tamvm** [jeremyevans/sequel#1966]
Hi all, 

### Complete Description of Issue
My Database version: 10.3.36-MariaDB-cll-lve
version_compile_os	Linux
version_ssl_library	OpenSSL 1.0.2k-fips  26 Jan 2017
Sequel version: 4.49.0
Mac M1 - version 12.3.1 (21E258) Monterey

Because there's no official MariaDB adapter so I need to use via mysql2 adapter. But I can't connect to my remote MariaDB. 

### Simplest Possible Self-Contained Example Showing the Bug
```
Sequel.connect(adapter: :mysql2, user: user, password: password, host: host)
```

### Full Backtrace of Exception (if any)
```
Traceback (most recent call last):
       16: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:58:in `kernel_load'
       15: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/bundler-2.3.16/lib/bundler/cli/exec.rb:58:in `load'
       14: from /Users/macbook/.asdf/installs/ruby/2.7.3/bin/irb:23:in `<top (required)>'
       13: from /Users/macbook/.asdf/installs/ruby/2.7.3/bin/irb:23:in `load'
       12: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       11: from (irb):16
       10: from (irb):17:in `rescue in irb_binding'
        9: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/core.rb:116:in `connect'
        8: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:68:in `connect'
        7: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:39:in `adapter_class'
        6: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:111:in `load_adapter'
        5: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:111:in `require'
        4: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:3:in `<top (required)>'
        3: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/sequel-4.49.0/lib/sequel/adapters/mysql2.rb:3:in `require'
        2: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `<top (required)>'
        1: from /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2.rb:36:in `require'
Sequel::AdapterNotFound (LoadError: dlopen(/Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle, 0x0009): symbol not found in flat namespace '_mysql_affected_rows' - /Users/macbook/.asdf/installs/ruby/2.7.3/lib/ruby/gems/2.7.0/gems/mysql2-0.5.3/lib/mysql2/mysql2.bundle)
```

Appreciate for any suggestions/help. 

Thank you,

**Comment by jeremyevans** [comment]
This looks like a mysql2 adapter issue, see https://github.com/brianmario/mysql2/issues?q=_mysql_affected_rows.  Try updating to mysql2 0.5.4.  If that doesn't work, file an issue with mysql2.  If you are able to connect using Mysql2 directly, but unable to connect via Sequel, then open a discussion on GitHub Discussions.
