### ISSUE TITLE
Validations of the 'validate_associated' plugin fail for non-integer primary-key columns

### ISSUE THREAD

**Issue by rolftimmermans** [jeremyevans/sequel#1968]
### Complete Description of Issue

On line 62 of the `validates_associated` plugin:
https://github.com/jeremyevans/sequel/blob/9a9f1119dfda85b10270763e5b0801b01cd401a7/lib/sequel/plugins/validate_associated.rb#L62
...there is a default value of `0` for foreign keys. This creates invalid queries if non-integer keys are being used. For example, we have many PostgreSQL-based projects that use `uuid` keys.

### Simplest Possible Self-Contained Example Showing the Bug

```
# Migrations
create_table :main_funds
  uuid :id, null: false, default: Sequel.function(:uuid_generate_v4), primary_key: true
end

create_table :main_fund_fiscal_numbers do
  uuid :id, null: false, default: Sequel.function(:uuid_generate_v4), primary_key: true
  uuid :main_fund_id, null: false, table: : main_funds, index: true, on_delete: :cascade
  text :country, null: false
  index %i[main_fund_id country], unique: true
end

# Models
class MainFund < Sequel::Model(:main_funds)
  plugin :auto_validations
  nested_attributes :fiscal_numbers, delete_blank: true, unmatched_pk: :create
  one_to_many :fiscal_numbers, class: :"FiscalNumber"
end

class FiscalNumber < Sequel::Model(:main_fund_fiscal_numbers)
  plugin :auto_validations
  many_to_one :main_fund
end

# Create a main fund + fiscal number
MainFund.create("fiscal_numbers_attributes" => [{"country"=>"AD"}])
```

### Full Backtrace of Exception (if any)

```
PG::UndefinedFunction: ERROR:  operator does not exist: uuid = integer
LINE 1: ...FROM "fund_fiscal_numbers" WHERE (("main_fund_id" = 0) AND (...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/rack-mini-profiler-3.0.0/lib/patches/db/pg.rb:110:in `exec'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/rack-mini-profiler-3.0.0/lib/patches/db/pg.rb:110:in `async_exec'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:17:in `block in log_connection_yield'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/sequel-rails-1.2.0/lib/sequel_rails/sequel/database/active_support_notification.rb:11:in `log_connection_yield'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:171:in `execute_query'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:159:in `block in execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:159:in `execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:532:in `_execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:555:in `check_database_errors'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:348:in `block in execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/database/connecting.rb:293:in `synchronize'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:348:in `execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/dataset/actions.rb:1162:in `execute'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/adapters/postgres.rb:651:in `fetch_rows'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/dataset/actions.rb:1003:in `with_sql_each'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/dataset/actions.rb:1011:in `with_sql_first'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/dataset/actions.rb:1019:in `with_sql_single_value'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/dataset/actions.rb:791:in `single_value!'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/dataset/actions.rb:112:in `count'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/validation_helpers.rb:294:in `block in validates_unique'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/validation_helpers.rb:276:in `each'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/validation_helpers.rb:276:in `validates_unique'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/auto_validations.rb:296:in `block in validate'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/auto_validations.rb:296:in `each'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/auto_validations.rb:296:in `validate'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1920:in `block in _valid?'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1047:in `around_validation'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1917:in `_valid?'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1642:in `valid?'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/validate_associated.rb:65:in `validate_associated_object'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/validate_associated.rb:48:in `block in delay_validate_associated_object'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/instance_hooks.rb:109:in `each'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/instance_hooks.rb:109:in `run_after_instance_hooks'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/plugins/instance_hooks.rb:64:in `after_validation'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1921:in `block in _valid?'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1047:in `around_validation'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1917:in `_valid?'
/Users/rolftimmermans/.gem/ruby/3.1.2/bundler/gems/sequel-675b9dd2801a/lib/sequel/model/base.rb:1642:in `valid?'
(irb):39:in `<top (required)>'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/workspace.rb:119:in `eval'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/workspace.rb:119:in `evaluate'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/context.rb:476:in `evaluate'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:577:in `block (2 levels) in eval_input'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:770:in `signal_status'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:558:in `block in eval_input'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:268:in `block (2 levels) in each_top_level_statement'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:250:in `loop'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:250:in `block in each_top_level_statement'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:249:in `catch'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb/ruby-lex.rb:249:in `each_top_level_statement'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:557:in `eval_input'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:491:in `block in run'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:490:in `catch'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:490:in `run'
/Users/rolftimmermans/.rubies/ruby-3.1.2/lib/ruby/3.1.0/irb.rb:419:in `start'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:70:in `start'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:19:in `start'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/railties-7.0.4/lib/rails/commands/console/console_command.rb:102:in `perform'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/railties-7.0.4/lib/rails/command/base.rb:87:in `perform'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/railties-7.0.4/lib/rails/command.rb:48:in `invoke'
/Users/rolftimmermans/.gem/ruby/3.1.2/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:9:in `require'
bin/rails:9:in `<main>'
```

### SQL Log (if any)

```
2022-11-21 15:51:19.699 CET [13062] STATEMENT:  SELECT count(*) AS "count" FROM "fund_fiscal_numbers" WHERE (("main_fund_id" = 0) AND ("country" = 'AD')) LIMIT 1
2022-11-21 15:51:38.778 CET [13126] ERROR:  operator does not exist: uuid = integer at character 78
2022-11-21 15:51:38.778 CET [13126] HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```

**Comment by jeremyevans** [comment]
It certainly seems better for the validate_associated plugin to use an object of the expected type in this case.  The use of `uuid` complicates things, because Sequel doesn't natively support that as a generic type.  However, I can probably handle that case, since `uuid` is reasonably common as a primary key type.  I'll try to fix this today.

**Comment by jeremyevans** [comment]
Actually, I think I can side step this problem.  Instead of setting a dummy value for the associated primary key column, just delete errors related to the key in the associated object before copying the errors from the associated object to the current object. This appears to pass tests, and is much simpler than dealing with various primary key types.

Can you try this patch?:

```diff
diff --git a/lib/sequel/plugins/validate_associated.rb b/lib/sequel/plugins/validate_associated.rb
index 8186a492e..68430d3f5 100644
--- a/lib/sequel/plugins/validate_associated.rb
+++ b/lib/sequel/plugins/validate_associated.rb
@@ -2,7 +2,7 @@

 module Sequel
   module Plugins
-    # The validates_associated plugin allows you to validate associated
+    # The validate_associated plugin allows you to validate associated
     # objects.  It also offers the ability to delay the validation of
     # associated objects until the current object is validated.
     # If the associated object is invalid, validation error messages
@@ -54,22 +54,24 @@ module Sequel
           return if reflection[:validate] == false
           association = reflection[:name]
           if (reflection[:type] == :one_to_many || reflection[:type] == :one_to_one) && (key = reflection[:key]).is_a?(Symbol) && !(pk_val = obj.values[key])
-            # There could be a presence validation on the foreign key in the associated model,
-            # which will fail if we validate before saving the current object.  If there is
-            # no value for the foreign key, set it to the current primary key value, or a dummy
-            # value of 0 if we haven't saved the current object.
             p_key = pk unless pk.is_a?(Array)
-            obj.values[key] = p_key || 0
-            key = nil if p_key
-          end
-          obj.errors.full_messages.each{|m| errors.add(association, m)} unless obj.valid?
-          if key && !pk_val
-            # If we used a dummy value of 0, remove it so it doesn't accidently remain.
-            obj.values.delete(key)
+            if p_key
+              obj.values[key] = p_key
+            else
+              ignore_key_errors = true
+            end
           end
+
+          # Ignore errors on the key column in the associated object. This column
+          # will be set when saving to a presumably valid value using a column
+          # in the current object (which may not be available until after the current
+          # object is saved).
+          obj.valid?
+          obj.errors.delete(key) if ignore_key_errors
+          obj.errors.full_messages.each{|m| errors.add(association, m)}
+          nil
         end
       end
     end
   end
 end
-
```

**Comment by jeremyevans** [comment]
I think the issue with the uniqueness check is that you don't may not be able to determine the value needed for the uniqueness query at the point the uniqueness query is sent.  For example, if the value to set in the associated object isn't determined until saving the current object, there is no way to validate uniqueness of the associated object in advance of saving the current object.

In your case, one possible solution without any patches to Sequel is to generate the uuid in the current object before validation.  Doing that would avoid this issue, since the uuid would be used instead of 0.  That also gets the uniqueness check in the associated object.

I still plan to fix this issue with a patch similar to above.

**Comment by rolftimmermans** [comment]
I understand and agree. I would be very happy with the above patch!

In this specific situation (which I believe the above code snippet is a simple reproduction of) I can observe in the log that the referencing row (in `main_funds`) is created before its association. So theoretically the primary key should be known and assigned to the foreign column `main_fund_id` in `main_funds_fiscal_numbers`, right? Is that supposed to happen, or could it be I'm also doing something wrong that prevents this?

**Comment by jeremyevans** [comment]
You aren't doing something wrong, but you are missing that validation for both the current and associated objects happens before the current object is saved and the `main_fund_id` is available.  Since you are using uuids and not autoincrementing integers, generating a uuid for the `main_fund_id` in `before_validation` would be a another way to solve your problem.  Note that skipping the uniqueness check should never cause problems in your case, unless you are somehow generating duplicate uuids.

**Comment by rolftimmermans** [comment]
Right! Thanks for the clarification & the fix!
