### ISSUE TITLE
Migrations not working for me on Ruby 3 on M1 Mac

### ISSUE THREAD

**Issue by SpyMachine** [jeremyevans/sequel#2029]
### Complete Description of Issue

The following fails for me on my M1 mac only when I upgrade to Ruby 3 (any version). It works on Ruby 2.7 and it also works if I run in a docker container of Ruby 3. Not sure where the issue is exactly.

### Simplest Possible Self-Contained Example Showing the Bug

```
#!/usr/bin/env ruby

require 'sequel'

db = Sequel.sqlite
sql = 'CREATE TABLE IF NOT EXISTS test ( id integer NOT NULL PRIMARY KEY AUTOINCREMENT );'
db.run(sql)
Sequel.extension :migration
Sequel::Migrator.run(db, File.join(__dir__, 'migrations'))
```

### Full Backtrace of Exception (if any)

```
/Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/dataset/misc.rb:318:in `initialize_copy': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from <internal:kernel>:48:in `clone'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/dataset/query.rb:85:in `clone'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/dataset/query.rb:254:in `from'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/database/dataset.rb:66:in `from'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/extensions/migration.rb:613:in `schema_dataset'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/extensions/migration.rb:453:in `initialize'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/extensions/migration.rb:517:in `initialize'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/extensions/migration.rb:401:in `new'
	from /Users/gkuruc/.rvm/gems/ruby-3.2.1/gems/sequel-5.7.1/lib/sequel/extensions/migration.rb:401:in `run'
```

### Ruby Version

3.0.5

### Sequel Version

5.7.1

**Comment by jeremyevans** [comment]
Please try using the current version of Sequel. Sequel 5.7.1 is over 5 years old at this point.

**Comment by SpyMachine** [comment]
🤦 I genuinely thought I was adding the latest version I must have missed the 6 when I was typing it into the Gemfile...sorry.
