### ISSUE TITLE
wrong number of arguments (given 1, expected 0) (ArgumentError) on JRuby 9.4.2.0 & 9.4.3.0

### ISSUE THREAD

**Issue by malcolm-pro** [jeremyevans/sequel#2053]
### Complete Description of Issue

It looks like Sequel + JRuby 9.4.x is having problems with `.clone` on instances of `Sequel::Postgres::JSONBHash` (ie hashes returned from JSONB columns). I've tested the same code with Ruby 2.6, 3.1, and JRuby 9.3.x, and none of those versions exhibit this issue.

I'm not sure if this is a bug in Sequel or a regression in JRuby.

### Simplest Possible Self-Contained Example Showing the Bug

SQL
```
# create table test_table ( jsonb_data jsonb );
# insert into test_table (jsonb_data) values ('{"key1":{"nested_key":"value"}, "key2":"value2"}');
```

jirb
```
> db_conn = <initialize connection>
> db_conn["SELECT jsonb_data from test_table limit 1"].first[:jsonb_data].clone
/opt/jruby/lib/ruby/stdlib/delegate.rb:226:in `initialize_clone': `clone': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

### Full Backtrace of Exception (if any)

```
/opt/jruby/lib/ruby/stdlib/delegate.rb:226:in `initialize_clone': `clone': wrong number of arguments (given 1, expected 0) (ArgumentError)
        from org/jruby/RubyKernel.java:2202:in `clone'
        from (irb):43:in `evaluate'
        from org/jruby/RubyKernel.java:1159:in `eval'
        from org/jruby/RubyKernel.java:1601:in `loop'
        from org/jruby/RubyKernel.java:1308:in `catch'
        from org/jruby/RubyKernel.java:1308:in `catch'
        from /opt/jruby/lib/ruby/gems/shared/gems/irb-1.4.2/exe/irb:11:in `<main>'
        from org/jruby/RubyKernel.java:1105:in `load'
        from /opt/jruby/bin/irb:23:in `<main>'
        from org/jruby/RubyKernel.java:1105:in `load'
        from /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:23:in `run'
        from /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.4.14/lib/bundler/cli.rb:492:in `exec'
        from /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/jruby/lib/ruby/gems/shared/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
```

### Ruby Version

JRuby 9.4.x

### Sequel Version

5.69.0

**Comment by jeremyevans** [comment]
This is a bug in JRuby.  Here's a minimal example:

```ruby
require 'delegate'
DelegateClass(Hash).new({}).clone
```

Please let me know whether you plan to report it to JRuby.  If you don't plan on doing so, I can.

**Comment by malcolm-pro** [comment]
Submitted, thanks for investigating!
