### ISSUE TITLE
NoMethodError: super: no superclass method `untaint'

### ISSUE THREAD

**Issue by StephanieSunshine** [jeremyevans/sequel#2186]
### Complete Description of Issue

Hi I'm trying to use the Sequel gem with TruffleRuby, but lacking success. From within `pry`, I am getting a LoadError when I try to require it. I have added sequel to my Gemfile and `bundle install`. This is not a Rails project.

```ruby
NoMethodError: super: no superclass method `untaint'
from /Users/stephanie/.rvm/gems/truffleruby-23.1.1/gems/sequel-4.49.0/lib/sequel/core.rb:228:in `block in require'
Caused by LoadError: cannot load such file -- sequel
```

### Simplest Possible Self-Contained Example Showing the Bug

```ruby
stephanie@Laputa> pry
[1] pry(main)> require "sequel"
NoMethodError: super: no superclass method `untaint'
from /Users/stephanie/.rvm/gems/truffleruby-23.1.1/gems/sequel-4.49.0/lib/sequel/core.rb:228:in `block in require'
Caused by LoadError: cannot load such file -- sequel
from <internal:core> core/kernel.rb:236:in `gem_original_require'
[2] pry(main)>

stephanie@Laputa> ruby -v
truffleruby 23.1.1, like ruby 3.2.2, Oracle GraalVM Native [aarch64-darwin]

stephanie@Laputa> cat Gemfile
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in library.gemspec
gemspec

gem 'pry', '~> 0.14.2'

gem 'sequel', '~> 4.36'
```

### Ruby Version

truffleruby 23.1.1, like ruby 3.2.2, Oracle GraalVM Native [aarch64-darwin]

### Sequel Version

4.36

**Comment by StephanieSunshine** [comment]
When adding Sequel to my Gemfile, I obtained the wrong version number. I thought I had pulled the gem line from Rubygems. Upon verifying if their gem line was correct, I went back to the Rubygems page and found that the correct version is 5.82, not 4.36. I'm not sure where I got the 4.36 version now, but this is working and can be closed.
