### ISSUE TITLE
Sequel::DatabaseDisconnectError: PQconsumeInput() SSL connection has been closed unexpectedly occasionally when running SQL queries

### ISSUE THREAD

**Issue by siddharth7** [jeremyevans/sequel#2200]
### Complete Description of Issue

We are running a backend service that occasionally throws `Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly` on running SQL queries on an endpoint. The services are hosted on AWS ECS Fargate and a Postgres instance on AWS RDS with a RDS proxy in between. I don't see any exceptions or failures on the RDS/proxy side.

This is a how a database connection is setup in the app initializers
```
DB = Sequel.connect(
       Config.database_url,
       pool_class: :threaded,
       max_connections: 4,
       pool_timeout: 10,
       after_connect: lambda do |conn|
         application_name = "web"
         conn.execute "SET statement_timeout = '10s'"
         conn.execute "SET application_name = 'app'"
       end,
     )
```

One of the example endpoint where we experience this issue is a basic GET API to fetch timestamp from DB
```
endpoint do
    http_path "/health/database"
    http_method :get
    schema Health::Schemas::Database

    operation do
      timestamp = DB["SELECT NOW() AS timestamp"].first[:timestamp]

      {
        timestamp: timestamp,
      }
    end
  end
 ```
 
 Could it be a missing sequel config?

### Simplest Possible Self-Contained Example Showing the Bug

It happens occasionally so we are unable to provide a definitive way to reproduce this issue.

### Full Backtrace of Exception (if any)

```
Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() SSL connection has been closed unexpectedly
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:171:in `exec'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:171:in `block in execute_query'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:171:in `execute_query'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:159:in `block in execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:136:in `check_disconnect_errors'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:159:in `execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:532:in `_execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:348:in `block (2 levels) in execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:555:in `check_database_errors'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:348:in `block in execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/connection_pool/threaded.rb:92:in `hold'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/database/connecting.rb:286:in `synchronize'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:348:in `execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/dataset/actions.rb:1189:in `execute'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/adapters/postgres.rb:651:in `fetch_rows'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/dataset/actions.rb:1032:in `with_sql_each'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/dataset/actions.rb:1040:in `with_sql_first'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/dataset/actions.rb:782:in `single_record!'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/dataset/actions.rb:770:in `single_record'
/usr/local/bundle/gems/sequel-5.82.0/lib/sequel/dataset/actions.rb:220:in `first'

### SQL Log (if any)

_No response_

### Ruby Version

3.3.3

### Sequel Version

5.82.0

**Comment by jeremyevans** [comment]
This is expected if the TCP or SSL session is disconnected.  It most commonly happens with firewalls closing connections, but maybe the RDS proxy is closing connections without logging?  Sequel does not automatically retry queries in most cases as it isn't safe to do so.  You can look into the connection_validator extension if you want to make sure a connection is valid before attempting to use it (https://sequel.jeremyevans.net/rdoc-plugins/files/lib/sequel/extensions/connection_validator_rb.html).
