### ISSUE TITLE
Issue with new sharded timed queue connection pool

### ISSUE THREAD

**Issue by mscrivo** [jeremyevans/sequel#2226]
### Complete Description of Issue

After upgrading from Sequel 5.84 -> 5.85, our application started failing with `Sequel::PoolTimeout`'s, whereas we didn't experience any before with the old sharded threaded connection pool. As soon as we set the pool type back to `sharded_threaded` while still using 5.85, the issue went away.

Some details about our setup:

We have various workers (sidekiq, shoryuken, etc) that are set to run with # threads = Sequel's max_connections and various puma servers where # of threads <= Sequel's max_connections. This setup was working great with 5.84 and we never saw any pool timeouts, but both workers and webs started throwing this error after the upgrade.

We have 2 servers setup in Sequel, a primary & replica.

Let me know if there are any other details that are helpful to troubleshoot.

### Simplest Possible Self-Contained Example Showing the Bug

I have not yet been able to come up with a simple reproduction, but am in the process of trying and will update the issue as soon as I have it.

### Full Backtrace of Exception (if any)

```
/home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/connection_pool/sharded_timed_queue.rb:312:in `acquire': timeout: 5.0, server: replica (Sequel::PoolTimeout)
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/extensions/connection_validator.rb:106:in `block in acquire'
	from <internal:numeric>:237:in `times'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/extensions/connection_validator.rb:105:in `acquire'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/extensions/connection_expiration.rb:83:in `block in acquire'
	from <internal:numeric>:237:in `times'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/extensions/connection_expiration.rb:82:in `acquire'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/connection_pool/sharded_timed_queue.rb:127:in `hold'
	from /home/affinity/ruby/patches/sequel_datadog.rb:10:in `synchronize'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/adapters/postgres.rb:824:in `literal_string_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:60:in `literal_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1192:in `block in expression_list_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1190:in `each'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1190:in `expression_list_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:311:in `array_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1350:in `literal_array_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:79:in `literal_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:414:in `complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/adapters/shared/postgres.rb:1851:in `complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/model/associations.rb:3077:in `complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/sql.rb:112:in `to_s_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1395:in `literal_expression_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:67:in `literal_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:446:in `block in complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:444:in `each'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:444:in `complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/adapters/shared/postgres.rb:1851:in `complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/model/associations.rb:3077:in `complex_expression_sql_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/sql.rb:112:in `to_s_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1395:in `literal_expression_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:67:in `literal_append'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:1641:in `select_where_sql'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:281:in `select_sql'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/sql.rb:177:in `sql'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel_pg-1.17.1/lib/sequel_pg/sequel_pg.rb:81:in `each'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/extensions/async_thread_pool.rb:390:in `block in define_async_method'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/actions.rb:51:in `block in all'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/actions.rb:1105:in `_all'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/dataset/actions.rb:51:in `all'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sequel-5.85.0/lib/sequel/extensions/async_thread_pool.rb:390:in `block in define_async_method'
	from /home/affinity/ruby/lib/consumers/base.rb:611:in `trackers_dependent_on'
	from /home/affinity/ruby/lib/consumers/base.rb:660:in `block in run'
	from <internal:kernel>:187:in `loop'
	from /home/affinity/ruby/lib/consumers/base.rb:656:in `run'
	from /home/affinity/ruby/lib/consumers/base.rb:639:in `block in run!'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/trace_operation.rb:206:in `block in measure'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/span_operation.rb:150:in `measure'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/trace_operation.rb:206:in `measure'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/tracer.rb:391:in `start_span'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/tracer.rb:158:in `block in trace'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/context.rb:45:in `activate!'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing/tracer.rb:157:in `trace'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/datadog-2.3.0/lib/datadog/tracing.rb:30:in `trace'
	from /home/affinity/ruby/lib/consumers/base.rb:634:in `run!'
	from /home/affinity/ruby/lib/consumers/base.rb:213:in `block in process_tracker'
	from /home/affinity/ruby/gems/log4a/lib/log4a/logger/logger_factory_impl.rb:77:in `create_scoped'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11589/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11589/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11589/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'
	from /home/affinity/ruby/gems/log4a/lib/log4a/logger/logger_factory.rb:69:in `create_scoped'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11589/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11589/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11589/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'
	from /home/affinity/ruby/lib/consumers/base.rb:197:in `process_tracker'
	from /home/affinity/ruby/lib/consumers/base.rb:232:in `block (2 levels) in run_super_unsharded_round!'
	from /home/affinity/vendor/bundle/ruby/3.3.0/gems/redlock-2.0.6/lib/redlock/client.rb:91:in `lock'
	from /home/affinity/ruby/lib/consumers/base.rb:229:in `block in run_super_unsharded_round!'
	from /home/affinity/ruby/lib/consumers/base.rb:228:in `each'
	from /home/affinity/ruby/lib/consumers/base.rb:228:in `run_super_unsharded_round!'
	from /home/affinity/bin/run_super_unsharded_consumer.rb:31:in `block in main'
	from <internal:kernel>:187:in `loop'
	from /home/affinity/bin/run_super_unsharded_consumer.rb:28:in `main'
	from bin/monitor.rb:34:in `<main>'
```

### Ruby Version

3.3.5

### Sequel Version

5.85

**Comment by jeremyevans** [comment]
Thank you for the report.  I'm not sure if it is possible, but if you could put together a reproducible example, that would certainly assist in troubleshooting.  It is possible to just revert the change, but the timed_queue approach is definitely be preferable in the long run. If there is a bug in the sharded version of timed_queue, I want to fix it.  Whatever bug is in sharded_timed_queue, it isn't exposed by Sequel's tests, and Sequel uses basically the same tests for sharded_timed_queue that it uses for sharded_threaded.

**Comment by jeremyevans** [comment]
Here is a reproducer I put together, using things I saw in your backtrace:

```ruby
require 'sequel'

opts = {:user=>'sequel_test', :servers=>{read_only: {}}}
opts[:pool_class] = :sharded_threaded if ARGV.include?('sharded_threaded')
opts[:max_connections] = 8 if ARGV.include?('8')
opts[:pool_timeout] = 30 if ARGV.include?('30')
DB = Sequel.postgres(opts)

DB.extension :connection_validator
DB.extension :connection_expiration
DB.extension :async_thread_pool

8.times.map do |i|
  Thread.new do
    1_000_000.times do |j|
      print '.' if j % 10_000 == 0
      r = rand
      if r < 0.01
        begin
          DB.get{pg_terminate_backend(pg_backend_pid.function)}
        rescue Sequel::DisconnectDatabaseError
        end
      elsif r < 0.1
        DB.get{pg_sleep(0.01)}
      else
        DB.get('a')
      end
    end
  end
end.map(&:join)
```

However, this reproduces the issue both for sharded_time_queue and sharded_threaded.  This isn't a bug in either pool, though, it just means things took longer than the allowed timeout.  

With max_connections = 8, there are no errors (expected as there are not more threads than connections).

With higher values for pool_timeout, errors became much less frequent.  Even with 30 I did see errors with both connection pools, though.

So it doesn't look like the pool is broken, you may just not be waiting long enough. If it's possible to run your application on JRuby, you may want to try that, as it generally handles concurrency better than CRuby.

Increasing the number of max connections allowed may also fix things.

Unfortunately, I still do not have an understanding of why this only affects sharded_timed_queue and not sharded_threaded in your application.

**Comment by mscrivo** [comment]
Thanks for spending the time on that repro! tbh, I'm struggling to find a way to repro this in our local development environment. It's all seemingly working fine no matter how many concurrent requests I make, so whatever the difference is, it's currently eluding me.

JRuby is not an option for us. Will continue to investigate.

**Comment by mscrivo** [comment]
@jeremyevans I've tried and I cannot reproduce this issue at all outside of the issue we ran into when deployed to our test/qa envs. I will have to find time to deploy it there again and try debugging live. In the mean time, feel free to close this until I have more information.

**Comment by jeremyevans** [comment]
OK.  Please let me know what you find out.  Thanks!

**Comment by jeremyevans** [comment]
Looks like you were using both connection_validator and connection_expiration, so it does seem likely to be related. Definitely give it a try and see if the problem has been resolved. My example code in this issue didn't cause the problem, because it didn't raise a disconnect error during the connection_validator/connection_expiration override of acquire.
