### ISSUE TITLE
Mismatched number of placeholders (0) and placeholder arguments (1) when using placeholder array

### ISSUE THREAD

**Issue by wgq91here** [jeremyevans/sequel#957]
My Code:

```
filter = []
@search_fields.each { |f, v|
      if (f.to_s.include? '_date') && (v.to_s.length > 0)
        case fields["#{f}_operator"]
          when '='
            filter.push Sequel.like(Sequel.qualify(:projects, f), '%' + v.to_s + '%')
          when '<='
            filter.push "#{f} <= '" + fields[f.to_s] + "'"
          when '>='
            filter.push "#{f} >= '" + fields[f.to_s] + "'"
        end
      else
        if v.to_s.length > 0
          filter.push Sequel.like(Sequel.qualify(:projects, f), '%' + v + '%')
        end
      end
    }

@projects = Project.where(filter).eager_graph(:factory).all
```

and Error!

In filter,have String and Sequel Object,and they sort is Object must first.If String is first , that is error!

```
Sequel::Error - Mismatched number of placeholders (0) and placeholder arguments (1) when using placeholder array:
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:674:in `block in placeholder_literal_string_sql_append'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:668:in `loop'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:668:in `placeholder_literal_string_sql_append'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/sql.rb:107:in `to_s_append'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:1192:in `literal_expression_append'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:85:in `literal_append'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:1429:in `select_where_sql'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/sql.rb:230:in `select_sql'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/actions.rb:139:in `each'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/actions.rb:45:in `block in all'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/actions.rb:857:in `_all'
	/usr/local/rvm/gems/ruby-2.0.0-p451/gems/sequel-4.19.0/lib/sequel/dataset/actions.rb:45:in `all'
	/home/ergongqu/app/controllers/projects.rb:35:in `block (2 levels) in <top (required)>'
```

My Problem Solving is 

<code>
filter = filter.sort_by { |x| x.class.to_s }
</code>

Why?

**Comment by jeremyevans** [comment]
If the string is the first argument, then it is considered to be a placeholder literal string, and the remaining arguments are the arguments for the placeholders.

You should change your code to modify the dataset, instead of trying to pass a bunch of filters in a single call:

```ruby
ds = Project.eager_graph(:factory)
@search_fields.each do |f, v|
  if v.to_s.length > 0
    if f.to_s.include?('_date')
      case fields["#{f}_operator"]
      when '='
        ds = ds.where(Sequel.like(Sequel.qualify(:projects, f), '%' + v.to_s + '%'))
      when '<='
        ds = ds.where("#{f} <= '" + fields[f.to_s] + "'")
      when '>='
        ds = ds.where("#{f} >= '" + fields[f.to_s] + "'")
      end
    else
      ds = ds.where(Sequel.like(Sequel.qualify(:projects, f), '%' + v + '%'))
    end
  end
end
@projects = ds.all
```

Also, if `@search_fields` or `fields` relies on any user input, there's probably a security issue in the above code.

**Comment by wgq91here** [comment]
Thanks
