### ISSUE TITLE
How to properly run tests?

### ISSUE THREAD

**Issue by janko-m** [jeremyevans/sequel#963]
First of all, thank you for this awesome library, I really hope that I will be able to have opportunity to use it in a job in near future. For now I can just play with it in my pet projects.

I have a problem figuring out how to properly run tests for the Sequel codebase. I tried many ways, but each one has a different problem:

1. `$ bundle exec rspec` (I would really like if this one worked)

  ```
  /Users/janko/Code/temp/clones/sequel/spec/adapters/spec_helper.rb:20:in `<top (required)>': undefined method `cache_anonymous_models=' for Sequel:Module (NoMethodError)
    from /Users/janko/Code/temp/clones/sequel/spec/adapters/db2_spec.rb:3:in `require'
    from /Users/janko/Code/temp/clones/sequel/spec/adapters/db2_spec.rb:3:in `<top (required)>'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `load'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `each'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:97:in `setup'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:85:in `run'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:70:in `run'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/exe/rspec:4:in `<top (required)>'
    from /Users/janko/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
    from /Users/janko/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
  ```

2. `$ rspec`

  ```
  /Users/janko/Code/temp/clones/sequel/lib/sequel/database/connecting.rb:57:in `connect': Sequel::Database.connect takes either a Hash or a String, given: nil (Sequel::Error)
    from /Users/janko/Code/temp/clones/sequel/lib/sequel/core.rb:95:in `connect'
    from /Users/janko/Code/temp/clones/sequel/spec/adapters/spec_helper.rb:75:in `<top (required)>'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/janko/Code/temp/clones/sequel/spec/adapters/db2_spec.rb:3:in `<top (required)>'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `load'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `each'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:97:in `setup'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:85:in `run'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:70:in `run'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:38:in `invoke'
    from /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rspec-core-3.2.1/exe/rspec:4:in `<top (required)>'
    from /Users/janko/.rbenv/versions/2.2.0/bin/rspec:23:in `load'
    from /Users/janko/.rbenv/versions/2.2.0/bin/rspec:23:in `<main>'
  ```

3. `$ bundle exec rake spec`

  ```
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.8.2/lib/bundler/rubygems_integration.rb:261:in `block in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from /Users/janko/.rbenv/versions/2.2.0/bin/rake:22:in `<main>'
  ```

4. `$ rake spec` (this one works, but I get a *lot* of warnings)

  ```
    /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake.rb:24: warning: already initialized constant Rake::VERSION
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake.rb:24: warning: previous definition of VERSION was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::MAJOR
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/version.rb:3: warning: previous definition of MAJOR was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::MINOR
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/version.rb:3: warning: previous definition of MINOR was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::BUILD
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/version.rb:3: warning: previous definition of BUILD was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::OTHER
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/version.rb:3: warning: previous definition of OTHER was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/version.rb:5: warning: already initialized constant Rake::Version::NUMBERS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/version.rb:5: warning: previous definition of NUMBERS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake.rb:31: warning: already initialized constant RAKEVERSION
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake.rb:31: warning: previous definition of RAKEVERSION was here
  WARNING: Possible conflict with Rake extension: String#ext already exists
  WARNING: Possible conflict with Rake extension: String#pathmap already exists
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/early_time.rb:20: warning: already initialized constant Rake::EARLY
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/early_time.rb:20: warning: previous definition of EARLY was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/late_time.rb:16: warning: already initialized constant Rake::LATE
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/late_time.rb:16: warning: previous definition of LATE was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/alt_system.rb:34: warning: already initialized constant Rake::AltSystem::WINDOWS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/alt_system.rb:34: warning: previous definition of WINDOWS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/linked_list.rb:100: warning: already initialized constant Rake::LinkedList::EMPTY
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/linked_list.rb:100: warning: previous definition of EMPTY was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/scope.rb:40: warning: already initialized constant Rake::Scope::EMPTY
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/scope.rb:40: warning: previous definition of EMPTY was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_utils.rb:9: warning: already initialized constant FileUtils::RUBY
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:9: warning: previous definition of RUBY was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_utils.rb:100: warning: already initialized constant FileUtils::LN_SUPPORTED
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils.rb:100: warning: previous definition of LN_SUPPORTED was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:16: warning: already initialized constant Rake::FileUtilsExt::DEFAULT
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_utils_ext.rb:16: warning: previous definition of DEFAULT was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:44: warning: already initialized constant Rake::FileList::ARRAY_METHODS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:44: warning: previous definition of ARRAY_METHODS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:48: warning: already initialized constant Rake::FileList::MUST_DEFINE
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:48: warning: previous definition of MUST_DEFINE was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:52: warning: already initialized constant Rake::FileList::MUST_NOT_DEFINE
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:52: warning: previous definition of MUST_NOT_DEFINE was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:56: warning: already initialized constant Rake::FileList::SPECIAL_RETURN
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:56: warning: previous definition of SPECIAL_RETURN was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:62: warning: already initialized constant Rake::FileList::DELEGATING_METHODS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:62: warning: previous definition of DELEGATING_METHODS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:374: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PATTERNS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:374: warning: previous definition of DEFAULT_IGNORE_PATTERNS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/file_list.rb:380: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PROCS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/file_list.rb:380: warning: previous definition of DEFAULT_IGNORE_PROCS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/promise.rb:11: warning: already initialized constant Rake::Promise::NOT_SET
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/promise.rb:11: warning: previous definition of NOT_SET was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:13: warning: already initialized constant Rake::CommandLineOptionError
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:13: warning: previous definition of CommandLineOptionError was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:38: warning: already initialized constant Rake::Application::DEFAULT_RAKEFILES
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:38: warning: previous definition of DEFAULT_RAKEFILES was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/application.rb:787: warning: already initialized constant Rake::Application::FIXNUM_MAX
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/application.rb:787: warning: previous definition of FIXNUM_MAX was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/task_arguments.rb:97: warning: already initialized constant Rake::EMPTY_TASK_ARGS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/task_arguments.rb:97: warning: previous definition of EMPTY_TASK_ARGS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/invocation_chain.rb:54: warning: already initialized constant Rake::InvocationChain::EMPTY
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/invocation_chain.rb:54: warning: previous definition of EMPTY was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/backtrace.rb:3: warning: already initialized constant Rake::Backtrace::SYS_KEYS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/backtrace.rb:3: warning: previous definition of SYS_KEYS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/backtrace.rb:4: warning: already initialized constant Rake::Backtrace::SYS_PATHS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/backtrace.rb:4: warning: previous definition of SYS_PATHS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/backtrace.rb:7: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/backtrace.rb:7: warning: previous definition of SUPPRESSED_PATHS was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/backtrace.rb:11: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS_RE
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/backtrace.rb:11: warning: previous definition of SUPPRESSED_PATHS_RE was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/backtrace.rb:15: warning: already initialized constant Rake::Backtrace::SUPPRESS_PATTERN
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake/backtrace.rb:15: warning: previous definition of SUPPRESS_PATTERN was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake.rb:78: warning: already initialized constant FileList
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake.rb:78: warning: previous definition of FileList was here
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake.rb:79: warning: already initialized constant RakeFileUtils
  /Users/janko/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rake.rb:79: warning: previous definition of RakeFileUtils was here
  ```

**Comment by jeremyevans** [comment]
The fourth option you gave is correct.  See http://sequel.jeremyevans.net/rdoc/files/doc/testing_rdoc.html#label-Testing+Sequel+Itself

Remove `-w` from your `RUBYOPT` when testing if you don't want warnings.

Note that this is not a bug in Sequel, so per the contribution guidelines, you should be asking questions like this on the sequel-talk Google Group.

**Comment by janko-m** [comment]
Thank you for the answer. I was actually hoping to ask you if it's possible to make `bundle exec rspec` work? It makes sense to have convenience Rake tasks, but I think tests should also be runnable directly with RSpec's command-line tool.

My `$RUBYOPT` doesn't contain anything, it's just that Rake was somehow required twice, so Ruby reports already initialized constants, which is a type of warning that is always outputted, regardless of `-w`. It just seems like there is something wrong going on. Don't you get these warnings? I use Ruby 2.2 and Rake 10.4.2.

**Comment by jeremyevans** [comment]
I'm not sure how to make `bundle exec rspec` work, but I don't consider that important.  There are a bunch of different test suites, `bundle exec rspec` wouldn't know which ones to run.  With rake, there are separate tasks for each of the different test suites.

I don't get the warnings you do, and neither does Travis (which runs `bundle exec rake spec_travis`), so I'm not sure why they are occurring for you.
